### ISSUE TITLE
[feature-request] Richer syntax definition

### ISSUE THREAD

**Issue by Shians** [Ikuyadeu/vscode-R#10]
Could I suggest adding richer syntax definitions and highlighting? Something like https://github.com/randy3k/R-Extended?

**Comment by Ikuyadeu** [comment]
@Shians Great! I'll hope your help. Thank you.
I think same developers https://github.com/randy3k/R-Box/syntax product is better. Because it is MIT license and updating still.

**Comment by Ikuyadeu** [comment]
@Shians In new version, it has been expanded from Rbox.
But it's immature and R markdown and R documentation are yet.

**Comment by Shians** [comment]
I can't quite get my head around how these tmLanguages are written, it seems to be very hard to read or write by hand. Some resources suggest they are compiled from a JSON file but nobody provides the source JSONs. Upon comparison with the highlighting in Sublime I see that the main difference is for function calls to be highlighted.

Since base VS Code has an R syntax I wonder if it's worthwhile figuring out the syntax definition for a function call then pulling it into the main project.

**Comment by Ikuyadeu** [comment]
OK, now I'm making script that convert sublime-syntax to JSON, and submited PR to VS Code base.

**Comment by schelhorn** [comment]
Along these lines, I'd also very much appreciate if code symbols could be included in the extension as well; this would enable IntelliSense auto completion and browsing by symbol which is essential for larger projects.

**Comment by Ikuyadeu** [comment]
@schelhorn Looks good. I'll try it, thank you!

**Comment by Ikuyadeu** [comment]
Sorry, my reply is late.
@Shians In Microsoft/vscode@012d7da, this repository will be referenced original VS Code repository Microsoft/vscode#28982, and VS Code user can use better R syntax without installing this extension.
So, this repository will update continually and take latest syntax.

@schelhorn, We will create IntelliSence autocompletion by https://github.com/REditorSupport/languageserver #24.
