### ISSUE TITLE
R Terminal loses purchase of old terminals

### ISSUE THREAD

**Issue by MaTo04** [Ikuyadeu/vscode-R#102]
Actual it isn't possible to switch between R-Terminals. After creating a new Terminal only the last one is active.

**Comment by andycraig** [comment]
I am working on a new command that will allow code to be sent to the currently active terminal, which should provide a solution to this problem.

**Comment by MaTo04** [comment]
Perfect, thank you for your solution.

**Comment by MaTo04** [comment]
Thanks for implement this issue but for me its difficult to use it. Could you please give an introduction how to use it ? If i start multiple R-Terminals for me it`s not possible to switch to the second last.

**Comment by Ikuyadeu** [comment]
@MaTo04 I just publish new version now.
Please try again after installing that.

**Comment by MaTo04** [comment]
Sorry for the late reply. I tried it and it works perfektly. Thank you.
