### ISSUE TITLE
Goto definition across scripts

### ISSUE THREAD

**Issue by LePeti** [Ikuyadeu/vscode-R#105]
As far as I know it is not possible atm to jump to the definition of functions (as with pressing F2 in RStudio). Would it be possible to implement? Thanks

**Comment by Ikuyadeu** [comment]
@LePeti This function is implemented on other language support (like javascript.)
Currently, it looks a bit difficult to implement.
I put this issue as the TODO.

**Comment by BernierCR** [comment]
I would definitely like this too if you can ever get around to it.

**Comment by andycraig** [comment]
Go to Definition is now supported on the `master` branch of the `languageserver` package. Install with: 

    devtools::install_github("REditorSupport/languageserver")

**Comment by Ikuyadeu** [comment]
@andycraig Great works!!
