### ISSUE TITLE
commands not found after 1.0.7 update

### ISSUE THREAD

**Issue by yh-luo** [Ikuyadeu/vscode-R#106]
**Describe the bug**
Commands failed to run after updating to 1.0.7. I tried reinstall the extension (1.0.7), reinstall vs-code, both did not fix the problem.
Currently tested with:
```
command 'r.runSelection' not found
```
```
command 'r.runSource' not found
```

**To Reproduce**
1. File -> Open Folder... -> Open a folder containing R source files.
2. `ctrl`+`enter`

**Do you want to fix by self? (I hope your help!)**

Reinstalling the extension of version **1.0.6** fixed the problem 

(Sorry I don't know how to fix it :cry: )

**Expected behavior**
Commands should be executed.

**Environment (please complete the following information):**
 - OS: Fedora 29 (Linux)
 - VSCode Version: 1.33.1
 - R Version: 3.5.3, Platform: x86_64-redhat-linux-gnu (64-bit)

**Comment by futuraprime** [comment]
I'm having the same problem. 1.0.6 is fine, 1.0.7 won't run R code.

OS: macOS 10.12.6
VSCode: 1.33.1
R: R version 3.5.3, Platform: x86_64-apple-darwin16.7.0 (64-bit)

**Comment by ndegara** [comment]
Same issue in MacOs Mojave 10.14.2

**Comment by beansrowning** [comment]
Same issue in Windows 10 with 1.0.7.

Downgrade to 1.0.6 resolves

**Comment by Ikuyadeu** [comment]
Sorry for good users, thank you for early inform.
I fixed and published the new version now.
Please try again that.

**Comment by beansrowning** [comment]
@Ikuyadeu Upgrading to 1.0.8 resolved my issues. Thanks for the quick response!

**Comment by yh-luo** [comment]
@Ikuyadeu I confirmed that the issue was fixed after upgrading to 1.0.8. Thanks for the good work!

**Comment by yh-luo** [comment]
@Ikuyadeu  I confirmed that the issue was fixed after upgrading to 1.0.8. Thanks for the good work!

**Comment by Ikuyadeu** [comment]
@beansrowning @yh-luo  I am glad to hear that, please happy coding

**Comment by deveops1996** [comment]
I don't know I'm felling totally frustrated and helpless. Recently I installed your latest version,did all the things as asked to set up the directory but cant run it .Those two dreadful errors always pop up.
command 'r.runSelection' not found
command 'r.runSource' not found
Please help me. Tell me what shall I do

**Comment by andycraig** [comment]
Hi @deveops1996, try:
File -> Open Folder...
Select the folder ‘Text Mining’ and click Open.
Then try the run selection or run source commands again.

**Comment by deveops1996** [comment]
> Hi @deveops1996, try:
> File -> Open Folder...
> Select the folder ‘Text Mining’ and click Open.
> Then try the run selection or run source commands again.

Yes I did and and it seems there has to be a workspace for the R interactive Terminal to open and run. Now its working after I have set the workspace folder

**Comment by AnBarbosaBr** [comment]
I´m getting this error on the version 2.2.0. Dowgrading to 2.0.0 solved the issue.

**Comment by renkun-ken** [comment]
> I´m getting this error on the version 2.2.0. Downgrading to 2.0.0 solved the issue.

Looks like you are trying to execute a vscode-R command without activating it? Does the same occur if you open an `.R` file?
