### ISSUE TITLE
Connect to (running) Jupyter Kernel

### ISSUE THREAD

**Issue by vnijs** [Ikuyadeu/vscode-R#107]
**Is your feature request related to a problem? Please describe.**
Plots are shown in a separate window and cannot be shown (unless you use X) when using code-server (i.e., vscode on a server running in a browser)

**Describe the solution you'd like**
Connect to a (running) R-jupyter kernel. This is possible in the Microsoft python extension (Python Interactive Window) and in Atom's Hydrogen extension. According to [Issue 2](https://github.com/Ikuyadeu/vscode-R/issues/2) it is possible to connect to an R-kernel through Jupyter but it is not clear to me how that would work.

The way it works with vscode python extension is that you provide a URL to connect to which could be local or remote. The process is very similar for Hydrogen: (https://github.com/nteract/hydrogen/blob/master/docs/Usage/RemoteKernelConnection.md)

For the docker image linked below you would connect to jupyter using:

http://localhost:8989/?token=jupyter

You can run a docker image from vnijs/rsm-editors or run a bash script through the command below and press 3 when the menu shows up. Jupyter lab will be accessible through localhost on port 8989. The "VS Code" icon will start code-server in the browser.

`source <(curl -s https://raw.githubusercontent.com/radiant-rstats/docker/master/launch-rsm-editors.sh)`

https://cloud.docker.com/u/vnijs/repository/docker/vnijs/rsm-editors

**Comment by randy3k** [comment]
As far as I know, vscode-R doesn't provide any mechanisms to connect to a jupyter kernel.

**Comment by vnijs** [comment]
There is this for python:

https://code.visualstudio.com/docs/python/jupyter-support#_connect-to-a-remote-jupyter-server

**Comment by vnijs** [comment]
Also, according to https://github.com/Ikuyadeu/vscode-R/issues/2 it does seem possible. @schelhorn could you comment on how you did (do) this perhaps?

**Comment by andycraig** [comment]
Hi @vnijs, this extension allows you to connect to a running Jupyter kernel and send R code to it:
https://marketplace.visualstudio.com/items?itemName=pavan.VSNotebooksBeta
It does show plots within VSCode although I'm not sure whether it will work with code-server.

**Comment by vnijs** [comment]
Thanks @andycraig. Looks promising, but I'm getting a 500 error. Any settings that are required that you know of to make this work?

**Comment by andycraig** [comment]
@vnijs It took a bit of trial and error to get it working. Here is the method that I used, in Linux:

Create a directory containing a Python virtual environment with the necessary packages, and a test R file:

```
mkdir vsnotebook-test
cd vsnotebook-test
python3 -m venv env
source env/bin/activate
python3 -m pip install jupyter matplotlib
echo 'print("Hello World")' > test.R
```

If you haven't already, set up an R kernel for Jupyter by doing the following in R:
```
install.packages("IRkernel")
IRkernel::installspec()
```

In VSCode:
1. Open `vsnotebook-test/test.R` (you need to have an R or Python file open for the extension to activate)
1. In a terminal: `jupyter notebook`
1. Command: `IPE: Open Output Pane with Existing Jupyter Notebook`
1. One of the options that appears should be the Jupyter session just started. Select that.
1. Position the cursor somewhere in `test.R` and hit `Alt-Enter`. For me, that sends the code to the output pane. I've found that sometimes if the cursor is at the very end of the line, it doesn't work.

If you're on Linux, hopefully that will work for you too! If not, there might be some ideas in there that will help.

**Comment by vnijs** [comment]
Thanks @andycraig. That works with vscode and code-server in docker! I can connect to a local R-kernel and to an R-kernel running in a docker container. I do have to use the "enter manually" option, however, because the extension doesn't seem to pick up settings (shown below) automatically. That said, this is a very nice step forward.

![image](https://user-images.githubusercontent.com/2998956/56611935-e8ca9a80-65c7-11e9-8573-31bce0808942.png)

**Comment by andycraig** [comment]
Great to hear it works (mostly), and with code-server too!
