### ISSUE TITLE
debug dataframe

### ISSUE THREAD

**Issue by lfjbb** [Ikuyadeu/vscode-R#110]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andycraig** [comment]
Hi @lfjbb, this extension provides a command `R: Preview Dataframe`. Perhaps that does what you want? There is also an issue already open about an environment/variable viewer (#47). If neither of these are what you have in mind, could you provide some more information? Thank you.
