### ISSUE TITLE
Line breaks in markdown break highlight

### ISSUE THREAD

**Issue by ying-w** [Ikuyadeu/vscode-R#116]
**Describe the bug**
Using line breaks in markdown `***` will break syntax highlighting on Rmd files

**To Reproduce**
Have an Rmd file:

`````
# this is a test

```{r test1}
# syntax highlighting works fine here
library(iris)
head(iris)
```

below is a line break

***

```{r test2}
# syntax highlighting no longer works
library(iris)
head(iris)
```

## even the markdown highlighting breaks

***

```{r test3}
# syntax highlighting works again
library(iris)
head(iris)
```

## highlighting works again

`````

**Do you want to fix by self? (I hope your help!)**

No :(

**Expected behavior**
Syntax highlighting work between line breaks

**Environment (please complete the following information):**
 - OS: OSX
 - VSCode Version: 1.35
 - R Version: 3.5.1
- Plugin version: 1.1.1

**Comment by andycraig** [comment]
I think this is a problem with our Rmd syntax. In VSCode's markdown highlighting it seems fine.
