### ISSUE TITLE
Messy indentation in console when sending text to Radian

### ISSUE THREAD

**Issue by andycraig** [Ikuyadeu/vscode-R#117]
- VSCode Version: 1.33.1
- VSCode-R Version: 1.1.1
- OS Version: Ubuntu 18.04.2 LTS

See https://github.com/randy3k/radian/issues/99

I have a working fix for this using bracketed paste mode (thanks @randy3k!): https://github.com/andycraig/vscode-R/tree/bracketed-paste

@Ikuyadeu I think there are two options here:
1. Introduce a 'Bracketed paste mode' option, that users can set if they're using Radian.
2. Always use bracketed paste mode. This works for both Radian and the normal R console, but slightly changes the appearance of how code is send to the R console:

Without bracketed paste mode (current version of vscode-R) - note the '+' on each line in the console: 

![bracketed_paste_before](https://user-images.githubusercontent.com/23294156/62407648-b2ed7700-b5f6-11e9-9ded-c86074436ce9.png)

With bracketed paste mode - no '+':

![bracketed_paste_after](https://user-images.githubusercontent.com/23294156/62407643-a406c480-b5f6-11e9-9bbc-086361431fa7.png)

So, functionally they are the same, but always using bracketed paste mode would slightly change the appearance of the R console from its current form.

**Comment by randy3k** [comment]
FYI, R with readline 6 or before do not support bracketed paste mode.

**Comment by andycraig** [comment]
Ah, in that case it would probably be best to have bracketed paste mode as an option, which users can set if they are using Radian. I will implement that.

**Comment by nlneas1** [comment]
FYI, I reported [here](https://github.com/randy3k/radian/issues/99#issuecomment-530341339) that this is working for me. My setup is as follows:

VS Code:

```
Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.16299
```

Radian / R / Python:

```
radian version: 0.3.4
r executable: /usr/lib/R/bin/R
r version: 3.4.4
python executable: /usr/bin/python
python version: 2.7.15
```

Note, I use VS Code on Windows but I route through to a linux server (which is where I do all of my coding).

```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
```

**Comment by renkun-ken** [comment]
I notice that I didn't use r.runSelectionInActiveTerm action but vscode built-in send-code action. I bind Cmd+Enter to r.runSelectionInActiveTerm and the bracketed paste works.

**Comment by andycraig** [comment]
@renkun-ken Phew, that’s good to hear!

**Comment by andycraig** [comment]
I'm still trying to work out the best way to handle this in Windows. @Hong-Revo Before bracketed paste mode was added, did you have messy indentation when sending code to radian?

For me, when using Windows, the indentation is fine without bracketed paste mode. I'm wondering if the solution is to recommend bracketed paste mode for radian when using Linux/Mac, but not Windows.

**Comment by Hong-Revo** [comment]
I think the only indentation issue I'm having is that sometimes, Radian will treat a single multi-line block of submitted text as a group of lines. For example:

```
f <- function(x)
{
    if(x)
        return(42)
    else
    {
        if(TRUE)
            23
        else 69
    }
}
```

When I submit this, it shows up as:

![image](https://user-images.githubusercontent.com/11328890/65848712-ac774380-e38a-11e9-8b82-f3a2f2d0d2e6.png)

Note the "+" in the middle. Also, sometimes radian thinks there is more text coming and I have to press Enter in the terminal to get it to process the submitted code. This is with bracketed paste on.

**Comment by andycraig** [comment]
@Hong-Revo I have that issue with needing to press Enter as well. I haven’t noticed the ‘+’ issue but I imagine it’s happening for me too so I’ll look out for it.

Thank you for providing that info, it’s very helpful. I’ll keep investigating what the best approach for Windows is.

**Comment by andycraig** [comment]
Code is sent to the console one line at a time. It might be that sending all lines at once works better with Radian. I will try that and see if it fixes the problems on Windows.

**Comment by andycraig** [comment]
I've pushed a version that seems to work to https://github.com/andycraig/vscode-R/tree/radian-send 

I have tested it on Windows and Linux (Ubuntu). If anyone else wants to test this for me (especially Mac users!) that would be great. Remember to enable the `R: Bracketed Paste` setting. Try sending the following code to an active radian terminal:

```
f <- function(x)
{
    if(x)
        return(42)
    else
    {
        if(TRUE)
            23
        else 69
    }
}
```

On Windows, it sends the code all at once, without using bracketed paste ASCII codes.

On non-Windows, it sends the code all at once, using bracketed paste ASCII codes.

It breaks the `r.nrow` family of commands, and the code is messy, so I will clean up before doing a PR.

**Comment by andycraig** [comment]
This julia-vscode issue and PR suggest that using bracketed paste for operating systems other than Windows is indeed the right approach:

https://github.com/julia-vscode/julia-vscode/issues/805#issuecomment-525014114

https://github.com/julia-vscode/julia-vscode/pull/840/files
