### ISSUE TITLE
Auto create roxygen comment on new line

### ISSUE THREAD

**Issue by renkun-ken** [Ikuyadeu/vscode-R#124]
When I write roxygen comments, it would be convinient if the new line is automatically commented with `#'`.

For example, when I try to add a new line in the middle or at the last line, the new line can be automatically added `#'` to save key strokes.

```r
#' Test function
#' @param x an object
#' @param check a function
######## new line here #########
#' @export
#' @examples
#' test(NULL, is.null)
#' test(0, is.null)
######## new line here #########
test <- function(x, check) {
  if (check(x)) {
    x
  } else {
    stop("Check failed")
  }
}
```

**Comment by renkun-ken** [comment]
I'm also curious if it is possible for `vscode-R` to provide auto-completion of those roxygen entries such as `@param`, `@export`, etc.?

**Comment by andycraig** [comment]
I think auto-completion for roxygen entries should be fairly straightforward, using a `CompletionItemProvider` that triggers on `@` and checks that the line starts with `#'`.

**Comment by andycraig** [comment]
@renkun-ken Can you make a separate issue for roxygen auto-completion?

**Comment by andycraig** [comment]
It might be possible to leverage this extension for automatic `#'` commenting:

https://marketplace.visualstudio.com/items?itemName=kevinkyang.auto-comment-blocks

**Comment by renkun-ken** [comment]
A separate issue here #128.

**Comment by andycraig** [comment]
I have a working implementation here: https://github.com/andycraig/vscode-R/tree/issue-124-roxygen-newline 

It flickers, though (I think as a result of VSCode's `replace`), so I'm going to see if I can solve that before doing a PR.

**Comment by renkun-ken** [comment]
I also asked if vscode-cpptools could provide Rcpp roxygen comment `//'` being auto-inserted on new line at <https://github.com/microsoft/vscode-cpptools/issues/4303> and it already has support for customizable prefix. Hope this is useful.

**Comment by andycraig** [comment]
@renkun-ken That is helpful, thank you!
