### ISSUE TITLE
Run selection should move cursor down the line start

### ISSUE THREAD

**Issue by renkun-ken** [Ikuyadeu/vscode-R#126]
Currently, run selection send code to terminal and move cursor down to the next line, and move cursor to line end.

In my case, there are often relatively long lines and short lines. If cursor is always moved down to line end, then the editor view will move left and right, which is quite annoying.

I suggset moving cursor to line start with `wrappedLineStart` or `wrappedLineFirstNonWhitespaceCharacter` (which I prefer and believe is more natural).

**Comment by andycraig** [comment]
Resolved by #127. Thanks @renkun-ken!
