### ISSUE TITLE
Auto-completion in roxygen comment

### ISSUE THREAD

**Issue by renkun-ken** [Ikuyadeu/vscode-R#128]
It would be nice to have auto-completion of roxygen documentation entries such as `@params` and `@export`.

```r
#' Test function
#' @param x an object
#' @param check a function
#' @export
#' @examples
#' test(NULL, is.null)
#' test(0, is.null)
test <- function(x, check) {
  if (check(x)) {
    x
  } else {
    stop("Check failed")
  }
}
```

**Comment by andycraig** [comment]
I think auto-completion for roxygen entries should be fairly straightforward, using a `CompletionItemProvider` that triggers on `@` and checks that the line starts with `#'`.

**Comment by andycraig** [comment]
I'm happy to have a go at this one, although it might take me a month or so. @renkun-ken If you'd like to work on it before then, let me know and I'll leave it to you.

**Comment by renkun-ken** [comment]
@andycraig I'm not sure how `CompletionItemProvider` and the trigger work. If you are happy to have a go, please. Thanks! I'll take a look and learn how you do this.
