### ISSUE TITLE
S3 and S4 classes autocomplete

### ISSUE THREAD

**Issue by hmassalha** [Ikuyadeu/vscode-R#132]
Hi, 
Would be nice to have the possibility that R extensions will provide an autosuggestion feature for S4 and S3 classes subfield (variables) while typing.
Thanks, HM

**Comment by renkun-ken** [comment]
Auto completion is provided by [languageserver](https://github.com/REditorSupport/languageserver). Please file or transfer the issue there.

**Comment by andycraig** [comment]
This would definitely be a nice feature. There is a similar issue for R6 classes at the language server repo: https://github.com/REditorSupport/languageserver/issues/75 If/when R6 classes are handled, it should be possible to handle S4 classes by the same mechanism.
