### ISSUE TITLE
Internal R terminal says package is missing when it is not. 

### ISSUE THREAD

**Issue by RaghuNaik** [Ikuyadeu/vscode-R#134]
Vscode-R recognizes the R installation and is able to send the commands from the rmd file to the terminal. 

The issue I have is that Vscode-R does not recognize the local library where the r packages are installed and is specified in the rprofile.site file through the .libPaths() command. 

Because if this reason I get the error command saying that the package is not installed, when in fact it is installed in the local library. 

Thanks for the help and this package.

R

**Comment by andycraig** [comment]
Hi, does it work fine if you start an R session in a terminal? (Not in VSCode.)

In VSCode, what is your `r.rterm.option` setting?

**Comment by RaghuNaik** [comment]
Hi Andy, yes it works fine when I start a R session in the terminal.  Here is the snapshot.

![image](https://user-images.githubusercontent.com/6098486/66499043-e8d62e00-ea73-11e9-98f4-037678f21f4a.png)

The snapshot in the internal terminal is:

![image](https://user-images.githubusercontent.com/6098486/66499191-2b980600-ea74-11e9-8a8e-2e74f88b2096.png)

In extension settings of the path is C:\Program Files\R\bin\x64\R.exe. 

Thanks for your help.

R

**Comment by andycraig** [comment]
The first screenshot contains some text about ‘Microsoft R Open’ whereas the second one doesn’t, which makes me wonder if different R versions are being called.

In a terminal (not a VSCode terminal), if you run the below command, do you get the ‘Microsoft R Open’ text in the output?

```
 C:\Program Files\R\bin\x64\R.exe.
```

**Comment by RaghuNaik** [comment]
Sure.  As below. Executed the command from the c: prompt. Thanks.


![image](https://user-images.githubusercontent.com/6098486/66611701-389c1e80-eb74-11e9-9ed8-1e52471e086e.png)

**Comment by andycraig** [comment]
Thank you for checking that. It’s strange that the output is different depending on where R is called from (terminal or VSCode). I’m traveling at the moment but will try to duplicate this when I get back.

I’m guessing your OS is Windows? What is the `r.rterm.option` setting VSCode?

**Comment by RaghuNaik** [comment]
Yes I am using windows 10. Also I do not see any settings for r.rterm.opton in my setting.json file. Should I be having one? Thanks.

**Comment by andycraig** [comment]
If there’s no `r.term.option` in your settings file it means it’s set to the default. Thank you for checking :)

**Comment by andycraig** [comment]
One of the arguments in the `r.term.options` default is `--no-site-file`, which is probably causing your `rprofile.site` file to be ignored. (The other arguments are `--no-save` and `--no-restore`.) Try adding this to your `settings.json` file and see if the problem goes away:

```
"r.term.options": [
        "--no-save",
        "--no-restore"
]
```

**Comment by RaghuNaik** [comment]
Also, after struggling a bit, I realized it should be r.**rterm**.option . 

Now everything works fine. 

Thank you for your help on this. 

Regards.

**Comment by andycraig** [comment]
Sorry about that, I managed to make a lot of mistakes in one line short line! Glad to hear it’s now working. We’ve updated the settings display (#136) so hopefully this sort of problem would be easier to identify/solve in future.

Thank you for your perseverance and for using vscode-R!
