### ISSUE TITLE
Activating extension 'Ikuyadeu.r' failed: Cannot read property '0' of undefined.

### ISSUE THREAD

**Issue by benwbooth** [Ikuyadeu/vscode-R#135]
**Describe the bug**

When opening an R file, I am only able to edit one character, then the editor locks up and I cannot move the cursor or edit any more. Also, I get this error in the developer console when loading an R script in VS code:

```Activating extension 'Ikuyadeu.r' failed: Cannot read property '0' of undefined.```

Here is the stack trace:

```
_logMessageInConsole @ abstractExtensionService.ts:396
_logOrShowMessage @ abstractExtensionService.ts:410
$onExtensionActivationError @ mainThreadExtensionService.ts:70
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
_register._socket.onData.e @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
```

**Environment (please complete the following information):**
 - OS: macOS Mojave
 - VSCode Version 1.39.1
 - R Version 3.6.1

**Additional context**

**Comment by andycraig** [comment]
Hi, can you check that the same error occurs if you disable all extensions except vscode-r and vscode-r-lsp? Thank you.

**Comment by andycraig** [comment]
Hi @benwbooth, there have been a couple of updates to vscode-R so could you check whether this still happens?

Please do the following:

1. Create a folder `temp-r` containing a file `temp.R`, which contains only the text

```
iris
```

2. Check that the vscode-R version is 1.1.7
3. Disable all extensions except vscode-R and vscode-r-lsp
4. Use ‘Open Folder...’ and select `temp-r`
5. See whether the error happens, and whether you can move the cursor in `temp.R` without it locking up

Thank you!

**Comment by benwbooth** [comment]
It seems to be working OK again in 1.17. It's OK to close this issue. If I run into it again I will create a new issue. Thanks!

**Comment by andycraig** [comment]
Great! Thank you!
