### ISSUE TITLE
Use variable under cursor for r.previewDataframe, r.nrow etc.

### ISSUE THREAD

**Issue by andycraig** [Ikuyadeu/vscode-R#137]
When there is no selection, it would be good if the following commands operated on the variable the cursor is on:

`r.previewDataframe`, `r.nrow`, `r.length`, `r.head`, `r.thead`, `r.names`

**Details**

Consider the following file:

```
library(ggplot2)
ggplot(iris, aes(Sepal.Width, Sepal.Length)) +
    geom_point()
```

When the cursor is on `iris` in line 2, I think it would make sense for `r.previewDataframe` etc. to act on `iris`. But calling `r.previewDataframe` results in the message 'This does not appear to be a dataframe'. Calling `r.nrow` results in in following appearing in the console:

```
> nrow(ggplot(iris, aes(Sepal.Width, Sepal.Length)) +)
Error: unexpected ')' in "nrow(ggplot(iris, aes(Sepal.Width, Sepal.Length)) +)"
> nrow(geom_point())
NULL
```
 
The reason is that the above commands use `getSelection()` to decide what to act on. When there is no selection, `getSelection()` tries to find the 'minimum runnable block of code', which in the above example is lines 2-3.

@MaTo04 Thank you for adding the `r.nrow` family of commands! Does this suggestion sound okay to you? I don't want to break a use case I haven't thought of.

**Comment by andycraig** [comment]
Also, under this proposal the cursor would remain where it is, instead of moving down one or more lines.

**Comment by andycraig** [comment]
Add something to README about using custom R functions as well as `nrow` etc.

**Comment by MaTo04** [comment]
Sorry about the late reply. This feature is very helpful but i think it doesn´t work. I tried to follow the instruction but get the error: "ENOENT: no such file or directory, mkdir '/c:/GIT/tmp'". Could you please give a detailed instruction how to use it ?

**Comment by andycraig** [comment]
Hi @MaTo04, the `r.nrow` command should still work in the same way it did when you implemented it. Did you try `r.nrow` or `r.previewDataframe`?

Here are more detailed instructions:

1. Create a directory `temp-r`
2. In `temp-r`, create a file `temp.R` with the following content:

```
library(ggplot2)
ggplot(iris, aes(Sepal.Width, Sepal.Length)) +
    geom_point()
```

3. Use ‘Open Folder...’ and select `temp-r`
4. Open `temp.R`
5. Place the cursor on `iris` (line 2)
6. Use the command `R: Preview Dataframe`
7. Place the cursor on `iris` (if it’s not there already)
8. Use the command `R: Show number of rows for selected object`

If you still get an ENOENT error, that’s probably a bug.

**Comment by andycraig** [comment]
@MaTo04 I have created a PR with some videos that show the proposed changes (#141).
