### ISSUE TITLE
Unable to preview dataframes

### ISSUE THREAD

**Issue by shinout** [Ikuyadeu/vscode-R#139]
Hi, I found that a commit you did three days ago for refactoring may break the functionality of `previewDataframe()`.

The reason should be that single quotations are duplicated here.
https://github.com/Ikuyadeu/vscode-R/blob/master/src/preview.ts#L46

I hope this will be fixed soon. Thanks.

**Comment by Ikuyadeu** [comment]
@shinout Thank you for using the extension and submitting the bug information.
I can fix that soon by your point fault localization.

**Comment by AmineI** [comment]
I'm not sure it is the same issue, it may be related to #92 actually : but on Windows a starting "/" before the actual path prevents the extension to create/access the tmp directory. Since the tmp directory is used to preview environment / dataframe, this functionality is broken as well. 

The issue was introduced in 1.1.5, as 1.1.4 works fine. 

 ![image](https://user-images.githubusercontent.com/15179425/68781679-6c1d0d80-0638-11ea-90f1-f8bb7f5d25ba.png)

**Comment by ChristopheRoyer21** [comment]
> I'm not sure it is the same issue, it may be related to #92 actually : but on Windows a starting "/" before the actual path prevents the extension to create/access the tmp directory. Since the tmp directory is used to preview environment / dataframe, this functionality is broken as well.
> 
> The issue was introduced in 1.1.5, as 1.1.4 works fine.
> 
> ![image](https://user-images.githubusercontent.com/15179425/68781679-6c1d0d80-0638-11ea-90f1-f8bb7f5d25ba.png)

I have the same error

**Comment by andycraig** [comment]
@ChristopheRoyer21 Thank you for reporting. What OS are you using?

@AmineI Thank you for tracking the starting ‘/‘ down to the version in which it was introduced.

**Comment by ChristopheRoyer21** [comment]
> @ChristopheRoyer21 Thank you for reporting. What OS are you using?

My OS is Windows 10
VS Code version: 1.41.4

Don't hesitate to ask me any questions to help you. This feature might be the final reason to make me switch from RStudio. Thank you for all the changes you made in the last year. I initially overlooked VS Code for my R sessions but now it looks so much better!

**Comment by andycraig** [comment]
@ChristopheRoyer21 Thank you for providing that info and for the positive comments!

I suspect that a fix might be to create `tmpDir` with `uri.toString()` rather than `uri.path`, based on the examples here: https://github.com/microsoft/vscode-uri#usage

**Comment by andycraig** [comment]
Nope, `toString()` didn't work because it mangles the drive colon (e.g., `d:` becomes `d%3a`). Suggestion here https://github.com/microsoft/vscode/issues/2990 is to use `fsPath` instead.
