### ISSUE TITLE
new vscode R terminal execution produces Error: unexpected symbol in "activate vst"

### ISSUE THREAD

**Issue by myusrn** [Ikuyadeu/vscode-R#140]
**Describe the bug**
new vscode R terminal execution of any line of code, e.g. print('hello R terminal'), produces Error: unexpected symbol in "activate vst"

**To Reproduce**
1. I install the latest R 1.1.7 extension into my current vscode 1.39.2 where windows 10 1903 (18362.10024) has cran R-3.6.1-win.exe installed.   

2. Added settings.json line "r.rterm.windows": "C:\\Program Files\\R\\R-3.6.1\\bin\\x64\\R.exe" and restarted vscode

3. create Test.R containing just print('hello R terminal') and then use ctrl+enter to cause R extension to open R terminal and execute that line

4. error is . . .
expected: new R terminal initialization info and then execution of selected line of code
actual: new R terminal initialization info and then 
> activate vst
Error: unexpected symbol in "activate vst"

Once terminal is open i can re-execute any line of code and things are working fine but this failing 'activate vst' line has me concerned that some bit of R extension functionality will not be working properly unless i do what is necessary to correct it.

**Do you want to fix by self? (I hope your help!)**
No - i did some searching and couldn't really figure out if this was resulting from an expected R client "vst" package being missing but couldn't find any details that led to resolution.

```json
// R.exe path for windows
"r.rterm.windows": "C:\\Program Files\\R\\R-3.6.1\\bin\\x64\\R.exe",
```

**Environment (please complete the following information):**
 - OS: Windows 10 1903 (18362.10024)
 - VSCode Version 1.39.2
 - R Version 3.6.1

**Additional context**
n/a

**Comment by myusrn** [comment]
i closed and reopened vscode and tried to repro this again and it no longer repros so not sure what i changed to cause new R terminal initialization error `>activate vst` to go away.

**Comment by andycraig** [comment]
@myusrn Glad to hear the problem disappeared! Just wanted to say a thank you for the very clear description of the issue.
