### ISSUE TITLE
Setting working directory to ${fileDirname} when opening terminal

### ISSUE THREAD

**Issue by janxmares** [Ikuyadeu/vscode-R#148]
Hi,

I might be missing something, but is there a way to set the working directory to the currently opened file when launching R terminal in VSC? 

I could not find any workaround in the current setup.

Many thanks!

**Comment by andycraig** [comment]
Hi, as far as I know there is no feature for this in this extension. But a couple of months ago VSCode added a command to open a terminal in the location of the current file: https://code.visualstudio.com/updates/v1_39#_open-new-terminals-with-custom-working-directories

It would probably be possible to create a [macro](https://marketplace.visualstudio.com/items?itemName=geddski.macros&ssr=false) that does this then writes ‘R’ to the terminal to open an R session there.

Someone else might know of a more straightforward way to do this.

**Comment by janxmares** [comment]
Thank you for the hint on macros. I realized that if you start the terminal while having a folder opened, it starts with the working directory set to that folder. So this provides desired functionality, although it requires specific procedure - finding a file in the folder opened in VSC and opening from there rather than directly from the file browser. Applies to Win at least.

**Comment by andycraig** [comment]
I think that’s VSCode’s assumed workflow - that you’ll open a project using ‘Open Folder...’ and then work in that folder.

Sounds like you found what you were after, so that’s good to hear!

**Comment by andycraig** [comment]
@janxmares It sounds like this issue is resolved so I'm going to close it, but if you don't consider it resolved please post and I can look into it further.

**Comment by ArnossArnossi** [comment]
Just in case someone else is also stumbling over this question in the distant future: R also provides a method for setting the current working directory from within the R terminal: `setwd([dir])` and `getwd()`.
While this doesn't switch the cwd automatically it might still be helpful.

Ref: https://stat.ethz.ch/R-manual/R-devel/library/base/html/getwd.html

Please feel free to delete this comment again if I missunderstood the question or if posting long after the fact is considered inappropriate.

**Comment by Fionn-McGlacken** [comment]
@janxmares Did you ever find a good fix for this? I am experiencing the same issue. Many thanks.

**Comment by janxmares** [comment]
@Fionn-McGlacken Not really, I adopted the workflow [mentioned above](https://github.com/REditorSupport/vscode-R/issues/148#issuecomment-559614157) and I use it ever since.

**Comment by gremms1** [comment]
In case others are looking for an easy solution: 
```
# Install the rprojroot package if not already installed
if (!requireNamespace("rprojroot", quietly = TRUE)) {
  install.packages("rprojroot")
}

# Load the rprojroot package
library(rprojroot)

# Set the working directory
setwd(here::here())

# Check if working directory is set correctly
getwd()

```

**Comment by rikrdo89** [comment]
Is there an easy way to set the current directory of the R terminal in VScode to the directory of the file I am currently working on? I know I could use setwd() but changing the path syntax between windows and R is a bit annoying. Is there any easy way to do this? I have cwd set to ${fileDirname} in VScode but it seems like R terminal does not follow those settings. Rstudio has a nice feature when right clicking the title of an open file, there is an option to set the current directory to the path of the opened file.

**Comment by rikrdo89** [comment]
> Thank you for the hint on macros. I realized that if you start the terminal while having a folder opened, it starts with the working directory set to that folder. So this provides desired functionality, although it requires specific procedure - finding a file in the folder opened in VSC and opening from there rather than directly from the file browser. Applies to Win at least.

@janxmares Was there any settings you used to have the R terminal open in the directory of the opened folder? In my vscode, when click to open a new R terminal, radian opens in the project directory even if I have a folder or file  opened.

**Comment by jczimm** [comment]
Not pretty, but a decent workaround is to run `setwd(dirname(.vsc$rstudioapi_env$getSourceEditorContext()$path))` at the beginning of your script.

**Comment by HHalva** [comment]
```
{
      "type": "R-Debugger",
      "name": "Debug R Script",
      "request": "launch",
      "debugMode": "file",
      "workingDirectory": "${fileDirname}",
      "file": "${file}"
    }
```

Works for me -- and then run Debug R Script.

**Comment by waynelapierre** [comment]
> Not pretty, but a decent workaround is to run `setwd(dirname(.vsc$rstudioapi_env$getSourceEditorContext()$path))` at the beginning of your script. (Ref: https://stackoverflow.com/a/47045368)

Thanks for this great solution! Could you explain why it works? Does it work without RStudio installed?
