### ISSUE TITLE
Debugging R in Visual Studio not yet implemented

### ISSUE THREAD

**Issue by AndyLuckert** [Ikuyadeu/vscode-R#153]
Dear community,

**in this project, the README.md states that implementing a debugger is on the To-Do-List.
Are there any ongoing attempts? I would really love to be able to debug R in Visual Studio**.

Usually, I program in Python. Now with my R-script, I did the same steps as usual:
Setting a breakpoint at a line of desire, and simply press F5 to start the debugging process.
Unfortunately, the debug-config file "launch.json" doesn't comprise of a R-related dictionary entry such as e.g. for python:

```
        {
            "name": "Python: Current File (Integrated Terminal)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
```

If I imitate the above code-lines and exchange "python" with "R", it says there is no debugger installed named like that.
Searching the vscode market place for R-debugging doesn't seem to offer anything, which obviously contains a debugger.

The closest I found was the extension [R LSP Client](https://marketplace.visualstudio.com/items?itemName=REditorSupport.r-lsp).
Nevertheless, after installing it, there was no way for me to add an R-debugger to my launch.json-file,
since there doesn't appear anything related to R in the available options when clicking the Tab "Debug" > "Add configuration ...".

The simple way the debugging process is described [here](https://docs.microsoft.com/en-us/visualstudio/rtvs/debugging-r-in-visual-studio?view=vs-2017) doesn't work for me since when starting a debugging process via F5, vscode selects one of the available debuggers (I have various for python available, such as "Current File", "Remote", "Flask", Django",.. BUT NOTHING FOR R).

I'd be very happy to get some help, since I really don't want to install RStudio on my system just because I can't debug R-codes in Visual Studio.

Thank you very much in advance!
Kind regards,
Andreas

PS:
The R-version I use is the following:
_R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)_

**Comment by renkun-ken** [comment]
Related: #89

**Comment by andycraig** [comment]
Hi @AndyLuckert, thank you for trying vscode-R! It would definitely be nice to have better debugging support for R in VSCode. As mentioned, #89 is an open issue for that so I’m going to close this issue.
