### ISSUE TITLE
Support SVG plot view

### ISSUE THREAD

**Issue by renkun-ken** [Ikuyadeu/vscode-R#159]
SVG Plot is generally a better way to present statistical graphics as its name suggests (Scalable Vector Graphics). To present SVG in VSCode, we need to use `svg()` instead of `png()` to capture the replayed graphics, and on VSCode side, we have the following options:

1. Open the SVG file but VSCode by default shows the XML source code of the SVG file instead of preview it (in constrast with PNG). In this case, an SVG previewer extension is required to view it.
2. Use WebView to present the SVG file.

The drawback of SVG is obvious too and it is mainly performance issue. When the graphics contains too many elements, the plotting can be very slow, and the resulted SVG file is also big, which makes it both slow to write and slow to read.

https://github.com/renkun-ken/vscode-R/tree/svg is an initial implementation of using SVG instead of PNG for graphics.

**Comment by vnijs** [comment]
Interesting. I'd like to test this out but I'm not sure about the build process for a VSCode extension. Would be even nicer if a build was was done through CI like microsoft with their python extension

https://github.com/Microsoft/vscode-python/blob/master/CONTRIBUTING.md#development-build
