### ISSUE TITLE
utils::browseURL

### ISSUE THREAD

**Issue by vnijs** [Ikuyadeu/vscode-R#166]
In the latest version of the R extension with `r.sessionWatcher": true` trying to open an external URL create a new tab in VSCode for a webview but the screen remains black. 

```
utils::browseURL("https://gitlab.com/")
```

**Comment by renkun-ken** [comment]
In the developer tools, it says

```
[Embedded Page] Refused to display 'https://about.gitlab.com/' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' https://gitlab.lookbookhq.com https://learn.gitlab.com".
```

We cannot walk around such security policy of WebView at the moment. See https://github.com/Microsoft/vscode/issues/65595#issuecomment-450266698.

**Comment by vnijs** [comment]
Interesting. Thanks for following up @renkun-ken. Given that "Many websites block being embedded in iframes using x-frame-options" do you think it possible to have, for example, all https site open up in an external brower? Or perhaps anything that isn't run on localhost?
