### ISSUE TITLE
SessionWatcher: "Could not find function `str`"

### ISSUE THREAD

**Issue by pat-s** [Ikuyadeu/vscode-R#168]
Seems like `str()` in l.57 needs to be replaced by `utils::str()` to successfully execute `~/.vscode-R/init.R`.

Due to 

> Each time the extension is activated, the latest session watcher script (init.R) will be deployed to ~/.vscode-R/init.R.

I can't solve this by manually changing to `utils::str()`.

Wondering a bit that I seem to be the first stumbling across this? Or am I missing something? 🤔 

Thanks for your effort!! 🚀

**Comment by renkun-ken** [comment]
Thanks for your reporting!

**Comment by pat-s** [comment]
Oh, that was quick ;) 

Is there any way how one can install the dev version of the extension? Searching the web for this was not really helpful. (Assuming that the fix won't directly result in a new release).

**Comment by renkun-ken** [comment]
I'm maintaining a cutting-edge branch https://github.com/renkun-ken/vscode-R/tree/test which is the latest development version with all my PR at https://github.com/Ikuyadeu/vscode-R/pulls are merged.

I'll take a look at how to generate automatic build on push so that the latest build from this branch can be downloaded for testing.

**Comment by pat-s** [comment]
Thanks, installed the languageserver dev branch.
However, installing an extension not being listed in the marketplace (or just a custom dev version of it) seems more complicated. I came across `code --install-extension <ext>` but I am not sure if should go down this route just for this.

Maybe it would be worth writing a little guide how to do so (as a blog post or similar). 
But maybe merging goes quick and all this effort is not really needed (idk how active the repo here is).

Feel free to mark this comment as off-topic :)

**Comment by renkun-ken** [comment]
I create a testing release at https://github.com/renkun-ken/vscode-R/releases. This tracks my latest test branch and is only for testing purpose.

**Comment by pat-s** [comment]
Thanks, this worked. Works quite well!
