### ISSUE TITLE
How to bind shortcut key to run selection?

### ISSUE THREAD

**Issue by red-swan** [Ikuyadeu/vscode-R#18]
I have this in my `keybindings.json`:

```
{
    "key": "alt+enter",
    "command": "r.runSelection",
    "when": "editorLangId = 'r'"
}
```
it doesn't run selections, how do I fix it? If possible, I would request shortcut keys as a feature request

**Comment by Ikuyadeu** [comment]
@red-swan You need more one `=` symbol between `editorLangId` and `r`

**Comment by red-swan** [comment]
Works perfect. Thank you!
