### ISSUE TITLE
Run code using current file name

### ISSUE THREAD

**Issue by andycraig** [Ikuyadeu/vscode-R#183]
`runSource` and `knitRmd` wrap the current file’s path in some R code and send that code to the terminal.

We could generalise this to a function `wrapPath` (or something) that has as parameters the R function name and any additional parameters to pass to that R function. Both `runSource` and `knitRmd` could be refactored to use `wrapPath`.

The key benefit of this is that then users could add their own similar commands in their `settings.json` file, without needing vscode-R itself to be changed.

**Comment by renkun-ken** [comment]
Closed by #237.
