### ISSUE TITLE
Add basic documentation

### ISSUE THREAD

**Issue by statquant** [Ikuyadeu/vscode-R#19]
Hello,
I am trying to give visial studio code + this addin a go but I can't even figure out how to send lines to console.
Is there some documentation I am missing ?

I've see the `R>run` on the main page but there is no description how to get there.
Am I missing something here ?

![screenshot from 2017-08-20 15-46-10](https://user-images.githubusercontent.com/3612473/29495833-15c8978e-85bf-11e7-845c-728e5d34d5d8.png)

**Comment by Ladvien** [comment]
Once you've loaded the extension you can hit F1 to bring up the command menu.  Search for `R: Run Selection / Line`.  Honestly, I've created a shortcut for this command as `CTRL+Enter` / `Command+Enter`, which basically provides the same behavior as RStudio.

When the first line of R is run an R Session is created and you'll have an R console in place of a terminal at the bottom pane in VSCode.

**Comment by Ikuyadeu** [comment]
@statquant Thank you for your issue.
I think it need run button. I'll consider.

**Comment by Ikuyadeu** [comment]
I added `Run Source` icon.
Please use this.
