### ISSUE TITLE
add a way to declare a cell and a command run cell

### ISSUE THREAD

**Issue by StevenLi-DS** [Ikuyadeu/vscode-R#191]
Please considering add a way to declare a cell like `#%%` so that users can run code from cell to cell without selecting multiple lines of code.

example:
https://code.visualstudio.com/docs/python/jupyter-support-py#_jupyter-code-cells
https://nteract.gitbooks.io/hydrogen/

**Comment by andycraig** [comment]
Hi @StevenLi-DS, thank you for the suggestion. Using Ctrl-Enter sends multiple lines of code if they’re linked together by brackets or pipes etc. but being able to declare cells would enable more control over what constitutes a sendable block of code.

I’ll put this as ‘help wanted’.

**Comment by assignUser** [comment]
I would suggest implementing this in a way that makes it compatible with rstudio sections: https://support.rstudio.com/hc/en-us/articles/200484568-Code-Folding-and-Sections
e.g. `# Section ----`
To allwo easier conversion from r to vsc :)

This would also make it possible to add a code navigation feature from rstudio that generates a "table of contents" via the code sections. 
Latex-Workshop does the same in the sidebar:
![image](https://user-images.githubusercontent.com/16141871/90152153-cb56ac80-dd87-11ea-87bc-e8c3ad91b17d.png)
Maybe it is possible to use some of their code?

**Comment by renkun-ken** [comment]
@assignUser 

Code section is already implemented in languageserver by https://github.com/REditorSupport/languageserver/pull/163 and folding by https://github.com/REditorSupport/languageserver/pull/294.

**Comment by renkun-ken** [comment]
Regarding the original request here, I'd suggest that we adopt the Notebook API to have code cells suggested at https://github.com/Ikuyadeu/vscode-R/issues/378 and being implemented at https://github.com/Ikuyadeu/vscode-R/pull/394.

**Comment by assignUser** [comment]
@renkun-ken  Oh that's cool! Sorry for my superflous comment, vsc-r/lsp can do so much I am still learning everyday. Thank you for your work on these projects.

**Comment by renkun-ken** [comment]
With rmarkdown code chunks support implmeneted, this code chunk in R script should be straightforward.

**Comment by ElianHugh** [comment]
If this is something people are still interested in, I have this working by piggybacking on rmarkdown.ts like @renkun-ken suggested:


![HluveJQPU8](https://user-images.githubusercontent.com/60372411/120947678-be001980-c72f-11eb-91c3-4dae45e42c6b.gif)


Still needs a little polishing, but is functioning as expected

**Comment by renkun-ken** [comment]
@ElianHugh Thanks for working on this. I believe it is still quite useful. It would be nice for you to put it into a PR anytime you like.
