### ISSUE TITLE
A hover returns "Loading..." when Shift-JIS characters are used

### ISSUE THREAD

**Issue by takuizum** [Ikuyadeu/vscode-R#194]
Hi! I have started using vscode-r recently! I'm pleased with the features more lighter and faster than Rstudio.

However, I found a small bug while using Japanese characters, so I reported the details.
I found out that a hover (code completion) returns **"Loading..."** when Japanese characters (Shift-JIS) are entered, **although a hover works completely before putting the cursor on S-JIS character.**

Using this code, you could reproduce a bug above.
```
library() # A hover works well
set <- 1234 # A hover works well
set <- "abc" # A hover works well
set # Code completion works well

set <- "あいうえお" # Hovar retruns "Loaging..."
library() # Hovar retruns "Loaging...", too.
```

I confirmed `setting.json` and tried re-installing extensions and relevant package, but the problem was not improved.
I have no idea to fix it (Sorry...😥).

My env is as below.
```
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=Japanese_Japan.932  LC_CTYPE=Japanese_Japan.932
[3] LC_MONETARY=Japanese_Japan.932 LC_NUMERIC=C
[5] LC_TIME=Japanese_Japan.932

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base


loaded via a namespace (and not attached):
[1] compiler_3.6.2
```

 I use vscode-r version 1.2.1 and R-LSP client version 0.1.4.

How can I solve this problem?

(This is my first issue report. I'm sorry if I could not give the necessary information.)

**Comment by renkun-ken** [comment]
Thanks for your reporting on this.

I could reproduce this with the following code on a Windows 10 virtual machine but not on Linux and macOS.

```r
v1 <- "hello"
v2 <- "你好"
v3 <- "あいうえお"
```

This is a [languageserver](https://github.com/REditorSupport/languageserver) issue specific to Windows encoding. I suggest that you transfer this issue there so we can discuss it in more details.

**Comment by takuizum** [comment]
This bug seems to be particular to Windows 10...
( I could not recognize it on my other device (macOS). )

I follow your advice and transfer.
Thanks!

**Comment by takuizum** [comment]
Ohh... How can I transfer this issue to [languageserver issue](https://github.com/REditorSupport/languageserver/issues) ? 

Or should I open a new one on there?

**Comment by renkun-ken** [comment]
Maybe you could just file a new issue there, put a link to this issue and just copy-paste the content.
