### ISSUE TITLE
Ability to choose R interpreter for lintr

### ISSUE THREAD

**Issue by schelhorn** [Ikuyadeu/vscode-R#2]
Nice extension, thank you for making it! I am using the Jupyter R-Kernel as R interpreter in your extension since it has better command completion within the VS Code terminal compared to Rterm. However, this does not work well with lintr. Would it be possible for you to let users specify the R interpreter for linting independently of the one used for the terminal?

**Comment by Ikuyadeu** [comment]
@schelhorn Thank you for using and good idea!
OK, I'll set new setting `r.path` for using lintr and future commands by Sunday.
Please wait for four days.

**Comment by schelhorn** [comment]
Excellent, thank you. While you're at it: could you please also add the functionality to provide parameters to the R interpreter of choice? I'd like to add stuff like `--vanilla` and so forth, and starting the Jupyter R kernel also requires using custom parameters to the commend line call.

**Comment by Ikuyadeu** [comment]
@schelhorn It's good idea too! Setting `r.term.args` will in next.
Thank you and please looking forward to next update!

**Comment by Ikuyadeu** [comment]
@schelhorn I ready settings `r.lintr.executable`(string) and `r.rterm.option`(array).

**Comment by Ikuyadeu** [comment]
@schelhorn  New version support your two request.
Happy coding!
