### ISSUE TITLE
incorporate a code formatter

### ISSUE THREAD

**Issue by StevenLi-DS** [Ikuyadeu/vscode-R#202]
It seems like there is no easy to format R code. Could you guys please consider to incorporating one of the code formatter packages 

![image](https://user-images.githubusercontent.com/33796896/73122430-d7e1f780-3f52-11ea-8a12-d0a277a7d156.png)

**Comment by renkun-ken** [comment]
Do you have [vscode-r-lsp](https://marketplace.visualstudio.com/items?itemName=REditorSupport.r-lsp) and [languageserver](https://github.com/REditorSupport/languageserver) installed? Latest languageserver supports `formatOnSave`, `formatOnPaste`, and simple `formatOnType` already.

**Comment by StevenLi-DS** [comment]
@renkun-ken Thanks buddy. It works well.
