### ISSUE TITLE
Improve R documentation integration

### ISSUE THREAD

**Issue by intiben** [Ikuyadeu/vscode-R#204]
First of all thanks a big thanks to all the contributors of this project. I recently started using vscode-R and it starting to be a very solid alternative to Rstudio, it is also good to see the project getting new features every week 👍.

I would like to submit a couple suggestions to improve the user experience with the R documentation:
* Add a command `r.help` to vscode-R in the spirit of `r.head` so that the selected function name in the editor can be sent to the console with `r help(<selected_text>)`, this would allow users to map shortcuts to it and quickly jump to the help page.
* Add the possibility to copy text from the R documentation in the html viewer in order to be able to paste it into the console or the text editor (e.g. I often do this with examples, function names, argument names, etc.).
* Add a search bar in the html documentation viewer.
* Add a black theme option to the html viewer possibly linked to the editor background color (#178).

Thanks

**Comment by renkun-ken** [comment]
Thanks for your suggestions!

>Add a command r.help to vscode-R in the spirit of r.head so that the selected function name in the editor can be sent to the console with r help(<selected_text>), this would allow users to map shortcuts to it and quickly jump to the help page.

This looks like a special case of #201.

>Add the possibility to copy text from the R documentation in the html viewer in order to be able to paste it into the console or the text editor (e.g. I often do this with examples, function names, argument names, etc.).

This is currently limited by the user operations allowed by WebView. See https://github.com/microsoft/vscode/issues/65452.

>Add a search bar in the html documentation viewer.

I'm not sure if it is possible to do this because the R documentation is purely provided by a http server started from R. The WebView just shows the URL triggerred by `browser`. It does nothing else and it even cannot know it is help documentation.

>Add a black theme option to the html viewer possibly linked to the editor background color (#178).

I'm trying to figure out but I don't know a robust way to do this at the moment.

**Comment by intiben** [comment]
Thanks a lot for your feedback @renkun-ken

**Comment by StepanSushko** [comment]
> I'm trying to figure out but I don't know a robust way to do this at the moment.

Could you add such option in settings of the extensions at least by default switched off, please?

**Comment by pat-s** [comment]
>  The WebView just shows the URL triggerred by browser. It does nothing else and it even cannot know it is help documentation.

It's really funny that on the one hand vscode can do SO MUCH but at the same time fails to provide search within the default HTML previewer 😅

**Comment by renkun-ken** [comment]
Closing as the help pages are supported now.
