### ISSUE TITLE
Code formatter to multiple lines (more then 3 lines) contain Japanese characters fails.

### ISSUE THREAD

**Issue by takuizum** [Ikuyadeu/vscode-R#209]
When I write or open the code contains Japanese characters and more than 3 lines with pipe concatenated, languageserver continues to report errors.

**Steps to reproduce the behavior:**

1. Write ( or open a code written) below lines
```
text <- "vscode is awesome"
text %>% str_replace_all("vscode", "ぶいえすこーど")  %>%
    str_replace_all("is", "は") %>%
    str_replace_all("awesome", "すばらしい")
```

Until line 2, languageserver works well. However, writing more than 3 lines, it continues showing error below.

```
[Error - 15:05:20] Request textDocument/rangeFormatting failed.
  Message: {"message":"missing value where TRUE/FALSE needed","call":{}}

  Code: -32603 
error handling json:  {"message":"lexical error: invalid char in json text.\n          \"縺吶<81><ef>��繧峨<ef>�<a0>縺Ы\")\\r\\n\"}]}}\n                     (right here) ------^\n","call":{}}

error handling json:  {"message":"lexical error: invalid char in json text.\n          \"縺吶<81><ef>��繧峨<ef>�<a0>縺Ы\")\\r\\nd\"}]}}\n                     (right here) ------^\n","call":{}}
```

I also record a screenshot (gif).
![vscode_completion_bug](https://user-images.githubusercontent.com/40698749/73333629-b7e16980-42ad-11ea-8cdf-11b1cd457c69.gif)

Although I tried the next conditions to reproduce this error, 

 - A large (more than 100) number of characters in one line.
 - Multiple lines without pipe

it cannot be observed.

**Environment (please complete the following information):**
 - OS: Windows 10 64 bit
 - VSCode Version 1.41.1
 - R Version3.6.2
 - vscode-r version [latest] (installed from github repository)

**Comment by takuizum** [comment]
Ignoring this error message and continue to write codes, after several minutes, languageserver occasionally stops showing a bug report and works well.

**Comment by renkun-ken** [comment]
Code formatting is done in [languageserver](https://github.com/REditorSupport/languageserver/issues), please raise issue there, so we can discuss it in more details.

**Comment by renkun-ken** [comment]
It is still a Windows encoding issue. Does this still happens if you use https://github.com/REditorSupport/languageserver/pull/165? Looks like `languageserver` and `styler` still have encoding inconsistencies when passing code.

**Comment by takuizum** [comment]
I used languageserver which was installed from github repository ( I wrote that vscode version is github repo, but it was languageserver. Sorry my mistake in writing).

First of all, I open a new issue on languageserver page.

Thanks.

**Comment by renkun-ken** [comment]
Fixed in languageserver. Closing now.
