### ISSUE TITLE
Clarify the source of functionality of vscode-R and languageserver

### ISSUE THREAD

**Issue by renkun-ken** [Ikuyadeu/vscode-R#210]
It looks like it's quite likely that users get confused about the functionality of vscode-R and languageserver, e.g. #194 #202 #207 #209.

Roughly speaking, languageserver provides code analysis features to make it easier to writing R code in any LSP-compliant code editor, while vscode-R provides runtime features specific to VSCode to make it easier to work with R interactively. It seems that we may list such features somewhere so that user could report issues accordingly.

By the way, @Ikuyadeu @andycraig would you like to grant me as collaborator of this repo so that it's easier for me to track issues related to session watcher and transfer issues to languageserver or other related repos when needed?

**Comment by StevenLi-DS** [comment]
I think it's better to just make R and R-LSP a all-in-one extension.

**Comment by renkun-ken** [comment]
@StevenLi-DS  [vscode-R](https://github.com/Ikuyadeu/vscode-R), [vscode-r-lsp](https://github.com/REditorSupport/vscode-r-lsp), and [languageserver](https://github.com/REditorSupport/languageserver) are three different projects. Ikuyadeu.r-pack is merely an extension pack that installs both vscode-R and vscode-r-lsp, but not languageserver (which is not a VSCode extension but an R package).

Most issues are not related to vscode-r-lsp as it is only a thin layer that handles the translation of LSP messages between VSCode and languageserver but related to either vscode-R or languageserver.

**Comment by Ikuyadeu** [comment]
@renkun-ken I invite you as the collaborator.
Some issues can be categorized by adding the [language-server label](https://github.com/Ikuyadeu/vscode-R/labels/language%20server)

To clarify for users and reduce the non-related issues, I think some easy options
* Put the notification on `ISSUE_TEMPLATE/bug_report.md` like the `Please check language server`
* Make the StackOverflow link for talking the small/general issues like [here](https://stackoverflow.com/questions/tagged/visual-studio-code+r).

@renkun-ken @andycraig  How do you think about them?

**Comment by andycraig** [comment]
I think adding something to the bug report template about the language server would be good. It could say something like, ‘Is the issue about autocompletion, hover help, go to definition (etc.)? If so, it is probably an issue with the language server (link)’.

**Comment by renkun-ken** [comment]
@andycraig I agree. Adding a statement to the issue templates should be enough.

Is the issue about auto-completion, hover help, go to definition, document highlight, document outline/symbols, workspace symbols, formatting, document link, document color and color picker? If so it is more likely an issue with the [language server](https://github.com/REditorSupport/languageserver).


I could keep the template updated with the latest languageserver features.

**Comment by andycraig** [comment]
@renkun-ken That would be great! You are definitely the most up-to-date on the language server’s features.
