### ISSUE TITLE
Combining Plots with par()

### ISSUE THREAD

**Issue by ChristopheRoyer21** [Ikuyadeu/vscode-R#212]
**Is your feature request related to a problem? Please describe.**
I often need to compare many plots in one go, but with how the extension is as for now it seems impossible. Everytime a plot is creates, it's overwriting the last one and it's impossible to compare them

**Describe the solution you'd like**
The function par() in R (ie. par(mfrow(a,b)) creates a grid of size a x b and but the next plots together in the grid. As for now, the function does nothing in R Session Watcher, but if it is supported by it, that would make plots comparison much easier.

**Describe alternatives you've considered**
Even if it doesn't really fix the problem, having a plot history instead of a single plot could be nice too.

**Comment by renkun-ken** [comment]
`par(mfrow = c(m, n))` should work in the first place.

What's the result when you run the following code:

```r
par(mfrow = c(1, 2))
plot(rnorm(100), main = "plot 1"))
plot(rnorm(100), main = "plot 2"))
```

Alternatively, #181 added the feature of showing plot history. Please press Ctrl + Shift + P and run vscode command `R: Show Plot History`.

**Comment by ChristopheRoyer21** [comment]
Oh well... Seems like it's working now. I don't know what happens  when I was trying it before. I'm closing this Issue, sorry for wasting your time!
