### ISSUE TITLE
Clean up the project

### ISSUE THREAD

**Issue by Ikuyadeu** [Ikuyadeu/vscode-R#215]
This project needs to be clean up the whole of files for future contributors.

* [x] Rewriting the contribution guide(`CONTRIBUTING.md`)
* [x] Updating tslint to eslint
* [x] Applying GitHub Action for the Pull Request for eslint (solved by #266)
  * https://github.com/marketplace/actions/setup-node-js-for-use-with-actions looks good that have not only eslint function
  * (Next workaround) https://github.com/marketplace/actions/eslint-action that is simple but only eslint function
* [x] Following the eslint
* [x] Redefining eslint rules
* [ ] Minimizing each function and dependency
* [x] (My selfish opinion) Applying the [DevReplay](https://devreplay.github.io/) that is implemented by me.

**Comment by renkun-ken** [comment]
It seems that the default formatting of TypeScript in VSCode is not applied to all `ts` files, so I have to disable auto formatting in this project when I'm editing. It would be nice if the formatting follow certain rules and auto formatting could be applied in a self-contained manner.

**Comment by Ikuyadeu** [comment]
Closed by #474
