### ISSUE TITLE
[Feature request] Support outline for Rmarkdown

### ISSUE THREAD

**Issue by ShixiangWang** [Ikuyadeu/vscode-R#218]
Currently, I cannot see the outline for Rmarkdown files. I don't know how to do this. Is it possible to inherit directly from markdown extension? 

Rmarkdown mode:

![image](https://user-images.githubusercontent.com/25057508/73833887-b08a0500-4845-11ea-8184-21d3bb8933b2.png)

Markdown mode:

![image](https://user-images.githubusercontent.com/25057508/73834110-170f2300-4846-11ea-8cff-323a8ec775aa.png)

**Comment by renkun-ken** [comment]
As I commented at https://github.com/REditorSupport/languageserver/pull/163#issuecomment-576185195, I'll probably implement code section support for Rmd.

**Comment by ShixiangWang** [comment]
@renkun-ken  Thanks :)
