### ISSUE TITLE
cannot preview environment or dataframe

### ISSUE THREAD

**Issue by ddangl** [Ikuyadeu/vscode-R#219]
when I called the R:preview environment or R:preview dataframe
error turns out to be _Cannot read property '0' of undefined_
with excel viewer installed.
OS：Mac os Catalina 10.15.3
![image](https://user-images.githubusercontent.com/33570514/73836727-e382c780-484a-11ea-9c75-edb8a5d6e5a5.png)

**Comment by andycraig** [comment]
@ddangl It looks like the extension may not be activated. Can you save the file as ‘temp.R’, choose ‘Open Folder...’ from the File menu, select the folder containing ‘temp.R’, and try again? Thank you!

**Comment by ddangl** [comment]
> @ddangl It looks like the extension may not be activated. Can you save the file as ‘temp.R’, choose ‘Open Folder...’ from the File menu, select the folder containing ‘temp.R’, and try again? Thank you!

It does works,thank you!

**Comment by andycraig** [comment]
@ddangl Great! :) It sounds like this issue is resolved, so I’ll close it.
