### ISSUE TITLE
Dataframe Preview not Renewing Data

### ISSUE THREAD

**Issue by Ladvien** [Ikuyadeu/vscode-R#22]
It looks like data within the Dataframe Preview command is getting cached somewhere and not renewed.  It doesn't look like it is happening in vscode-R , so I'll need to dig through the source of the Excel Preview extension and find it.

**Comment by Ladvien** [comment]
Well, I cannot seem to replicate the issue.  My Mac is down right now, but it doesn't seem to be caching anything on Windows.  I'll do some Mac specific testing when I get it back up.  

If anyone runs into this issue, please let me know ASAP.

**Comment by Victsz** [comment]
![image](https://user-images.githubusercontent.com/8154646/34399399-208b9392-ebc2-11e7-8ffe-1fd65ecb476f.png)
@Ladvien is this error related to?

**Comment by Ladvien** [comment]
I don't think so.  The error I was encountering I'm pretty sure had to do with the Excel Preview extension caching views.

**Comment by Ikuyadeu** [comment]
Fixed by #150
