### ISSUE TITLE
Line Comment in Rmarkdown

### ISSUE THREAD

**Issue by awellis** [Ikuyadeu/vscode-R#220]
In an Rmd file, outside of code chunks, using the 'Toggle Line Comment' command should add an HTML comment, not a `#`

Commenting out `TEXT` should result in
```
<!-- TEXT -->
```
and not
```
# TEXT
```

**Comment by andycraig** [comment]
@awellis Thank you for your suggestion. I agree, this would be the preferred behaviour.

**Comment by andycraig** [comment]
I think VSCode would do this for us automatically if we handled Rmd as Markdown with R as an embedded language.

**Comment by andycraig** [comment]
Without vscode-R installed, VSCode provides highlighting for R code blocks *without braces around the `r`*:

![highlighting](https://user-images.githubusercontent.com/23294156/73937782-2dda7600-4929-11ea-8a22-ffcddbf5c208.png)

Outside of code chunks, comments are HTML comments as expected. Inside code chunks *without braces*, comments are R/Python comments as expected.

I think the current vscode-R Rmd grammar is providing highlighting for code chunks with braces, but blocking 'built-in' VSCode features like HTML comments outside of code chunks.

**Comment by andycraig** [comment]
As a side note, here are the languages that VSCode provides highlighting for without any extensions installed: https://github.com/Microsoft/vscode/tree/master/extensions

**Comment by andycraig** [comment]
I am reworking the Rmd syntax so that we use VSCode's built-in Markdown grammar, and add to it code chunks with braces and inline R code. This should also fix #36, #48 and #116.
