### ISSUE TITLE
Environment Viewer

### ISSUE THREAD

**Issue by Ikuyadeu** [Ikuyadeu/vscode-R#23]
R Studio environment is very useful.
This extension need this function and output like this #15

**Comment by Ikuyadeu** [comment]
Done
![sep-16-2017 17-38-28](https://user-images.githubusercontent.com/8369346/30510804-130c37f6-9b06-11e7-8077-c5dffda12f79.gif)

**Comment by Ikuyadeu** [comment]
Sorry, this is too small

**Comment by f-leborgne** [comment]
Is there an environment variable viewer in your extension in which we could see all the variables created in R and their values like in R studio ?
![image](https://user-images.githubusercontent.com/32433180/35393579-a5c7a6d4-01e5-11e8-8b65-e91fa18f4fef.png)

**Comment by Ikuyadeu** [comment]
@f-leborgne  Thank you for your using and suggestion.
I opened #47
