### ISSUE TITLE
MacOS cannot get radian to run: "The terminal process terminated with exit code: 2"

### ISSUE THREAD

**Issue by atanasj** [Ikuyadeu/vscode-R#235]
I have the following settings for this extension: 

```
R:Bracketed Paste (marked)
R>Rterm:Mac: /usr/local/bin/radian (path to radian)
```

However, when I try and execute any R code, I get the error `The terminal process terminated with exit code: 2`.

Not sure what I am doing wrong.

Other relevant system info: 

```bash
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G3020
code: 1.42.1
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
radian version: 0.4.6
r executable: /Library/Frameworks/R.framework/Resources/bin/R
r version: 3.6.1
python executable: /usr/local/opt/python/bin/python3.7
python version: 3.7.6
VSCode-R: 1.2.3
```

Please let me know if you need any more info.

**Comment by renkun-ken** [comment]
What Rterm options do you have?

It is known that the default Rterm options does not work with radian. You need to remove Rterm options `--no-restore` to use radian.

**Comment by atanasj** [comment]
Okay, I had to remove all the Rterm options for it to work. I will raise an issue with radian, hopefully the can provide a fix.

**Comment by renkun-ken** [comment]
Fixed at radian side. Closing this.

**Comment by galileukim** [comment]
I now have a similar issue, but the exit code is **exit code: 1**. I'm on MacOS:

The terminal process "/usr/local/bin/radian" terminated with exit code: 1.

**Comment by matthewberryman** [comment]
> I now have a similar issue, but the exit code is **exit code: 1**. I'm on MacOS:
> 
> The terminal process "/usr/local/bin/radian" terminated with exit code: 1.

I had the same error. I have updated the [wiki page](https://github.com/REditorSupport/vscode-R/wiki/Installation:-macOS) with the solution, for reference add the following to vscode user settings:
```json
    "terminal.integrated.env.osx": {
      "R_HOME": "/Library/Frameworks/R.framework/Resources",
      "R_BIN": "/usr/local/bin/R"
    },
```
