### ISSUE TITLE
Session watcher only working in the first attached VScode folder

### ISSUE THREAD

**Issue by intiben** [Ikuyadeu/vscode-R#236]
**Describe the bug**
In a VScode workspace I am only able get the R session watcher working in the first attached folder.

**To Reproduce**
1. Create the following folder structure
![image](https://user-images.githubusercontent.com/56064362/74916316-edb5d180-53c5-11ea-9aec-6e008d664b0b.png)

1. Attach folders in VScode (`File>Add Folder to Workspace...`) to obtain the following: 
![image](https://user-images.githubusercontent.com/56064362/74916020-68322180-53c5-11ea-99df-abae08b0a875.png)

1. In the setup above start an R terminal under `project_1`. The R session ID should be properly shown in the VScode status bar

1. Now do the same but start a new R terminal under `project_2` instead. The VScode status bar will stay with `R: (not attached)`

_Note: if the `project_2` folder were attached first to VScode (i.e. shown first in the side bar list) then the Rsession watcher would work for `project_2` but not for `project_1`_.

`setting.json`
```json
    "r.alwaysUseActiveTerminal": true,
    "r.bracketedPaste": true,
    "r.rterm.mac": "/usr/local/bin/radian"
    "r.sessionWatcher": true
```

**Expected behavior**
R session watcher should be able to work no matter from which folder it has been attached.

**Environment:**
 - OS: macOS
 - VSCode Version: 1.42.1
 - R Version: 3.6.2
 - vscode-R version: 1.2.3

**Additional info**
This could be an extension of #196

**Comment by renkun-ken** [comment]
Thanks for reporting!

Multi-root workspace is not supported yet. We may consider how it should be supported.

**Comment by intiben** [comment]
@renkun-ken thanks for the feedback, I do not know how things work internally but it seems to me that it is almost there i.e. the `.vscode/vscode-R/<session ID>` are properly created it' may "just" be a matter of attaching them to VScode.

**Comment by renkun-ken** [comment]
Multi-root workspace has some complexity that may require everything to be an array, e.g. file watchers, managed terminals, etc.

* Single root workspace, single terminal (the simplest case, works)
* Single root workspace, multiple terminals (works but only tracks last created terminal #200)
* Multi-root workspace, single terminal (only starting R session from first workspace folder works, and session info are shared among all workspaces)
* Multi-root workspace, multiple terminals (multiple `.vscode/vscode-R`, multiple `response.log`)

Do you expect the behavior when you are editing a file from workspace 1, session watcher uses the session data from workspace 1's attached session, and when you are editing a file from workspace 2, session watcher uses the session data from workspace 2's attached session? This allows each workspace has an attached session.

**Comment by intiben** [comment]
In the case I described above (4^th^ item in your list), my expectations would be that the workspaces should be independent from each others.
