### ISSUE TITLE
collaboration of language server

### ISSUE THREAD

**Issue by randy3k** [Ikuyadeu/vscode-R#24]
HI @Ikuyadeu 

I am the author of the [R package](https://github.com/randy3k/R-Box) for Sublime Text. I have recently started a project on [language server](https://github.com/randy3k/languageserver) for R. Nothing is working now, but the basic skeleton is done. My plan is to move R-Box language support based on the language server.

As vscode will be another potential client for the project, so I want to invite you to join the project. Please let me know if you are interested. 

Also, inspired by [JuliaEditorSupport](https://github.com/JuliaEditorSupport), I have an idea to create the organization [REditorSupport](https://github.com/REditorSupport) and move R-Box and languageserver there. Let me know if you are also interested in the organization.

**Comment by Ikuyadeu** [comment]
Very interesting!
I'll send email to your email address on your GitHub account.

**Comment by randy3k** [comment]
`languageserver` is on CRAN now.
