### ISSUE TITLE
Enable Real Time Lintr in Problems Tab

### ISSUE THREAD

**Issue by Kalaschnik** [Ikuyadeu/vscode-R#240]
Until recently I was using [R Tools](https://marketplace.visualstudio.com/items?itemName=Mikhail-Arkhipov.r), which was showing Lintr results pretty much in real time within VS Code’s Problem.

However, when using the current exension the lintr is not working anymore. The entry `"r.lintr.enable": true` is now an unknown configuration setting.

Yet, linting through R using `lintr::lint("test.r")` works fine.

Is there anything else I need to set?

**Comment by renkun-ken** [comment]
Linting is provided by [languageserver](https://github.com/REditorSupport/languageserver#services-implemented) on document open, change and save. Please make sure you have [vscode-r-lsp](https://marketplace.visualstudio.com/items?itemName=REditorSupport.r-lsp), and languageserver installed, and make sure you enabled `r.lsp.diagnostics` in VSCode settings (which is on by default).

**Comment by renkun-ken** [comment]
We may need a major improvement of `README` to make clear the setup of multiple parts vscode-R, vscode-r-lsp, languageserver, and radian on Windows, Linux/macOS so that it is easier for user to have the full experience these parts combined has to offer.

**Comment by Kalaschnik** [comment]
Hey renkun-ken,
thanks for clarification! Indeed updating the doc would greatly benefit new users. I successfully performed the following steps to enable linting:
1. Install R package `install.packages("languageserver")`
2. Install VS Code [R LSP Client](https://marketplace.visualstudio.com/items?itemName=REditorSupport.r-lsp)
3. Add this to (workspace) settings: "r.lsp.path": "C:\\Program Files\\R\\[R VERSION]\\bin\\x64\\R.exe"
4. Restart VS Code
5. Profit

**Comment by renkun-ken** [comment]
Closing now.
