### ISSUE TITLE
Better handling of "#'"

### ISSUE THREAD

**Issue by christiantillich** [Ikuyadeu/vscode-R#242]
I'd like to use vscode's rewrap to reflow long comments either for function documentation or for long comment blocks when using knitr::spin(). Right now, rewrap works as expected when the comment block starts with "#", but not with "#'"

--#  If this is my super long comment line. 

Rewrap will...

--#  If this is my super
--#  long comment line. 

get the spaces right using "#". But 

--#'  If this is my super
--#long comment line

Does not. It makes sense, rewrap sees the ' and thinks text has begun, so I really think the solution here is to modify the comment token. 

I _think_ what I'd like is for language-configuration.json is treat each token as separate

"comments": {
  "lineComment": "#",
  "lineComment": "#'"
},

But that doesn't seem to work as I test it out.

**Comment by andycraig** [comment]
Hi @christiantillich, this is about the Rewrap extension, right? It looks like their comment types are defined here: https://github.com/stkb/Rewrap/blob/aef00b2a9946afff9784b443beb5eaa328cd5e8d/core/Parsing.Documents.fs It seems like they do support for different comment types within one language, such as for C#: https://github.com/stkb/Rewrap/blob/aef00b2a9946afff9784b443beb5eaa328cd5e8d/core/Parsing.Documents.fs#L49 So, it might be that they can add ROxygen comment support too. Could you open an issue there?

The thread for issue #85 also has a similar request.

**Comment by christiantillich** [comment]
Thanks for the quick response. [See here](https://github.com/stkb/Rewrap/issues/181)

**Comment by assignUser** [comment]
Support for `#'` is now in rewrap and https://github.com/stkb/Rewrap/issues/181 was closed. So this issue can probably be closed too 😃

**Comment by andycraig** [comment]
@assignUser Great! Thank you for checking and posting!
