### ISSUE TITLE
How do you open webview in new window automatically?

### ISSUE THREAD

**Issue by atanasj** [Ikuyadeu/vscode-R#243]
Is there a way to open help files via the `webview` functionality in a new window? At the moment, it seems to open in the same window where I executed the code?

Is this possible? If not, could this be a an option?

**Comment by renkun-ken** [comment]
This could certainly be an option. The problem here is that help triggers `browser` so we actually do not know if it is help or a shiny app. It makes sense to show the shinyapp in active editor group while show help on one side. I'll think about it more.
