### ISSUE TITLE
Status of Rmarkdown support

### ISSUE THREAD

**Issue by Hong-Revo** [Ikuyadeu/vscode-R#255]
Apologies if this is already covered elsewhere. What is the current status for supporting Rmd files? This is in terms of both already implemented and on the roadmap.

My current use case is that I'm working on a project that involves R notebooks, and they are rather awkward in VSCode-R. The editor doesn't recognise code chunks in Rmd files, so I end up working with the code in R scripts, and then copying and pasting into the Rmd file. This defeats the purpose of Rmarkdown, where your code and text live side-by-side; it's particularly bad for an R notebook which is meant to be used interactively.

Would be great to see full support for Rmds in this extension!

**Comment by renkun-ken** [comment]
The current support of Rmd is not perfect but should be sufficient for simple use.

Did you choose `R Markdown (rmd)` as the language of the document?

You may set the following settings to associate `*.rmd` with `rmd` language so that the R markdown syntax and language server could be enabled.

```json
"files.associations": {
        "*.rmd": "rmd"
}
```

**Comment by Hong-Revo** [comment]
@renkun-ken I'm not sure what you mean by choosing the language? Isn't this set automatically by the file extension?

**Comment by Hong-Revo** [comment]
Ah, I see it now. I had *.rmd associated with "markdown" in my settings.json. Changing that to "rmd" appears to have fixed it.

**Comment by renkun-ken** [comment]
Closing now. Feel free to reopen if you have further questions.

**Comment by jmorim** [comment]
Is there a built-in snippet for inserting code blocks like
\```{r}
[code]
\```
like RStudio has?

**Comment by hongooi73** [comment]
Interesting. I tried to make a user snippet like this:

```
"```": {
    "prefix": "chunk",
    "body": [
        "```{r}",
        "```"
    ],
    "description": "Insert code chunk"
}
```

In the rmd.json snippet file, but it didn't take. Typing <kbd>\`</kbd><kbd>\`</kbd><kbd>\`</kbd><kbd>Tab</kbd> inside a .Rmd file doesn't insert the snippet. Is there something else that's required?

I do have "*.rmd" associated with "rmd" in my settings.json.

**Comment by jmorim** [comment]
Hmm, mine worked fine in rmd.json

```
	"Insert code block": {
		"prefix": "``",
		"body": ["```{r}", "```\n"],
		"description": "Inserts a code block in an RMD file"
	}
```
