### ISSUE TITLE
[Feature request] RMarkdown: "Run all chunks" & "Run previous"

### ISSUE THREAD

**Issue by pat-s** [Ikuyadeu/vscode-R#262]
RStudio has the nice feature to "Run all chunks" or "Run previous" for RMarkdown documents. This is really handy if you want to have all objects up to a certain chunk to continue from there.

Currently I need to c/p each chunk by hand to the R interpreter to avoid errors when pasting text to the interpreter.

(To run all chunks, [this custom function](https://stackoverflow.com/a/24754637/4185785) can be used as a workaround.)

**Comment by renkun-ken** [comment]
This could be done as extension command that detects the code chunk the cursor is at. And we could also do this using CodeLens like vscode-python:

![image](https://code.visualstudio.com/assets/docs/python/jupyter/code-cells-02.png)

**Comment by andycraig** [comment]
I started working on this in #49 but stopped before producing any useful shareable code. If someone else wants to add this feature that would be very welcome of course!

Using a CodeLens would be a nice approach.

**Comment by assignUser** [comment]
See #358 #395
