### ISSUE TITLE
Suggestion: Add hint for adding arbitrary editor keybindings

### ISSUE THREAD

**Issue by pat-s** [Ikuyadeu/vscode-R#267]
Currently only `r.runCommand` examples are shown in the wiki.

Usually people like to bind operators to a keybinding, e.g. the pipe.
While this is vscode generic, it will probably help users to get started more quickly than searching for this in the web.

Example:

```
        "key": "ctrl+o",
        "command": "type",
        "args": {
          "text": "%>%"
        },
        "when": "editorTextFocus"
       }
```

**Comment by andycraig** [comment]
@pat-s Good idea! I have added a section to the Wiki with shortcuts for `%>%` and `<-`, using the RStudio default keybindings: https://github.com/Ikuyadeu/vscode-R/wiki/Keyboard-shortcuts#suggested-keyboard-shortcuts
