### ISSUE TITLE
`Run line` should load code chunk

### ISSUE THREAD

**Issue by Ikuyadeu** [Ikuyadeu/vscode-R#27]
In #26,  It's very useful function.
> Okay, I found the way to run a line (just like RStudio, its Cmd + Enter, and the run source utility is useful. However, I'm wondering about running just individual code chunks, e.g.
> 
> 
> code_chunk <- function(x) {
>     cat("I am a chunk")
> }
> 
> code_chunk_2 <- x %>%
>   mutate(...) %>%
>   transmute(...)
> 
> If I play my cursor at the beginning of line 1 with the first code_chunk, and enter C-c (aka Ctrl+c, or some other shortcut, say to run a region, like Ctrl+r) then it would run all three lines at once (the whole chunk), and not run code_chunk_2, and if this could be done without necessarily highlighting the chunk prior to running the code.
> 
> Just wondering if you might have some insight on how this could be done, or alternately if this could be implemented in an update?

**Comment by Ladvien** [comment]
I'm starting work on this one.
