### ISSUE TITLE
[Feature request] Running commented examples

### ISSUE THREAD

**Issue by pat-s** [Ikuyadeu/vscode-R#270]
In RStudio one can run examples within the roxygen documentation directly by just highlighting those and hitting `ctrl + enter`.
The comments (`#'`) are automatically stripped.

I have no idea how complicated it would be to implement this but it would be really useful.

**Comment by andycraig** [comment]
Hi @pat-s, this would be a nice feature. There's already an open issue for this, #147, so I'll close in favour of that.
