### ISSUE TITLE
Session Watcher does not show graphs

### ISSUE THREAD

**Issue by gcambray** [Ikuyadeu/vscode-R#272]
**Describe the bug**

After enabling the session watcher I do not get the pane showing the graphs (nor am I getting a quartz windows). I do see a png for the graph stored in the PID folder within the .vscode/vscod-R folder though. So the problem seem to stem from the pane not opening.
I tried installing radian to see if that would help and got a separate issue, which I'll report in another thread.

**Do you want to fix by self? (I hope your help!)**

Yes

**(If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)**

Maybe some guidance as to what I could try to fix...

(If related)setting.json

   "r.sessionWatcher": true,
    "r.bracketedPaste": true,
    "r.rterm.option": [],
    "r.alwaysUseActiveTerminal": true,
    "r.lsp.path": "/usr/local/bin/R"

**Expected behavior**
Some guidance to fix that issue!
**Environment (please complete the following information):**
 - OS: [e.g. Windows, macOS, Linux]
OSX mojave 10.14.6

 - VSCode Version: [e.g. 1.42.0]
1.43.2

 - R Version: [e.g. 3.6.2]
3.6.1 (2019-07-05) -- "Action of the Toes"
Installed from CRAN distribution

 - vscode-R version: [e.g. 1.2.2]
1.2.7

Many thanks for your help

**Comment by renkun-ken** [comment]
Would you like to post the output of the following:

```r
ls.str(getOption("vscodeR"))
```

and the workspace root of your VSCode?

**Comment by gcambray** [comment]
Thanks for the very quick response time!

` ls.str(getOption("vscodeR"))
attach : function ()  
dataview : function (x, title)  
dataview_data_type : function (x)  
dataview_table : function (data)  
dir :  chr "/Users/gcambray/Dropbox/Documents/WorkStuff/Info/R/.vscode/vscode-R"
dir_plot_history :  chr "/var/folders/cp/392gr6y940n3xbr39449d1cw0000gn/T//RtmpKEGnLQ/images"
dir_session :  chr "/Users/gcambray/Dropbox/Documents/WorkStuff/Info/R/.vscode/vscode-R/4089"
globalenv_file :  chr "/Users/gcambray/Dropbox/Documents/WorkStuff/Info/R/.vscode/vscode-R/4089/globalenv.json"
new_plot : function ()  
pid :  int 4089
platform : List of 8
 $ OS.type   : chr "unix"
 $ file.sep  : chr "/"
 $ dynlib.ext: chr ".so"
 $ GUI       : chr "vscode"
 $ endian    : chr "little"
 $ pkgType   : chr "mac.binary.el-capitan"
 $ path.sep  : chr ":"
 $ r_arch    : chr ""
plot_file :  chr "/Users/gcambray/Dropbox/Documents/WorkStuff/Info/R/.vscode/vscode-R/4089/plot.png"
plot_history_file :  NULL
plot_updated :  logi FALSE
rebind : function (sym, value, ns)  
respond : function (command, ...)  
response_file :  chr "/Users/gcambray/Dropbox/Documents/WorkStuff/Info/R/.vscode/vscode-R/response.log"
tempdir :  chr "/var/folders/cp/392gr6y940n3xbr39449d1cw0000gn/T//RtmpKEGnLQ"
unbox : function (x)  
update : function (...)`

as for the workspace root, I guess this is what you are asking for:
`{
	"folders": [
		{
			"path": "."
		},
		{
			"path": "/Users/gcambray/Dropbox/Documents/WorkStuff/Info/R"
		}
	],
	"settings": {
		"editor.formatOnSave": true,
		"editor.formatOnPaste": true,
		"files.autoSave": "afterDelay",
		"r.sessionWatcher": true,
		"r.alwaysUseActiveTerminal": true,
		"r.bracketedPaste": true
	}
}`

**Comment by renkun-ken** [comment]
This is very likely to be similar with #179 where cloud-based filesystem does not support FileSystemWatcher to monitor file changes so that R session watcher does not work either.

You may try opening a standard folder and see if it works.

**Comment by gcambray** [comment]
Most of my filesystem is on dropbox but with an actual local version. After trying your suggestion, I realized that the issue was actually caused by another folder in my workspace populated with python scripts. Turns out just duplicating the workspace in place and deleting that other folder fix the behavior. I guess there was  some sort of conflicts with python rules for that workspace.
Please let me know if I can be of any help figuring ou exactly what was the problem.
Thanks for your help!
