### ISSUE TITLE
radian does no get proper env variable and cannot launch

### ISSUE THREAD

**Issue by gcambray** [Ikuyadeu/vscode-R#273]
**Describe the bug**
I installed radian as suggested on the wiki. 
When I create a new R terminal I get an error (shown in screenshot below). 
I traced this down on the radian source code to an issue with radian getting a path to the R library (Rhome function). I added the R_HOME value to my environment variable to try to solve this, but it still does not work. (R_Home is the path returned by executing R RHOME).
Radian works fine when launched from terminal, so I am assuming the problem is coming from it being launch from within the vscode-R extension, though it is unclear to me how environment variables could be affected...

**Do you want to fix by self? (I hope your help!)**

Yes

**(If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)**

I have tried pretty much all I could think of, so any idea would be appreciated.

(If related)setting.json

```    "r.sessionWatcher": true,
    "r.bracketedPaste": true,
    "r.rterm.option": [],
    "r.alwaysUseActiveTerminal": true,
    "r.lsp.path": "/usr/local/bin/R",
    "r.rterm.mac": "/Users/gcambray/anaconda3/bin/radian"
```
**Screenshots**
<img width="643" alt="image" src="https://user-images.githubusercontent.com/54418151/77926176-1757f780-72a6-11ea-9dc7-8f9d8c28d7ac.png">

**Environment (please complete the following information):**
 - OS: [e.g. Windows, macOS, Linux]
OSX Mojave 10.14.6

 - VSCode Version: [e.g. 1.42.0]
1.43.2

 - R Version: [e.g. 3.6.2]
3.6.1 (2019-07-05) -- "Action of the Toes"

 - vscode-R version: [e.g. 1.2.2]
1.2.7

- radian
0.4.8

Many thanks

**Comment by renkun-ken** [comment]
@randy3k Is there anything user should do when starting radian with the python from anaconda on macOS?

**Comment by randy3k** [comment]
I don’t think it is related to anaconda but rather the path to R is not exposed to VSCode terminal.

I vaguely remember that there is an option to import all users environmental variables in VSCode.

**Comment by renkun-ken** [comment]
@gcambray Would you check the following VSCode settings:

```
"terminal.integrated.inheritEnv": true
```

as suggested in https://github.com/randy3k/radian/issues/170?

**Comment by gcambray** [comment]
This was set to true but only in my workspace settings. Setting it to true in my User settings did the trick.
Working now!
Thanks and best regards
