### ISSUE TITLE
rprofile.site not respected

### ISSUE THREAD

**Issue by leeleavitt** [Ikuyadeu/vscode-R#276]
When opening up an R terminal the settings specified in the `Rprofile.site` is not respected. For example i specify `.libpaths()`, in my `Rprofile.site`, but now when i call on `.libpaths()` the newly specified library path is no longer there.

**Comment by renkun-ken** [comment]
If you create R terminal via command `R: Create R Terminal`, it sets `R_PROFILE_USER` to a vscode-R provided `.Rprofile` to initialize session watcher and `Rprofile.site` is ignored in this case. I'll think about how we could better handle this.

A walk around at the moment is to edit `~/.Renviron` and add the following (for example):

```
R_LIBS_USER=~/R/your_library
```

as suggested at https://github.com/REditorSupport/vscode-r-lsp/issues/34#issuecomment-612401176.

**Comment by renkun-ken** [comment]
The problem is caused by the default config:

```json
"r.rterm.option": [
        "--no-save",
        "--no-restore",
        "--no-site-file"
    ]
```

You should remove `--no-site-file` and reload vscode and the R terminal you create should automatically source your `Rprofile.site` first.

**Comment by renkun-ken** [comment]
@Ikuyadeu @andycraig Do you think we should remove `--no-site-file` from the default `r.rterm.option`? User started R session has no `--no-site-file` by default to respect system profile.

**Comment by leeleavitt** [comment]
I'm fine either way, I am trying to get more users in my lab to switch to vscode instead of notepad++. I automatically load their softwares with the rgui. This is the reason why this option was attractive to me.

**Comment by andycraig** [comment]
I would be happy with removing `—no-site-file` from the default.
