### ISSUE TITLE
Recognize and honor .lintr file

### ISSUE THREAD

**Issue by hafen** [Ikuyadeu/vscode-R#28]
For folders that use a .lintr file, it would be nice is this extension would honor those settings.

**Comment by Ikuyadeu** [comment]
@hafen I didn't know that, and I'll try.
Thank you for your good information!

**Comment by hafen** [comment]
👍 Thanks for looking into it and making this extension.

**Comment by Ikuyadeu** [comment]
@hafen , new this extension 0.5.0 supported folder's lintr by settings `r.lintr.isPackages` to `true`.
However, supporting `.lintr` is still on TODO yet. 
Please use setting `r.lintr.linter` until support.

**Comment by steveped** [comment]
I currently have this issue on Ubuntu 18.04 using `lintr 2.0.1` and R4.0.3. On a separate Windows machine with an WSL installation running Ubuntu 20.04 and R4.1.x the situation is identical.

```
cat ~/.vscode/extensions/ikuyadeu.r-2.0.0/R/.lintr 
linters: with_defaults(
  line_length_linter(120),
  cyclocomp_linter = NULL,
  object_name_linter = NULL,
  object_usage_linter = NULL)
```

I'm getting problems detected such as:

Lines should not be more than 80 characters
Variable and function name style should be snake_case

Changing the values in the `.lintr` file makes no difference. Linting manually using lintr::lint("path/to/file") behaves as expected.

**Comment by renkun-ken** [comment]
@steveped You should edit `~/.lintr`.
