### ISSUE TITLE
Commenting doesn't work in R Markdown chunks for Python etc.

### ISSUE THREAD

**Issue by andycraig** [Ikuyadeu/vscode-R#281]
Commenting works nicely in 

* YAML frontmatter, markdown content
* Rmd R code chunk (\`\`\`{r})
* Rmd C++ code chunk (\`\`\`{cpp})
* Markdown R code chunk (\`\`\`r)
* Markdown C++ code chunk (\`\`\`cpp)

but does not work with python code chunks (treating it like markdown content)

* Rmd Python code chunk (\`\`\`{python})

_Originally posted by @renkun-ken in https://github.com/Ikuyadeu/vscode-R/pull/269#issuecomment-605624580_

Each language we want to support in Rmd code chunks will need to be added to `syntax/Markdown Redcarpet.tmLanguage`.

**Comment by kar9222** [comment]
@andycraig I think it's included in https://github.com/Ikuyadeu/vscode-R/pull/460 if that's what you meant.

![1](https://user-images.githubusercontent.com/54139483/100718462-7a8ac280-340f-11eb-8501-0bde254a59a1.png)

**Comment by andycraig** [comment]
@kar9222 I tested it and it works. Thank you!
