### ISSUE TITLE
Windows R terminal doesn't respect up and down arrows

### ISSUE THREAD

**Issue by leeleavitt** [Ikuyadeu/vscode-R#283]
Using R in Linux I am able to use the R terminal in the same ways that i can use the Rgui. For example;

When working in the terminal in windows, I cannot use the up key to go back to previously entered commands. Additionally the terminal doesn't respect the home or end key. This make troubleshooting and playing around fairly difficult.

Also, is there any hope for colorful terminal text? I miss having the input as Red, and the output as blue.

**Comment by renkun-ken** [comment]
You might want [radian](https://github.com/randy3k/radian) instead. Please see https://github.com/Ikuyadeu/vscode-R/wiki/Installation:-Linux#4-radian about the installation.

**Comment by andycraig** [comment]
@leeleavitt I have the same problem using the R terminal in Windows. This is a limitation of the R console itself and so there's not much we can do about it. I strongly second @renkun-ken's recommendation of [radian](https://github.com/randy3k/radian).

**Comment by leeleavitt** [comment]
@andycraig Thanks for the reccomendation! How do use specify vs code to use Radian for R?

**Comment by andycraig** [comment]
@leeleavitt Here are some instructions on how to set up radian with VS Code: https://github.com/Ikuyadeu/vscode-R/wiki/Installation:-Windows#4-radian (by @renkun-ken).

**Comment by andycraig** [comment]
I am going to close this issue as the Windows R terminal is outside our control.

@leeleavitt If you have trouble with the radian setup, feel free to continue to post to this issue and we'll try to help.

**Comment by leeleavitt** [comment]
Thanks for the suggestion to use Radian. It is very nice. The install was a bit complicated with using conda, but overall it went smoothly

**Comment by andycraig** [comment]
@leeleavitt Good to hear!

**Comment by gwd666** [comment]
In case someone else runs into this issue and stumbles upon this ticket ....    
I have the strong feeling that this is ConPTY (some, not sure which  versions) related ... 
I could work around this issue (ie make arrow keys cycle through R commands history again) by UN-ticking in 
Settings -> Terminal > Integrated: Windows Enable Conpty 
![image](https://user-images.githubusercontent.com/57595487/111202544-443f1080-85c4-11eb-9d1b-56ebb9428084.png)
