### ISSUE TITLE
vscode-R considers a period "."  in an object name / call to indicate a separate word

### ISSUE THREAD

**Issue by alexcoulton** [Ikuyadeu/vscode-R#286]
**Describe the bug**
When editing R scripts in VSCode using vscode-R, object calls or definitions that are internally separated by a . are considered to be separate words, and so cannot be highlighted at once. For Python, this is the correct functionality, but this is not the case for R, in which . does not represent a language feature and can be freely used in variable names. Indeed RStudio, Sublime 3 and Nvim-R all function correctly in this regard.

**To Reproduce**
Write a variable, e.g.:
name.last <- "Smith"

Place the cursor at the start of the variable, then press Ctrl + Shift + Right. Only the first portion of the variable will be highlighted. 

**Do you want to fix by self? (I hope your help!)**

I'm not sure how to fix this, but I imagine it relates to the definition of a word object in language-configuration.json (https://code.visualstudio.com/api/language-extensions/language-configuration-guide). Any help would be greatly appreciated. 

**Environment (please complete the following information):**
 - OS: Windows 10
 - VSCode Version: 1.44.2
 - R Version: 3.5.1
 - vscode-R version: 1.2.8

**Comment by andycraig** [comment]
@alexcoulton Thank you for reporting!

I think the problem might be the dot in this line: https://github.com/Ikuyadeu/vscode-R/blob/ef3c8bdd103e4228b539b291bee6169dc914c44a/src/extension.ts#L16

**Comment by andycraig** [comment]
Bad news. From the VS Code docs https://code.visualstudio.com/api/language-extensions/language-configuration-guide#word-pattern

> wordPattern defines what's considered as a word in the programming language. Code suggestion features will use this setting to determine word boundaries if wordPattern is set. Note this setting won't affect word-related editor commands, which are controlled by the editor setting editor.wordSeparators.

After removing '.' from `editor.wordSeparators`, the `name.last <- "Smith"` example works as expected.

So, I don't think this is something we can set specifically for R files. It looks like the user has to choose '.' as a word separator for either all or no files.

**Comment by alexcoulton** [comment]
Hi Andy,

I thought there might be a fix that could be implemented into the extension that I didn't know about, but for now I fixed it locally by adding the following to my settings.json:

    "[r]": {

    "editor.wordSeparators": "`~!@#%$^&*()-=+[{]}\\|;:'\",<>/?"
    }

Also see: https://github.com/microsoft/vscode/issues/33701

**Comment by andycraig** [comment]
@alexcoulton Thanks for the workaround and the link! I upvoted.

**Comment by andycraig** [comment]
I don't think there is anything we can do about this so I'm going to close this issue. But, I have added @alexcoulton's workaround to the Wiki: https://github.com/Ikuyadeu/vscode-R/wiki/Recommended-extensions-and-configuration#dots-in-variablefunction-names Thank you @alexcoulton!

**Comment by renkun-ken** [comment]
@andycraig Thanks for updating useful information in the wiki!
