### ISSUE TITLE
Keyboard shortcut for "run from line 1 to cursor line"

### ISSUE THREAD

**Issue by michaeldorman** [Ikuyadeu/vscode-R#288]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to be able to use the shortcut **Ctrl+Alt+B** to send the code from line 1 to the line where the cursor is, to the console/terminal. The cursor position should remain unchanged. (The latter shortcut exists in RStudio.)

**Describe alternatives you've considered**
The alternative is to select the code manually using **Shift+PageUp** followed by **Ctrl+Enter** to send the selection. This is inconvenient because then I need to go back and find the line where I was using **PageDown** and arrow keys.

**Additional context**
For example, if in the attached screenshot the cursor is on line 8 column 22, then after pressing **Ctrl+Alt+B** I would like to see lines 1-8 inclusive executed, while the cursor remains on line 8 column 22.

Thanks you very much for any help & thanks for building this excellent extension!

![Screenshot from 2020-04-22 16-11-53](https://user-images.githubusercontent.com/9386655/79986197-5a2b7a80-84b4-11ea-98a4-22f9e6f72584.png)

**Comment by andycraig** [comment]
@michaeldorman Thanks for creating! I will work on this.

**Comment by michaeldorman** [comment]
@andycraig Thank you!
