### ISSUE TITLE
winkey + enter not executing .R file line that cursor is currently on in editor

### ISSUE THREAD

**Issue by myusrn** [Ikuyadeu/vscode-R#29]
I'm running win10 fall creators update [ 1709 / 16299.15 ] + visual studio code 1.17.1 [ sep17 ] + R language extension [ 0.4.7 ].   My user settings [ %appdata%\Code\User\settings.json ] contains entry [ "r.rterm.windows": "C:\\Program Files\\Microsoft\\R Client\\R_SERVER\\bin\\x64\\R.exe", ] to denote use of default vs17 [ 15.4.0 / 27004.2002 ] provided Microsoft R client. 

With vscode open against folder containing my *.R [ and some *.Rmd, *.csv, *.md, etc ] files and one of the *.R files open with cursor sitting on a line with simple R language variable assignment i press winkey + enter to execute that line and nothing happens.  If i try F1 | >R: Run Selection/Line it attempts to open a new R Terminal window, vs using the one i opened using F1 | >R: Create R terminal which does process interactively entered valid R language syntax.

**Comment by Ikuyadeu** [comment]
@myusrn Thank you for issue!
I missed key map.
Now, I updated and you can use this command by `Ctrl` + `Enter`.

**Comment by myusrn** [comment]
Thanks for followup. I installed the 0.48.0 update and now using rstudio aligned ctrl+enter keyboard shortcut while sitting on a *.R source file line of code it does use existing R terminal, or launch new one if none existed, to execute that line of code.

For whatever reason the first R terminal that attempts to be created looks like it hangs and fails to ever initialize for me. This is the case whether its launched using ctrl+enter or f1 | R: Create R terminal option. I get the same result using both the R 3.4.1 client install and the vs17 data science workload installed Microsoft R Client 3.3.2 in settings. The workaround i stumbled on is i open settings [ %appdata%\Code\User\settings.json ] and comment out the "r.rterm.windows" property setting then use ctrl+s to save changes.  At that point the R terminal completes opening using the value i had configured for "r.term.windows" before commenting it out.  This may suggest that on first load of this R language support extension is perhaps trying to use a default R.exe location [ "C:\\Program Files\\R\\R-3.3.2\\bin\\x64\\R.exe" ] and only changing to a settings.json defined alternative [ "r.rterm.windows": "C:\\Program Files\\R\\R-3.4.1\\bin\\x64\\R.exe", OR "r.rterm.windows": "C:\\Program Files\\Microsoft\\R Client\\R_SERVER\\bin\\x64\\R.exe", ] when a settings.json change notification for that property it cares about is raised with the extension.

Note that this workaround doesn't work in the other direction, i.e. if i open vscode with "r.term.windows" property commented out and then uncomment it and ctrl+s to save settings.json change it doesn't resolve the issue with successfully opening R terminal.  So i have to open vscode with the relevant "r.term.windows" property setting uncommented and then comment it out for the R terminal session to successfully open.

**Comment by Ikuyadeu** [comment]
@myusrn  Sorry, my English skill is not well.
What should I do?

**Comment by myusrn** [comment]
In my case it appears that extension doesn't read and apply the r.rterm.windows" property setting when it initializes. It does appear to put it in effect when i the comment out that property in settings.json and save it. A repro would require operating extension on a system without the default R 3.3.2 client installed [ "C:\Program Files\R\R-3.3.2\bin\x64\R.exe" ] and instead just the R 3.4.1 or msft R client installed as this would require the r.rterm.windows property setting to be used when extension initializes.  

If this doesn't repro on your setup or others then i must have a dev wks specific issue going on.

**Comment by pnd-abriki** [comment]
Hello,

I'm not sure if this bug is fixed or not.
Using winkey+enter doesn't seem to work, and ctrl+shift+b runs the entire script.
Is there a way to run only the line where the cursor is ?

Thank you

**Comment by myusrn** [comment]
The keyboard shortcut for execution of line cursor is currently sitting on was set to "ctrl+enter" in the update that fixed this issue so it aligns with keyboard shortcut for doing the same in rstudio and rgui ide environments.

**Comment by pnd-abriki** [comment]
Hi myusrn,

Even ctrl+enter shortcut is not working!
Any thoughts of what could be the reason of such behavior ?
I'm using VS code v1.17.2 and R extension v0.4.8 on Windows 10 x64 machine.

Thanks

**Comment by myusrn** [comment]
I'm running same version of vscode, r extension and windows as you.  Not sure why you getting that unexpected result. Assume the source file in which you are trying to execute line of R code using ctrl+enter is saved with the .R extension. If so might suggest trying an extension uninstall and reinstall to see if that resolves and otherwise would defer to @Ikuyadeu for his thoughts.

**Comment by Ladvien** [comment]
I'm almost done with issue #27.  Then I'll start on this one.

**Comment by Ladvien** [comment]
@myusrn this does appear related to having a non-typical (loosely speaking) R install.  For me, I use the Microsoft R.  What I'm seeing is if I create a fresh install of vscode-R, while using a non-typical R install, then when I hit ctrl + enter the RTerm never initializes.

My proposed fix is to give the user feedback if the R client cannot be found.  

"The R client cannot be found.  Please check the R path in preferences."

This isn't too far off from RStudio.  On Windows machines they allow one to select the R client.  On Mac, they don't provide the choice, as Mac has been standardized to x64.

**Comment by Ladvien** [comment]
I've finished the R path warning.  It displays the a message rather than hanging if the R client cannot be found.  

I'll open a PR after Ikuyadeu reviews my PR to add execute block.

**Comment by myusrn** [comment]
@Ladvien thanks for following up on the related matter nested in this thread. 

My expectation was that having the user settings [ %appdata%\Code\User\settings.json ] entry "r.rterm.windows": "C:\Program Files\R\R-3.4.1\bin\x64\R.exe", OR "r.rterm.windows": "C:\Program Files\Microsoft\R Client\R_SERVER\bin\x64\R.exe", should tell the R extension where the R client install exists in cases where it is not whatever is considered to be the typical path, e.g. 3.3.2 x64 "C:\Program Files\R\R-3.3.2\bin\x64\R.exe" or x86 "C:\Program Files\R\R-3.3.2\bin\R.exe".   

In my notes above that settings entry worked for me but not on the first pass, i.e. i had to comment the entry out and then uncomment again, for the setting to take. I just tested again yesterday and this morning and i'm no longer having that issue.  The vscode 1.17.2 and R extension v0.4.8 releases on my w10x64 1709/16299.15 environment are now doing what i'd expect on initial load and finding the users settings [ %appdata%\Code\User\settings.json ] entry "r.rterm.windows": "C:\Program Files\Microsoft\R Client\R_SERVER\bin\x64\R.exe", specified client install right away.  Not sure what changed with my wks or vscode or r extension setup to get it to start working as expected.

I like your idea of throwing a message stating that R extension cannot find typical R client or user settings r.term.windows specified installed vs looking like it hangs when attempting to launch the R terminal window.

**Comment by jwvjwvjwv** [comment]
The ctrl+enter shortcut still does not work (on Windows, anyway). Even if I reassign the shortcut in VS Code to something else, _that_ shortcut doesn't work. The only thing that works is selecting the code chunk I want to run, opening the command palette (ctrl+shift+p), and finding and selecting "R: Run Selection/Line".

**Comment by myusrn** [comment]
@jwvjwvjwv perhaps try uninstalling the vscode R extension and reinstalling it to see if that gets the keyboard mapping working. In my setup the ctrl+enter execution of .R script cursor is currently sitting on is still working.

**Comment by Ikuyadeu** [comment]
Thank you @jwvjwvjwv and @myusrn  for information.
I'll add extension work CI  test on windows as soon as possible.

**Comment by andycraig** [comment]
I think all the problems described here were resolved, except perhaps @aybbr and @jwvjwvjwv’s (now showing as a ghost) issues. I’m going to close this.

@aybbr This is an old issue and hopefully you’re not experiencing this problem any more, but if you are please reply and I’ll see if we can help you further.
