### ISSUE TITLE
Extension deploy the configuration files with every new session

### ISSUE THREAD

**Issue by kguidonimartins** [Ikuyadeu/vscode-R#292]
I'm trying to maintain the `~/.vscode-R/init.R` and `~/.vscode-R/.Rprofile` in my dotfiles folder, which is based on symlinks. However, every new session in VSCode, the extension rewrites these files. Is that an expected behavior? There is a way to change this?

**Comment by renkun-ken** [comment]
Yes, it is an intended behavior at the moment since the vscode-R uses this folder to ensure that the scripts are the latest so that session watcher could work correctly. The folder is not intended for user to maintain and modify at the moment.

**Comment by kguidonimartins** [comment]
Thanks for the quick response. I'm trying to understand how the extension works by commenting on the configuration files. I would like the extension to access my R snippets. Apparently I should keep a copy of these files, though.

I'm closing this issue.

**Comment by renkun-ken** [comment]
Please notice that the scripts in `~/.vscode-R` is only useful for the session watcher feature to inject the functions to each R interactive session so that it could communicate with session watcher on vscode-R side.
