### ISSUE TITLE
R session watcher does not work

### ISSUE THREAD

**Issue by fdq09eca** [Ikuyadeu/vscode-R#297]
I tried the following code with the session watcher open
```r
library(tidyverse)
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy))

```
but it does not prompt anything.

![image](https://user-images.githubusercontent.com/51902242/80771464-2ae8cd80-8b86-11ea-9839-3c26fef4ddb9.png)
![image](https://user-images.githubusercontent.com/51902242/80772910-d4ca5900-8b8a-11ea-9a0a-40feddd62c24.png)

I read about #179.. but it seems not my problem

here is some more information might be useful.
```bash
> ls.str(getOption("vscodeR"))
attach : function ()  
dataview : function (x, title)  
dataview_data_type : function (x)  
dataview_table : function (data)  
dir :  chr "/Users/macone/Documents/learn-R/.vscode/vscode-R"
dir_plot_history :  chr "/var/folders/0v/_qjsr_1j6yv2z49b9r94grp40000gn/T//RtmpFyr0GP/images"
dir_session :  chr "/Users/macone/Documents/learn-R/.vscode/vscode-R/20992"
globalenv_file :  chr "/Users/macone/Documents/learn-R/.vscode/vscode-R/20992/globalenv.json"
new_plot : function ()  
pid :  int 20992
platform : List of 8
 $ OS.type   : chr "unix"
 $ file.sep  : chr "/"
 $ dynlib.ext: chr ".so"
 $ GUI       : chr "vscode"
 $ endian    : chr "little"
 $ pkgType   : chr "mac.binary"
 $ path.sep  : chr ":"
 $ r_arch    : chr ""
plot_file :  chr "/Users/macone/Documents/learn-R/.vscode/vscode-R/20992/plot.png"
plot_history_file :  NULL
plot_updated :  logi FALSE
rebind : function (sym, value, ns)  
respond : function (command, ...)  
response_file :  chr "/Users/macone/Documents/learn-R/.vscode/vscode-R/response.log"
tempdir :  chr "/var/folders/0v/_qjsr_1j6yv2z49b9r94grp40000gn/T//RtmpFyr0GP"
unbox : function (x)  
update : function (...)
```

```bash
> Sys.getenv("R_USER")
[1] ""
```

```bash
> getwd()
[1] "/Users/macone/Documents/learn-R"
```
Thank you

**Comment by renkun-ken** [comment]
Thanks for reporting.

Looks like you do not open folder `/Users/macone/Documents/learn-R` as your workspaceRoot in VSCode. Are you using multi-root workspace? It is not currently supported yet (#236).

Please open the folder directory and retry.

**Comment by fdq09eca** [comment]
![image](https://user-images.githubusercontent.com/51902242/80775019-1231e500-8b91-11ea-9370-adae45b5ff63.png)
it is attached now, but it still does not prompt anything

**Comment by renkun-ken** [comment]
Looks like source a file will not print the ggplot object.  You may try the same in plain R terminal outside vscode I guess the behavior is the same.

**Comment by fdq09eca** [comment]
> Looks like source a file will not print the ggplot object. You may try the same in plain R terminal outside vscode I guess the behavior is the same.

It doesn't make sense to me.. so how to have dynamic plotting if I can only run it in the Terminal?

**Comment by renkun-ken** [comment]
The plot is printed because in an interactive session when you input an expression, the result will be printed, and ggplot2 graphics is only created when you print the result.

If you need the produce the plot in source, you may need the following:

‘’’r
plot <- ggplot(...)
print(plot)
‘’’

**Comment by fdq09eca** [comment]
ah! blimey. sorry for the stupid question, it works perfectly!
![image](https://user-images.githubusercontent.com/51902242/80780182-9a6bb680-8ba0-11ea-8eac-a2455d7810c7.png)

**Comment by fdq09eca** [comment]
> The plot is printed because in an interactive session when you input an expression, the result will be printed, and ggplot2 graphics is only created when you print the result.
> 
> If you need the produce the plot in source, you may need the following:
> 
> ```r
> plot <- ggplot(...)
> print(plot)
> ```

ah.. blimy 

> The plot is printed because in an interactive session when you input an expression, the result will be printed, and ggplot2 graphics is only created when you print the result.
> 
> If you need the produce the plot in source, you may need the following:
> 
> ```r
> plot <- ggplot(...)
> print(plot)
> ```

for whom may interest, hit `cmd+enter` can have this result as well
