### ISSUE TITLE
Icon for .Rmd files

### ISSUE THREAD

**Issue by andycraig** [Ikuyadeu/vscode-R#298]
how do I have the icon of `.rmd` in vscode? now it appears as the unknown file type.

![image](https://user-images.githubusercontent.com/51902242/80768186-451dae00-8b7c-11ea-829c-ad4afbb0944c.png)

_Originally posted by @fdq09eca in https://github.com/Ikuyadeu/vscode-R/issues/295#issuecomment-622164109_

**Comment by Ikuyadeu** [comment]
I submitted the PR to the original seti icon project that is referred by vscode.

**Comment by andycraig** [comment]
@Ikuyadeu That was quick, thank you!

**Comment by Ikuyadeu** [comment]
OK, the PR is merged. Maybe, the new feature will be enabled from the next vscode update.

**Comment by andycraig** [comment]
![icon](https://user-images.githubusercontent.com/23294156/81462420-450d5600-91ed-11ea-954d-4798c0719034.png)

Confirmed that .Rmd files have a proper icon in VS Code 1.45.0. Thanks @fdq09eca and @Ikuyadeu!
