### ISSUE TITLE
Have setting changes apply immediately

### ISSUE THREAD

**Issue by andycraig** [Ikuyadeu/vscode-R#299]
When changing settings like `r.bracketedPaste`, a reload is necessary for the new setting to take effect. I'm sure I've seen other extensions for which setting changes apply immediately.

**Comment by renkun-ken** [comment]
It seems that we need to implement `onDidChangeConfiguration: Event<ConfigurationChangeEvent>` to make settings effective immediately according to https://code.visualstudio.com/api/references/vscode-api#workspace.

**Comment by andycraig** [comment]
@renkun-ken Thank you for checking!

I'm having a try at this at the moment. I started with `onDidChangeConfiguration` but it looks like we can access the current values by using

```
workspace.getConfiguration('r').get<boolean>('alwaysUseActiveTerminal')
```

instead of

```
config.get<boolean>('alwaysUseActiveTerminal')
```

I'm going to do a PR for this.
