### ISSUE TITLE
Linting does not work on Windows 10

### ISSUE THREAD

**Issue by schelhorn** [Ikuyadeu/vscode-R#3]
When running `lintr` under Windows 10 with latest VS Code and R extension, the linting does not work on my system since the line (in your `extension.js`)
 
```javascript
    cp.execFile(RPath, parameters, (error, stdout, stderr) => {
```
 
does produce an empty `stdout`. The R command built by this line itself works when run externally, and produces linting messages to `stdout`. However, when I change the line to
 
```javascript
        cp.exec(RPath + " " + parameters.join(" "), (error, stdout, stderr) => {
```
 
then linting works just fine in the R extension. Would it be possible to change the line accordingly?

**Comment by Ikuyadeu** [comment]
Great! Changing line is possible.
But my develop env is windows 10 and Mac. In my windows, lintr can run.
Could you tell me your settings for R?

**Comment by schelhorn** [comment]
Sorry, not required afterall. There issue only appears when I specified Rterm.exe as the interpreter. With R.exe, everything works as intended. Closing.

**Comment by Ikuyadeu** [comment]
@schelhorn  Ok, I should write for windows settings.
Thank you for information.

**Comment by wedneyyuri** [comment]
Hi @Ikuyadeu,

I'm using Windows 10, vscode 1.18.0 and R (version 3.4.2 (2017-09-28) -- "Short Summer") but the Lintr is not working for me. It's a fresh installation, so I don't know if I did anything wrong.

User Settings:
```json
{ "r.rterm.windows": "C:\\Program Files\\R\\R-3.4.2\\bin\\x64\\R.exe" }
```

Screenshots:
![image](https://user-images.githubusercontent.com/7511692/32851435-14a8565e-ca1c-11e7-823e-e574751d4bf5.png)
