### ISSUE TITLE
how do i change the location of r path in vs code

### ISSUE THREAD

**Issue by premiumwd** [Ikuyadeu/vscode-R#30]
how do i change the windows default r location

**Comment by premiumwd** [comment]
please add to documentation how to add change path in vs code not every1 knows this.

**Comment by Ikuyadeu** [comment]
@premiumwd Thank you for issue!
I'll do.
Did you solved this?

**Comment by premiumwd** [comment]
yes, had to search for it in someone else's reported bug on this repo.

**Comment by Ikuyadeu** [comment]
@premiumwd  OK, think you for sharing.
I'll write it in next 2 weeks.
