### ISSUE TITLE
Rscript instead of Run Source

### ISSUE THREAD

**Issue by nwillems94** [Ikuyadeu/vscode-R#300]
**Is your feature request related to a problem? Please describe.**
I have recently switched to radian console which is great, but I've noticed when running the source of some files, I get an `Error: cannot allocate vector of size...`. This does not occur if my r.rterm.windows is set to R.exe but does when its set to radian.exe. 

**Describe the solution you'd like**
Clearly this is a problem with radian, but one solution which i think has merit on its own, would be the option to execute Rscript on the current file. Granted this is easily accomplished by switching to the terminal but so it `source('')`. It would be cool to see the option to have this command replace the functionality of the Run Source button.

**Comment by andycraig** [comment]
Hi @nwillems94, thank you for the suggestion. 

A couple of workarounds are:

1. Bind Rscript to a keyboard shortcut using the command `r.runCommandWithEditorPath` (examples here https://github.com/Ikuyadeu/vscode-R#creating-keybindings-for-r-commands ). The disadvantage of this approach is that the active terminal can't already be in R or radian.
1. Create a VS Code Task. This is more work to set up but the advantage is that it runs in the background.

**Comment by renkun-ken** [comment]
I prefer the @andycraig's second solution. Following is my tasks to use blogdown functions to create post and serve site:

`${workspaceFoler}/.vscode/tasks.json`:

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "new_post",
      "type": "shell",
      "command": "Rscript -e 'blogdown::new_post(\"${input:title}\")'",
      "problemMatcher": []
    },
    {
      "label": "serve_site",
      "type": "shell",
      "command": "Rscript -e 'blogdown::serve_site()'",
      "problemMatcher": []
    }
  ],
  "inputs": [
    {
      "id": "title",
      "description": "Article title",
      "default": "untitled",
      "type": "promptString"
    }
  ]
}
```

The tasks feature is very powerful. You may take a look at https://code.visualstudio.com/docs/editor/tasks for more details.

**Comment by nwillems94** [comment]
I hadn't heard of the tasks feature, thanks for the suggestion! 
For future reference here is my work around:

tasks.json:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558

    // for the documentation about the tasks.json format
    "version": "2.0.0",  
    "tasks": [  
        {  
            "label": "Rscript",  
            "type": "shell",  
            "command": "Rscript.exe ${file}"  
        }  
    ]  
}
```

and keybindings.json (I use `ctrl+alt+s` to maintain `ctrl+shift+s` as save as)
```// Place your key bindings in this file to override the defaultsauto[]
[
    {
        "key": "ctrl+alt+s",
        "command": "workbench.action.tasks.runTask",
        "args": "Rscript",
        "when": "editorTextFocus && editorLangId == 'r'"
    },
    {
        "key": "ctrl+shift+s",
        "command": "-r.runSource",
        "when": "editorTextFocus && editorLangId == 'r'"
    }
]
```
