### ISSUE TITLE
Add recommended TypeScript linter to CONTRIBUTING.md

### ISSUE THREAD

**Issue by andycraig** [Ikuyadeu/vscode-R#304]

**Comment by Ikuyadeu** [comment]
I will update the file by referring https://github.com/microsoft/vscode/wiki/How-to-Contribute#linting

**Comment by Ikuyadeu** [comment]
Done https://github.com/Ikuyadeu/vscode-R/wiki/Contributing#lint

**Comment by andycraig** [comment]
@Ikuyadeu Great, thank you!
