### ISSUE TITLE
Remove Run Selection/Line in Active Terminal

### ISSUE THREAD

**Issue by andycraig** [Ikuyadeu/vscode-R#306]
The command `Run Selection/Line in Active Terminal` was added before the setting `Always Use Active Terminal`. `Always Use Active Terminal` has been available for a while now and my guess is that nobody is using `Run Selection/Line in Active Terminal` anymore. If it was removed, I think that a lot of functions could be simplified by avoiding this 'pattern':

```typescript
const callableTerminal = await chooseTerminal();
if (callableTerminal === undefined) {
    return;
}
runSelectionInTerm(callableTerminal);
```

A couple of options:

1. Remove `Run Selection/Line in Active Terminal` and see if anyone complains;
2. Deprecate it by showing a message when it is used, like 'This command will be removed. Enable setting "Always Use Active Terminal" (with option to not show message again). Then remove it after a couple of months.

**Comment by andycraig** [comment]
Showing a warning message with option to not show message again requires adding a setting like`deprecateSendActiveDontShowAgain`.

**Comment by andycraig** [comment]
Option 3: Remove the command’s functionality and just show a message when it is used, like 'This command has been removed. Enable setting "Always Use Active Terminal"'. Then, remove it completely after another couple of months.

That way it’s clear to the user, and we wouldn’t have to add a setting that would only be used temporarily.

Unless anyone has any objections, let’s go with Option 3.

**Comment by renkun-ken** [comment]
Option 3 LGTM
