### ISSUE TITLE
Sending multi-line string removes lines starting with hash

### ISSUE THREAD

**Issue by renkun-ken** [Ikuyadeu/vscode-R#312]
Sending the following multi-line string to terminal removes `# hello` which is mistakenly treated as comment:

```r
text <- "
# hello
this is new #hello
"
```

Instead the following is actually sent to terminal:

```
> text <- " 
  this is new #hello 
  "
```

**Comment by renkun-ken** [comment]
I'm wondering if we could simply not remove comments from code to be sent to terminal and just send the original text since sometimes I need to take a look at history of my terminal commands with comments as my note and sections. Removing comments makes it hard to review the command history in terminal.

**Comment by andycraig** [comment]
> I'm wondering if we could simply not remove comments from code to be sent to terminal and just send the original text since sometimes I need to take a look at history of my terminal commands with comments as my note and sections.

I’m happy with this change being made.

**Comment by renkun-ken** [comment]
Suppose

```r
text <- "


# hello



this is new #hello
"
```

The blank lines and `#`-starting lines are all removed, which is both undesired in multi-line strings.

**Comment by andycraig** [comment]
This case still needs to be handled. I think this is why commented lines were removed in the first place.

```r
function() {
    1
# }
    2
}
```

If the cursor is on the first line, all lines should be sent. That is, the closing brace on the comments line should not be matched with the opening brace.

**Comment by andycraig** [comment]
Hmm, actually the `# }` case should already be handled by `cleanLine`, so it is probably safe just to not drop commented lines.

**Comment by renkun-ken** [comment]
I tested with 

```r
function() {
    1
# }
    2
}
```

and it works well.

**Comment by renkun-ken** [comment]
I'm wondering if `cleanLine` is still relevant for some cases?

**Comment by andycraig** [comment]
Yes, `cleanLine` is still needed. Without it, the `# }` case will incorrectly match the commented brace.
