### ISSUE TITLE
Expand Session watcher to help auto complete with NSE (tidyverse syntax)

### ISSUE THREAD

**Issue by gowerc** [Ikuyadeu/vscode-R#323]
It would be awesome if the session watchers autocomplete could be expanded to work with non-standard evaluation for example when using dplyr's mutate/select/etc.

I.e.  when writing something like:

```
iris %>%
    select( 
```
Then have the auto-complete popup with the list of variables within the iris dataset.

**Comment by gowerc** [comment]
For reference Rstudios implementation of this simply looks at the top most object for which names to use in the autocomplete, for example

![image](https://user-images.githubusercontent.com/8447209/82741361-0b8a2e00-9d49-11ea-827b-6fd8dfdd51f5.png)

As you can see Rstudio just offers all the names of iris in the autocomplete even though none of them exist after the `gather()` command. Having said that it does have some sense of context as you can see the newly created variable is available in the list. I think even if it was possible to just get the initial object variables listed (ignoring newly created ones) it would be a big help to development !

**Comment by gowerc** [comment]
At @andycraig  & @renkun-ken ,   

Which files are related to the current session watcher autocomplete.  For example when session watcher is enabled I am able to do this:

![image](https://user-images.githubusercontent.com/8447209/83347222-6c9e9c80-a31b-11ea-970c-5711753cd441.png)


But I'm struggling to work out where in the code provides this functionality

**Comment by renkun-ken** [comment]
On mobile now. If I remember correctly, The session watcher completion is implemented in extension.ts: getBracketCompletions, etc.

**Comment by randy3k** [comment]
FYI, it is how RStudio implemented it: https://github.com/rstudio/rstudio/blob/7fd3ff2ba1b579952baceaddd6fcb2ca4c88d186/src/cpp/session/modules/SessionRCompletions.R#L1963

**Comment by renkun-ken** [comment]
@gowerc I come up with an easy approach to this at https://github.com/renkun-ken/languageserver/tree/token-completion which simply put all symbols that appear in the same document into the completion list, which will be helpful to complete symbols that already appear in the document.

![image](https://user-images.githubusercontent.com/4662568/90848319-28152100-e39f-11ea-9cb1-4dbad413efca.png)

You might have a try on this any let me know if this is helpful.

**Comment by renkun-ken** [comment]
To provide completion items in a pipe expression, without a parser, it is a bit trickier to detect the names of the variables to show completions, although we already have the `names()` of all variables in the global environment in `globalenv.json` created by the session watcher. I suggest we do the following:

```r
my_dt %>%
  mutate(var3 = test) %>%
  select(var1, var2, var3)
```

As a starting point, we should detect `my_dt` in this case, and hopefully `var3` in the future.

**Comment by danielbasso** [comment]
My totally abstract idea by now is to dynamically compute `names()` for the whole pipe chain using only the first row of the dataframe, to make computations fast. Using only the first row shouldn't affect `select()`, `group_by()`, `summarise()` and others. It could affect `filter()`, but this can be ignored, I guess?

**Comment by renkun-ken** [comment]
> My totally abstract idea by now is to dynamically compute names() for the whole pipe chain using only the first row of the dataframe, to make computations fast ...

I'm afraid we cannot execute user code in any way because it might have side effects to user sessions. Imagine user in-place mutate or remove columns or execute some code that has important side effects like

```r
my_df %>%
  filter(var == 4) %>%
  select(path) %>%
  remove_files()
```

**Comment by renkun-ken** [comment]
@gowerc @danielbasso would you like to try the PR #530 by installing the artifact in https://github.com/Ikuyadeu/vscode-R/actions/runs/500273775?

**Comment by gowerc** [comment]
Sure will try and give it a test this weekend !

**Comment by renkun-ken** [comment]
Sorry, it is not very useful at the moment since it only works with very limited cases. I'll improve it later.

**Comment by danielbasso** [comment]
> Sure will try and give it a test this weekend!

Same here!

> Sorry, it is not very useful at the moment since it only works with very limited cases. I'll improve it later.

No worries man, this is volunteer work, do it at your own pace. I'll try to help whenever I can.

**Comment by renkun-ken** [comment]
@gowerc @danielbasso You could try the [latest development build](https://github.com/Ikuyadeu/vscode-R/releases/tag/latest) and see if it works for you.

**Comment by gowerc** [comment]
Hey @renkun-ken ,

First off this is awesome, than you for your work on this !!

It wasn't clear to me from the above conversation if inline variables (those created within the pipeline) were supposed to be made available in this update. For me at least the base dataframes variables are available but not those that are defined inline:

![image](https://user-images.githubusercontent.com/8447209/105749610-8e4c3400-5f3b-11eb-8ee1-353bdd4c880c.png)

**Comment by renkun-ken** [comment]
@gowerc If I'm understanding it correctly, then you want

```r
x <- iris
x %>%
  mutate(score = Petal.Length + Petal.Width) %>%
  filter()
```

The autocompletion triggered by `(` does indeed only show the existing columns as completion items of `x` in the user session. The `score` item will appear when you try to type it, and it is provided by languageserver token completion, which is based on code analysis rather than user session globalenv.

<img width="749" alt="image" src="https://user-images.githubusercontent.com/4662568/105785447-d90a9200-5fb5-11eb-9513-5c5dbf93229b.png">

**Comment by gowerc** [comment]
Indeed, would be great if it could also be included in the autocompete triggered by `(` but absolutely no worries if thats not possible this is already an amazing improvement as is :)

**Comment by renkun-ken** [comment]
I filed https://github.com/REditorSupport/languageserver/pull/369 that adds `(` to the completion trigger characters in languageserver.

**Comment by KatlehoJordan** [comment]
Just starting to try to use R extension in VS Code to replace RStudio. It seems to me that the original ask of this issue has still not been addressed.

If I initialize a new file, then using `dplyr` pipelines with the pipe operator `%>%` still does not make the variables of the source dataset visible for autocompletion.

Specifically:
```r
library(dplyr)
iris %>%
   select(
````

The intellisense that appears after the `select(` does not give me a list of the variables in the `iris` dataset, which was the original ask, and is standard behavior in RStudio.

Am I doing something wrong? Or is this a feature that "won't be done", hence this issue being closed?

Thanks for your help!

**Comment by KatlehoJordan** [comment]
Terrific! I had a suspicion that if it does not work with `iris` it would also not work with any dataset where the symbols for the tokens were not already seen by the workspace.

To test, I created a `.csv` file with a simple dataframe-like structure and used `my_data <- read.csv(...)` to import it.

**I can confirm that you are correct;** when I subsequently use `my_data %>% select(` my variable names are found and suggested.

This is really terrific.

Thank you for this extension and all of it's features! 🥳
