### ISSUE TITLE
Run code block but leave cursor in existing position (Rstudio feature)

### ISSUE THREAD

**Issue by gowerc** [Ikuyadeu/vscode-R#324]
Rstudio have this feature where you can run the current code "block" but leaving the cursor in its existing position. You already have the ab

ility to run code "blocks" (which is awesome) but would be also great to have this second option available as well!  

Apologies if it already exists and I missed it, gif to help clarify what I mean:

![2020-05-15 12 48 05](https://user-images.githubusercontent.com/8447209/82047847-6a95d600-96ab-11ea-8e1b-9ea746dda101.gif)

**Comment by renkun-ken** [comment]
We could definitely add this without moving the cursor as RStudio supports it and bind to the same shortcut key (<kbd>Option+Enter</kbd>, not sure the key under Ubuntu and Windows?)

**Comment by renkun-ken** [comment]
From [RStudio IDE Cheatsheet](https://github.com/rstudio/cheatsheets/raw/master/rstudio-ide.pdf), we can see the run code commands:

<img width="593" alt="image" src="https://user-images.githubusercontent.com/4662568/82061031-c0459f00-96fa-11ea-989c-a83f7812f2e3.png">

We could add this "Run current (retain cursor)" command.
