### ISSUE TITLE
Mac & Linux search for default version of R

### ISSUE THREAD

**Issue by gowerc** [Ikuyadeu/vscode-R#339]
Currently mac and linux setups do not create a new terminal if no path is specified (unlike windows which searches the registry listings).  I would suggest that the PATH variable should be checked to see if a version of R exists and use that one if no path has been specified.

**Comment by renkun-ken** [comment]
I'm wondering if similar logic applies to Windows, i.e. first find in registry, then find in Windows `PATH`?

**Comment by gowerc** [comment]
Its been a long time since I've used windows sorry, does it use PATH in the same way that linux/mac does ? 

If so then yer I guess it makes sense to expand this to all 3

**Comment by renkun-ken** [comment]
Tested on all Windows 10, macOS, and Ubuntu and everything works as expected. Maybe similar changes could be made to vscode-r-lsp and radian so that how different parts of R language support could behave consistently.
