### ISSUE TITLE
Lintr does not work in Windows 10 when invoked from a folder with spaces

### ISSUE THREAD

**Issue by wedneyyuri** [Ikuyadeu/vscode-R#34]
- VSCode Version: 1.18.0
- VSCode-R Version: 0.5.0
- OS Version: Windows 10 Pro 10.0.15063 Build 15063

Steps to Reproduce:

1. Install "R" on a folder with spaces ("C:\Program Files\R\R-3.4.2\bin\x64\R.exe")
2. Execute the command `R: lintr` from vscode

Related issues: 
 - https://github.com/nodejs/node/issues/7367
 - https://github.com/Ikuyadeu/vscode-R/issues/3

**Comment by wedneyyuri** [comment]
Under the hood, the nodejs is trying to execute the following command on cmd.exe:

![image](https://user-images.githubusercontent.com/7511692/32853770-76c3bffc-ca23-11e7-9dd2-5dd87dbff946.png)

Spawning process in Windows can be tricky, to execute a file from a folder with quotes [we need to escape it](https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows). Example:

```js
// OR...
const exec = require('child_process').exec;
exec('my.bat', (err, stdout, stderr) => {
  if (err) {
    console.error(err);
    return;
  }
  console.log(stdout);
});

// Script with spaces in the filename:
const bat = spawn('"my script.cmd"', ['a', 'b'], { shell: true });
// or:
exec('"my script.cmd" a b', (err, stdout, stderr) => {
  // ...
});
```

I'm working on a fix and will open a pull request today.

**Comment by affanshahid** [comment]
Any workarounds?

**Comment by andycraig** [comment]
Linting is now provided by the language server. I’ve tried linting in Windows 10 with R installed in a file path with spaces and it worked fine, so I think this issue is probably resolved. I’m going to close it, but please post if you’re still having this problem.
