### ISSUE TITLE
FR: Send expanded code templates to the terminal

### ISSUE THREAD

**Issue by tomtom** [Ikuyadeu/vscode-R#345]
Quite often, I would like to send `str(word_under_cursor)` or similar commands to the terminal. It would be nice if the R extension for VSCode supported user defined code snippets that get expanded and set to the terminal.

Use case:

Assume the following line of text

```
foo = bar()
      ^
      Cursor position
```
Users should be able to define templates like, e.g., `??%s` or `str(%s)` that should be expanded with the word under cursor (or the whole line, the selected text) and then be sent to the terminal.

Regards

**Comment by andycraig** [comment]
Hi @tomtom, `r.runCommandWithSelectionOrWord` might be what you're after. Have a look here: https://github.com/Ikuyadeu/vscode-R#creating-keybindings-for-r-commands

**Comment by tomtom** [comment]
Excellent. Thanks a lot. How could I have missed that.

BTW you probably should make the when condition:

         "when": "editorTextFocus && editorLangId == r",

Thank you very much.

Regards

**Comment by andycraig** [comment]
@tomtom Great to hear that did the job!

> BTW you probably should make the when condition:
> "when": "editorTextFocus && editorLangId == r",

Yes, that would be better. PR welcome! :smiley:
