### ISSUE TITLE
too many R sessions left at R-project folder under .vscode

### ISSUE THREAD

**Issue by litn2018** [Ikuyadeu/vscode-R#352]
when create a new terminal, vscode-r will not pick up the previous r-session files. and the old files under previous session id are kept and will have more and more session files. Should the extension delete those old session files or reusing the files? every time when a new terminal is created, a new session folder is created, it goes ugly.

**Comment by renkun-ken** [comment]
If the session is exited normally, the folders should be removed.

In #348, the watching mechanism is switched from `vscode.FileSystemWatcher` (which only works within workspace) to `fs.watch` (which works system-wide). This should no longer be a problem as there won't be `{workspaceFolder}/.vscode/vscode-R` folder any more.
