### ISSUE TITLE
RMarkdown citations not highlighted properly in R Markdown syntax format

### ISSUE THREAD

**Issue by rensa** [Ikuyadeu/vscode-R#36]
- VSCode Version: 1.18.1
- VSCode-R Version: 0.5.0
- OS Version: macOS 10.13.1

Steps to Reproduce:

1. Edit an `.Rmd` document with citations in it.
2. Ensure that `R Markdown` is selected as the highlighting language.

![screenshot 2017-11-20 12 33 58](https://user-images.githubusercontent.com/6520659/32998438-1d2c0d12-cdef-11e7-9598-43faed518f6c.png)

In this case, the citations aren't recognised by the highlighting, and pairs of underscores are read as italicisation. If the citation key has an odd number of underscores, the italicisation continues past the citation on to the next underscore.

**Comment by rensa** [comment]
Thanks very much! There are definitely some other aspects of Markdown that would benefit from still being highlighted in R Markdown, like list items and YAML front matter.

**Comment by andycraig** [comment]
An approach here might be to designate citation labels as their own kind of object for highlighting. I found this link about ASCII characters that can appear in citation labels: https://tex.stackexchange.com/a/408548

@Ikuyadeu Is it okay to edit the Rmd syntax file directly, or is it automatically generated somehow?

**Comment by andycraig** [comment]
Citation labels, list items and YAML front matter are all highlighted correctly in VSCode's Markdown highlighting.
