### ISSUE TITLE
Outline review for rmd files as Rstudio

### ISSUE THREAD

**Issue by gitbobo** [Ikuyadeu/vscode-R#363]
**Is your feature request related to a problem? Please describe.**
When I open rmd file,I cannot review outline in vs code.It's convenient to jump to {r chunk name} in Rstudio.
![image](https://i.stack.imgur.com/Fm4x5.png)

**Describe the solution you'd like**
https://code.visualstudio.com/api/references/vscode-api

**Describe alternatives you've considered**
like Rtools

**Additional context**

**Comment by renkun-ken** [comment]
This could be implemented in languageserver to follow up https://github.com/REditorSupport/languageserver/pull/186.

**Comment by renkun-ken** [comment]
Implemented by languageserver.
