### ISSUE TITLE
remove or warn about cmd + 1 shortcut defaults

### ISSUE THREAD

**Issue by maxheld83** [Ikuyadeu/vscode-R#368]
These shortcuts (defaulting to `CMD` on macOS, but same problem otherwise)

> Run `nrow`, `length`, `head`, `thead`, names functions (Ctrl + 1, 2, 3, 4, 5)

overwrite the vscode defaults used to navigate between different editor groups:

> Focus into 1st, 2nd or 3rd editor group

(from [here](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf)).

This can fixed by the user by removing these shortcuts, but it takes a while to figure out.

I also think the group navigation is a fairly basic shortcut in vscode that may not be worth touching.

Thanks for the amazing work!

**Comment by andycraig** [comment]
Hi @maxheld83, thank you for this suggestion.

@Ikuyadeu @renkun-ken I agree that it would be better not to override these default VS Code shortcuts. I think we should remove the shortcuts for these commands.

**Comment by renkun-ken** [comment]
@andycraig I agree. In fact, I revert all these in my key bindings from the beginning.

**Comment by keita-makino** [comment]
@andycraig The wiki page is not fixed yet, FYI.

**Comment by andycraig** [comment]
Hi @keita-makino, here's the section of the Wiki that was updated: https://github.com/Ikuyadeu/vscode-R/wiki/Keyboard-shortcuts#removed-keyboard-shortcuts

If there's anything specific that seems to be missing/needs fixing, let me know.

**Comment by seed-of-apricot** [comment]
@andycraig I see, but I meant the one on the top page. This description seemed to tell that the binding is by default.
![image](https://user-images.githubusercontent.com/26666870/93481120-11d18680-f8b3-11ea-982c-1c918c413211.png)

**Comment by keita-makino** [comment]
@andycraig I see, but I meant the one on the top page. This description seemed to tell that the binding is by default.
![image](https://user-images.githubusercontent.com/26666870/93481120-11d18680-f8b3-11ea-982c-1c918c413211.png)

**Comment by andycraig** [comment]
@keita-makino Oh, the README! You are right, I missed that. Thank you! I'll fix it this weekend. A PR would of course be welcome too.

**Comment by keita-makino** [comment]
@andycraig No it's the top page of the wiki, so I cannot make PR... Thank you for your cooperation though.

**Comment by andycraig** [comment]
@keita-makino Thanks for persisting, I understand now. It's the bit of the Wiki that has a copy of the README. I will fix.
