### ISSUE TITLE
R snippet(Read CSV) seems not correct

### ISSUE THREAD

**Issue by jnote1** [Ikuyadeu/vscode-R#369]
https://github.com/Ikuyadeu/vscode-R/blob/299eb35d6cada82dc659f94cebbf0db45b89ef28/snippets/r-snippets.json#L339

It seems wrong last close bracket '} ' 
in `stringsAsFactors = ${6|FALSE,TRUE|}})`

**Comment by andycraig** [comment]
Hi @jnote1, thank you for reporting. This does look wrong.
