### ISSUE TITLE
Customize folding for R scripts

### ISSUE THREAD

**Issue by hongyuanjia** [Ikuyadeu/vscode-R#37]
- VSCode Version: 1.18.1
- VSCode-R Version: 0.5.0
- OS Version: Microsoft Windows 10 Version 1709 (OS Build 16299.64)

Just some background: I am a new user of VSCode.  Before I switched to VSCode, I am a Vim user. There is a Vim plugin called [NVim-R](https://github.com/jalvesaq/Nvim-R) that can covers some general functionalities for R programming in Vim. The author wrote an R package called [nvimcom](https://github.com/jalvesaq/Nvim-R/tree/master/R/nvimcom) to handle the communication between Vim and R. I am very glad to see your extraordinary works on vscode-R. I know that the language server of R in vscode is under development. Hope it could be done soon and Intellisense could be added in the near future.

In vscode 1.17.1, the feature of [folding by regions](https://code.visualstudio.com/updates/v1_17#_editor) was added. Currently, I can toggle folding based on functions. I wonder if there is any way to add a customized folding marker for R, e.g. `{{{` and `}}}` like Powershell `#region` and `#endregion` described in vscode docs?

**Comment by Ikuyadeu** [comment]
@hongyuanjia Thank you for using and new idea!
I'm not sure about R region. If R Tool for VS or R Studio use it, I'll just use it. 
If not, I'll consider with other R editor developers.

**Comment by Ikuyadeu** [comment]
I just support region like this
```r
# © Microsoft. All rights reserved.

#' Add together two numbers.
#'
#' @param x A number.
#' @param y A number.
#' @return The sum of \code{x} and \code{y}.
#' @examples
#' add(1, 1)
#' add(10, 1)
add <- function(x, y) {
  x + y
}

#region

print(add(1, -2))
print(add(1.0e10, 2.0e10))

#endregion

print(paste("one", NULL))
print(paste(NA, 'two'))

print(paste("multi-
line",
'multi-
line'))
```
You can use this next update!

**Comment by hongyuanjia** [comment]
@Ikuyadeu I tried the new version. It works like a charm! Thanks a lot!
