### ISSUE TITLE
Starting R terminal with Python extension loaded causes problems

### ISSUE THREAD

**Issue by hongooi73** [Ikuyadeu/vscode-R#370]
**Describe the bug**

I'm not sure whether this is a bug with the R or Python extension, or both.

When I run the "Create R terminal" command, and the Python extension is active, I end up with extraneous text in the terminal pane.

**To Reproduce**
1. Have this extension and the [MS Python extension](https://github.com/Microsoft/vscode-python) installed
1. Have a folder with both .R and .py files present
2. Open a .py file (this loads vscode-python)
3. Open a .R file (this loads vscode-R)
4. With the .R file active, run "Create R terminal"

This results in the following text being sent to the terminal (it's used by the Python extension)

```
R version 4.0.2 (2020-06-22) -- "Taking Off Again"
Platform: x86_64-w64-mingw32 (64-bit)
r$> C:/Users/hongo/Miniconda3/Scripts/activate
Error: unexpected '/' in "C:/"
r$> conda activate base
Error: unexpected symbol in "conda activate"
r$>
```

**Environment (please complete the following information):**
 - OS: Windows 10 2004
 - VSCode Version: 1.46.1
 - R Version: 4.0.2
 - vscode-R version: 1.4.2

**Additional context**
- vscode-python version: 2020.6.90262
- using Radian as the rterm

**Comment by andycraig** [comment]
Hi @hongooi73, this is caused by the Python extension. I created an issue for it: https://github.com/microsoft/vscode-python/issues/11963
