### ISSUE TITLE
r.term.windows will not populate with R.exe file path in settings, will not run R terminal in VS Code

### ISSUE THREAD

**Issue by joeamoroso** [Ikuyadeu/vscode-R#373]
**Describe the bug**
r.term.windows will not populate with R.exe file path in settings, will not run R terminal in VS Code.

**To Reproduce**
1. Go to R Extension
2. Click on Settings
3. Scroll down to r.term.windows and enter file path
4. In the feature contributions tab in the extension, r.term.windows is blank as well as the JSON variable. But, it is
populated in the setting tab.

**Do you want to fix by self? (I hope your help!)**
Yes

**(If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)**

(If related)setting.json
"r.rterm.windows": 
```json
// R.exe path for windows
"r.rterm.windows": "",  # Here's the issue!

// R path for Mac OS X
"r.rterm.mac": "/usr/local/bin/R",

// R path for Linux
"r.rterm.linux": "/usr/bin/R",

// R command line options (i.e: --vanilla)
"r.rterm.option": [],

// An optional encoding to pass to R when executing the file, i.e. 'source(FILE, encoding=ENCODING)'
"r.source.encoding": "UTF-8",

// Keeping focus when running
"r.source.focus": "editor",

// Use active terminal for all commands, rather than creating a new R terminal
"r.alwaysUseActiveTerminal": false,

// Use bracketed paste mode
"r.bracketedPaste": false,

// Enable R session watcher (experimental)
"r.sessionWatcher": false,

// Delay in milliseconds before sending each line to rterm (only applies if r.bracketedPaste is false)
"r.rtermSendDelay": 8,
```

**Expected behavior**
R extension will execute R.exe path in extension settings.

**Screenshots**
You can show the keybord contents by pressing `F1` and `Developer: toggle screencast mode`

**Environment (please complete the following information):**
 - OS: Windows 10
 - VSCode Version: 1.46.1
 - R Version: 3.6.1
 - vscode-R version: 1.4.2

**Additional context**

**Comment by renkun-ken** [comment]
If `r.rterm.windows` is not specified, vscode-R will find from Windows registry first, and then `PATH`. This should work for most R installation from official installer with "Save version number in registry".

If your R executable is neither specified in registry nor in `PATH`, then you have to specify this setting to let vscode-R know the path.

https://github.com/Ikuyadeu/vscode-R/pull/374 removes the default value of both `r.rterm.mac` and `r.rterm.linux` so that they by default rely on `PATH` first and are only necessary when R path is not installed to default location.

**Comment by joeamoroso** [comment]
Yes, I specify that path in the settings, but I will never save the file path I enter in the R extension settings tab. There is just blank quotes, but that field is filled when you look at the settings: See :
![image](https://user-images.githubusercontent.com/62147557/86014398-45a4ba80-b9ee-11ea-9810-4625f1253416.png)

Then: 
![image](https://user-images.githubusercontent.com/62147557/86014541-771d8600-b9ee-11ea-90d2-6f6e40333cad.png)

**Comment by renkun-ken** [comment]
The blue vertical line in the first image indicates that the setting is modified. The second image is the feature contribution of the extension, only showing the default value rather than the current value.

**Comment by assignUser** [comment]
@joeamoroso did you manage to get it to work or do you require additional assitance?

**Comment by joeamoroso** [comment]
Hi, I apologize about my late reply, I was able to get the PATH variable added in my environment and it seems to be working well in VS Code now, thank you
