### ISSUE TITLE
Wish: GitHub release to follow development

### ISSUE THREAD

**Issue by pat-s** [Ikuyadeu/vscode-R#382]
Currently the changes are logged in `Changelog.md`. However, there is no way to stay informed about updates to this file.
It is also cumbersome to look up the vscode extension every once in a while for updates. Also for both, no timestamps exist.

It would be great if the "GitHub release" feature could be used (again). Users can subscribe to releases and they contain timestamps.

Thanks for all your work! (Trying) to follow development as close as possible 😄

**Comment by Ikuyadeu** [comment]
@pat-s  Thank you for your suggestions.

As you say, reusing GitHub release is useful for users accessing from GitHub.
We will try that from the next release.

However, we will keep CHANGELOG.md to support users who only access it via vscode.
To fix missing timestamps and the possibility that I might miss a change, we will try to automatically update like a python extension.
https://github.com/microsoft/vscode-python/blob/master/news/announce.py

**Comment by pat-s** [comment]
@Ikuyadeu Unfortunately no GitHub releases for the latest extension releases ;/ I would really be happy if this could be done 😃 

Note that there are convenience functions like `usethis::use_github_release()` which makes this task a one-liner.

**Comment by pat-s** [comment]
Thanks a lot for this!
