### ISSUE TITLE
VS Code outline not working

### ISSUE THREAD

**Issue by Dee-L** [Ikuyadeu/vscode-R#386]
I followed the instructions on [this site](https://renkun.me/2019/12/11/writing-r-in-vscode-a-fresh-start/) in order to start using VS Code with R. Several features work, but a couple do not.

I only get things to show up in the outline if I include 4 asterisks after.

```
# This shows up ####

# This does not show up

```
Also, the code folding works based on indentation, but not based on using asterisks to identify sections/subsections.

Tips?

**Comment by renkun-ken** [comment]
This is intended behavior for R document which is actually implemented by https://github.com/REditorSupport/languageserver/pull/163, just like RStudio.

Since `#` starts a comment line in R code, regarding all comment lines as code sections is obviously not ideal.

For R markdown documents, the code sections could be more flexible, as implemented by https://github.com/REditorSupport/languageserver/pull/186.

**Comment by renkun-ken** [comment]
>Also, the code folding works based on indentation, but not based on using asterisks to identify sections/subsections.

If you are using the latest development version of languageserver, it should provide folding ranges based on multi-line expression blocks and code sections.

**Comment by Dee-L** [comment]
Aha! I did not notice in your blog post that the "sections" part was a .Rmd file rather than a .R file.

Thank you for the clarification and *very* fast response, 👍

**Comment by renkun-ken** [comment]
>Is there somewhere you can point me to learn more about how to use the Document/Workspace symbols features?

You could take a look at Help -> Keyboard shortcuts reference, and you need 

<img width="329" alt="image" src="https://user-images.githubusercontent.com/4662568/88937651-03092300-d2b7-11ea-8794-d51775e535ff.png">

"Go to Symbol.." shows document symbol, and "Show all Symbols" shows workspace symbols (all symbols in workspace).

>but none of the functions or variables I define show up in the outline of .R files

You need to run the following the install the latest development version of languageserver.

```r
devtools::install_github("REditorSupport/languageserver")
```

and reload your vscode and the symbols should show up. The all-symbol feature is implemented at https://github.com/REditorSupport/languageserver/pull/295, which is not released to CRAN yet.

**Comment by Dee-L** [comment]
Woot woot! Your tips were spot on, :).

Thanks!
