### ISSUE TITLE
magrittr pipe shortcut ?

### ISSUE THREAD

**Issue by xiaoouwang** [Ikuyadeu/vscode-R#388]
**Is your feature request related to a problem? Please describe.**

First, tks for the plugin !
Does vscode-R plugin have a shortcut, say command+shift+m for Mac to input the %>% ? In pycharm or Rstudio this kind of shortcut exists and is quite convenient.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andycraig** [comment]
Hi @xiaoouwang, thanks for using vscode-R! There's no built-in shortcut, but we do have a suggested shortcut in the Wiki: https://github.com/Ikuyadeu/vscode-R/wiki/Keyboard-shortcuts#suggested-keyboard-shortcuts

**Comment by xiaoouwang** [comment]
> Hi @xiaoouwang, thanks for using vscode-R! There's no built-in shortcut, but we do have a suggested shortcut in the Wiki: https://github.com/Ikuyadeu/vscode-R/wiki/Keyboard-shortcuts#suggested-keyboard-shortcuts

that's fantastic tks !

**Comment by renkun-ken** [comment]
Closing as resolved.

**Comment by psobolewskiPhD** [comment]
For what it's worth, in addition to the keybinding provided in the Wiki: https://github.com/Ikuyadeu/vscode-R/wiki/Keyboard-shortcuts#suggested-keyboard-shortcuts 
```
 {
        "key": "ctrl+shift+m",
        "command": "type",
        "when": "editorLangId == r || editorLangId == rmd && editorTextFocus",
        "args": { "text": " %>% " }
   },
```
it was helpful to me to add this one, which makes the pipe shortcut work in the Terminal:
```
{
        "key": "Ctrl+Shift+m",
        "command": "workbench.action.terminal.sendSequence",
        "args": { "text": "%>%" },
        "when": "terminalFocus"
    }
```
