### ISSUE TITLE
This does not appear to be a dataframe

### ISSUE THREAD

**Issue by andycraig** [Ikuyadeu/vscode-R#389]
I have just completed the install of ikuyadeu.r including radian etc as directed. I'm running vscode on Mojave 10.14.6 and have installed the grapecity.gc-excelviewer extension. However, I cannot view a dataframe. I am trying to view the "cars" dataframe but get an error in the bottom right saying that "This does not appear to be a dataframe". Any help would be appreciated, thanks!

_Originally posted by @tbkw in https://github.com/Ikuyadeu/vscode-R/issues/96#issuecomment-671453426_

**Comment by andycraig** [comment]
Hi @tbkw, when you are trying to view the `cars` dataframe, what text are you selecting? Or, if you aren’t selecting any text, what word is the cursor over?

That error happens if the extension thinks that the selected text or the word the cursor is on couldn’t correspond to an R variable name (e.g., because it contains a space).

**Comment by tbkw** [comment]
Hi @andycraig, I have tried selecting the entire variable in the text editor or in the terminal and get the same effect. "This does not appear to be a dataframe". The same effect also occurs if I place the cursor in the middle of the word without selecting it, right click, click command palette and then try to preview dataframe. Interestingly, preview environment works and produces a tab showing that the dataframe I am attempting to preview is a variable in my environment.

**Comment by andycraig** [comment]
Hi @tbkw, thank you for the additional details. What you’re describing should work, so it may be that this command has broken. I will look into it.

**Comment by tbkw** [comment]
After playing around I've found that I can get the dataframes to display but only if the variable name is a single letter. E.g. if I assign iris to the variable "a", I can the get it to display by either placing the cursor at the beginning of the variable or selecting the letter then going to command palette to view. This brings up the preview as expected. However, assigning the same dataframe even to a variable "aa" will now produce the same error as before: "This does not appear to be a dataframe" whether I put the cursor at the beginning or select the entire "aa". Hope this information helps and I am not doing something to cause such an odd error.

**Comment by andycraig** [comment]
Wow, that’s very strange! Thank you for that additional info, it definitely helps.

**Comment by andycraig** [comment]
I have replicated this.

Problem is that I changed `getWordOrSelection` from returning an array of strings to returning a string, but didn't update its use in `previewDataframe` here: https://github.com/Ikuyadeu/vscode-R/blob/c9070661b1ee7a9bb79095ccea7c176f6c059725/src/preview.ts#L33

**Comment by tbkw** [comment]
Hi, when will this fix be released in a new version?
