### ISSUE TITLE
Hint prompt cannot list library and user defined functions 

### ISSUE THREAD

**Issue by Victsz** [Ikuyadeu/vscode-R#39]
![image](https://user-images.githubusercontent.com/8154646/34399564-618920c0-ebc3-11e7-834c-d5b9bb9a9542.png)

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.3.9600
 R version 3.4.3 x64

**Comment by Ikuyadeu** [comment]
@Victsz Thank you for an issue.
Sorry, this function is not implemented ye.

**Comment by Ikuyadeu** [comment]
R language server is implemented!
