### ISSUE TITLE
Language server not working with Notebook

### ISSUE THREAD

**Issue by renkun-ken** [Ikuyadeu/vscode-R#396]
As I'm trying to implement the R Notebook using the [Notebook API](https://code.visualstudio.com/api/extension-guides/notebook) at #394 initiated by #378, I have no clue at the moment how to make language server work when editing R code cells.

The notebook API introduces a new schema `vscode-notebook-cell` which is not covered by the document selector of the language client created in vscode-r-lsp. I'm not sure if anything has to be changed in languageserver and vscode-r-lsp to handle requests from a notebook or notebook cell.

**Comment by andycraig** [comment]
I had a look at that API document and around the VS Code repo but I have no idea either. I'm not even sure if it's possible yet. Is it worth reaching out to the team implementing the Notebook API?

This seems to be a Notebook API 'mega-issue': https://github.com/microsoft/vscode/issues/93265

**Comment by renkun-ken** [comment]
The language server definitely works with Notebook. See the Jupyter Notebook in preview:

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/4662568/90200306-d9e5a800-de09-11ea-85bd-cf255925ec07.png">

Maybe we should take a look at how its language server and client are configured to handle requests from notebook cells.

**Comment by renkun-ken** [comment]
With some [changes](https://github.com/REditorSupport/vscode-r-lsp/compare/notebook) made to vscode-r-lsp, the language server now works with the notebook cells.


![Kapture 2020-08-26 at 22 57 15](https://user-images.githubusercontent.com/4662568/91319917-869f2c80-e7ef-11ea-9fba-a913d2a7e2ba.gif)
