### ISSUE TITLE
vscode doesnt run R code in radian when i hit control enter

### ISSUE THREAD

**Issue by bdeshon** [Ikuyadeu/vscode-R#398]
Hello, I just set up radian to run R code. I thought i did everything correctly but I guess might have goofed somewhere. :)

I pip installed radian and it works when I run 'radian' from the windows cmd (I am running windows 10). When I go into vscode and hit control enter it does not execute radian. At first I get an error that says 'There are no open terminals'. When I open a new terminal and repeat control enter, it runs the code in the command prompt but does not open radian first. I wasn't sure if it is possible to have radian launch when the line is executed (similar to how python works with vscode).

Below is the settings in vscode:
`"r.rterm.windows": "C:\\Users\\XXXX\\AppData\\Local\\Continuum\\miniconda3\\Scripts\\radian.exe",`
`"r.rterm.option": [ "--no-save", "--no-restore", "radian" ]`
`"r.terminalPath": "D:\\R-4.0.2\\bin\\x64\\r.exe"`
`"r.alwaysUseActiveTerminal": true,`
`"r.editor.bracesOnNewLine": true,`
`"r.bracketedPaste": true,`
`"r.lsp.path": "D:\\R-4.0.1\\bin\\x64",`

The vscode extensions I have installed are:
-R
-R Extension Pack
-R LSP Client
-R Tools
-r-vscode-tools

I appreciate any help you all could provide.

**Comment by renkun-ken** [comment]
There might be conflicts between the extensions you installed. R, R Extension Pack, and R LSP Client are compatible, but probably not with R Tools and r-vscode-tools. Please try removing R Tools and r-vscode-tools, and remove the settings `r.terminalPath`, `r.editor.bracesOnNewLine` which are from removed extensions.

Also, please ensure `r.rterm.windows` points to the executable path of radian, and `r.rterm.option` should be empty for radian. And `r.lsp.path` should be `D:\\R-4.0.2\\bin\\x64\\R.exe` in your case I guess?

Do you have an R installation with version written to registry? If so, you don't have to specify `r.lsp.path`, the extension will try to find the R executable in registry.

**Comment by assignUser** [comment]
@bdeshon I also had some weird issues when I had both vscode-R (R) and R tools installed. Removing R tools fixed the issues.

**Comment by bdeshon** [comment]
thanks all!  it seemed to work when i removed those packages and i fixed the paths.  i appreciate it.
