### ISSUE TITLE
shortcut for `str()` function

### ISSUE THREAD

**Issue by MrJGao** [Ikuyadeu/vscode-R#404]
Any chance we could have `cmd (ctrl) + 6` as the shortcut for `str()` function? I think many people use the function a lot, especially for the fact we don't have an environment panel showing the structure of variables in VSCode. Thanks!

**Comment by renkun-ken** [comment]
You might take a look at https://github.com/Ikuyadeu/vscode-R/wiki/Keyboard-shortcuts and send any command you want with your shortcut keys.

**Comment by MrJGao** [comment]
> You might take a look at https://github.com/Ikuyadeu/vscode-R/wiki/Keyboard-shortcuts and send any command you want with your shortcut keys.

Wow, this is super fancy!!! thanks. I'll close this one.
