### ISSUE TITLE
Insert Roxygen Skeleton

### ISSUE THREAD

**Issue by assignUser** [Ikuyadeu/vscode-R#405]
In Rstudio you can insert a roxygen skeleton with the correct param tags via keybind (when the cursor is within a function definition) to create e.g. this:
```r
#' Title
#'
#' @param x 
#'
#' @return
#' @export
#'
#' @examples
exported <- function(x) {
    x + 1
}
```

It would be a nice qol feature for package developers.
I might look into this but I have yet to make the first steps with vsc extension development/ts and wanted to put the idea out here :)

**Comment by andycraig** [comment]
Hi @assignUser, thank you for the suggestion. This seems like a good fit for a snippet. Users can add their own snippets. Also, snippets can be added to the extension without needing to write TypeScript.

Here is a guide on how to create them: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets

**Comment by assignUser** [comment]
@andycraig Hey thanks for teh quick reply. I will look into it but I am not sure that snippets are flexible enough to completely emulate the rstudio function which adds params depending on the function signature. But it is a good quick fix for now I guess 👍

**Comment by andycraig** [comment]
@assignUser Oh, I see what you mean. Yes, that would probably require some TypeScript rather than just a snippet.

If you decide you want to try implementing this, we can provide advice etc. as needed.

**Comment by renkun-ken** [comment]
I guess this could be made much easier to implement if we define some customized requests in language server so that editor clients could query the information of the parsed data of the document at a document point (row, column). Otherwise, detecting the function arguments could be non-trivial in many cases when cursor is inside the function body, e.g., complex function argument default value, cursor at closure in function, cursor at string literal in function.

Having access to the language client will make it much easier to implement customized language-related features such as this. Unfortunately, vscode-r-lsp and vscode-R are separate projects. I'm not sure if there's a way to access the language client created in vscode-r-lsp unless we merge the two projects (#98) previously done at https://github.com/renkun-ken/vscode-R/tree/lsp.

**Comment by MilesMcBain** [comment]
This would come very cheaply with #302. That way we could take advantage or R code that already exists to do this.

I know of code in {sinew} and {fnmate}, there's probably a few others.

**Comment by renkun-ken** [comment]
@MilesMcBain I didn't know there's already RStudio plugins doing all these. Thanks for letting us know!

**Comment by MilesMcBain** [comment]
Recently I've been the RStudio addin in [`{docthis}`](https://github.com/mdlincoln/docthis) for this purpose in VSCode and it works pretty well.

The differences to the built in RStudio behaviour are the function object name needs to be selected, and the function needs to exist as an object in the session, e.g. having been placed there by `devtools::load_all()`.

**Comment by andycraig** [comment]
It sounds like @MilesMcBain's approach of using the RStudio Addin {docthis} provides this functionality, so I'm going to close this issue as resolved. @assignUser If you feel like any essential functionality is still missing, please feel free to reply and we can re-open.

**Comment by assignUser** [comment]
@andycraig the use of Rstudio Addins sounds like a good solution for now 👍 !

**Comment by tylerhoecker** [comment]
> Recently I've been using the RStudio addin in [`{docthis}`](https://github.com/mdlincoln/docthis) for this purpose in VSCode and it works pretty well.
> 
> The differences to the built in RStudio behavior are the function object name needs to be selected, and the function needs to exist as an object in the session, e.g. having been placed there by `devtools::load_all()`.

Thanks for this tip @MilesMcBain. If possible, a bit more information about how to access the "Document object" addin from within VSCode would be super helpful!

**Comment by wleoncio** [comment]
A primitive way to accomplish this is to run `cat(docthis:::doc_this("object"))` and paste the output on your editor, but at that point I'd rather keep using the custom skeleton snippet I wrote. It doesn't edit parameters, but that's easily caught by `devtools::check()`.
