### ISSUE TITLE
VS Code using XQuartz as graphic device.

### ISSUE THREAD

**Issue by alex-gable** [Ikuyadeu/vscode-R#411]
both tables and plots rendering in XQuartz instead of in vscode

- VSCode Version: 1.49.1
- VSCode-R Version: 1.4.5
- OS Version: Mac OSX 10.15.6

Steps to Reproduce:

1. open radian or R in the vscode terminal (radian is set as the default R in my vscode-r settings, but both were tested)
1. View(mtcars)

Do you want to fix by self?

No, not this time, sorry!

(If related)setting.json

```json
    "r.bracketedPaste": true,
    "r.rterm.mac": "/Users/{username}/.local/bin/radian",
    "r.source.focus": "editor",
    "r.sessionWatcher": true,
    "r.lsp.use_stdio": true
```

**Comment by alex-gable** [comment]
Just noticed, help documentation is no longer loading in a vscode tab but is instead opening in the terminal

**Comment by renkun-ken** [comment]
Looks like the session watcher is not loaded. 

Would you like to take a look at `ls.str(.vsc)` on a fresh session?

**Comment by alex-gable** [comment]
is that supposed to be executed in an R session? if so:

```R
> ls.str(.vsc)
Error in ls.str(.vsc) : object '.vsc' not found
```

checked the vscode console to see if it worked there (it didn't) and turned this up:
![image](https://user-images.githubusercontent.com/5963623/93656123-e64abb00-f9dc-11ea-813e-d6a88896080d.png)

**Comment by renkun-ken** [comment]
How do you start your R session? Using `R: Create R session` command or starting R manually in the vscode terminal?

**Comment by alex-gable** [comment]
starting R manually in the terminal. Sometimes I kick it off just by executing code from the editor

**Comment by renkun-ken** [comment]
R terminal started manually does not activate session watcher out of the box. Please take a look at https://github.com/Ikuyadeu/vscode-R/wiki/R-Session-watcher#advanced-usage-for-self-managed-r-sessions.

**Comment by alex-gable** [comment]
Well. I feel awful. Appreciate you taking a look. I don't know how I've missed this in the past, guess I'm just used to starting a session from the editor. 

Reading those docs earlier, I didn't realize "from the vscode terminal" fell in the scope of "external" R session. It's good to know.

**Comment by renkun-ken** [comment]
`R: Create R session` starts an R session with a vscode-R supplied `.Rprofile` that activates session watcher. Manually started R session does not do that automatically. User has to put those code to start session watcher in user `.Rprofile` so that any R session started manually could work with session watcher, i.e. R session started inside a tmux window for persistence.

**Comment by renkun-ken** [comment]
Closing now. Feel free to reopen if you encounter problems using such mechanism with self-managed R session.
