### ISSUE TITLE
Installing on Windows, init.R not included in sessions by default?

### ISSUE THREAD

**Issue by slodge** [Ikuyadeu/vscode-R#417]
**Describe the bug**
I've gone through a couple of clean installs on Windows 10 laptops.

In both of these installs I installed:
- vscode-r
- r-lsp
- httpgd

The blogs on https://renkun.me/2020/06/16/using-httpgd-in-vscode-a-web-based-svg-graphics-device/ really helped with this :)

These installs went really well, except that `.vsc.browser` is not available

![image](https://user-images.githubusercontent.com/533662/95055720-9a418b00-06eb-11eb-825e-7f7879723e65.png)

To fix this locally, I manually edited my rprofile to get a source of init.r in there... and to get the chart drawing work I also had to enable the session watcher functionality.

I looked on https://github.com/Ikuyadeu/vscode-R/wiki/Installation:-Windows and couldn't spot any steps I missed.. it feels like perhaps there are some windows path installation issues?

**To Reproduce**
Follow 
https://github.com/Ikuyadeu/vscode-R/wiki/Installation:-Windows

Open a new R window, then try using `.vsc.browser` - it is unknown...

**Do you want to fix by self? (I hope your help!)**

Yes - happy to try

**(If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)**

Some where you might look pointers...

**Additional context**
Thanks for this - fab stuff

**Comment by renkun-ken** [comment]
It seems that the session watcher `init.R` is not sourced at all. Do you use `R: Create R terminal` to start R or do you start R manually in the terminal?

**Comment by slodge** [comment]
Thanks

I've always started it using `Ctrl`+`Enter` on some R in an editor window... that automatically starts and R session for me.

I've just experimented and I think that if I rollback my manual `.Rprofile` change and use `Ctrl`+`Shift`+`P` and "R: Create R terminal" then I do get .vsc injected...

So is this just about the route that `Ctrl`+`Enter` takes to creating a terminal?

**Comment by renkun-ken** [comment]
Ctrl + Enter will run `R: Create R terminal` if `r.alwaysUseActiveTerminal = false` and there's no active R terminal. User `.Rprofile` is sourced before `init.R`. If an error occurs before `init.R` is sourced, then it won't be sourced at all.

Looks like there might be an error in your `.Rprofile` that prevents sourcing `init.R` from running?

**Comment by slodge** [comment]
OK

I've run lots of different combinations now... 

I think the problem is by design...

I think in reading through the tutorial on https://renkun.me/2020/06/16/using-httpgd-in-vscode-a-web-based-svg-graphics-device/ and reading through the readme on here, I've completely missed the fact that those `.vsc` methods are only there if you somehow enable the session watcher.

Sorry for wasting your time on this - thanks for the excellent work and for answering this query - I know what I need to do now... so closing...
