### ISSUE TITLE
Run Selected has strange behavior

### ISSUE THREAD

**Issue by Victsz** [Ikuyadeu/vscode-R#42]
VSCode Version:1.19.1
R 3.4.3
VSCode-R Version: 0.52
Win10

Steps to Reproduce:

1.define
![image](https://user-images.githubusercontent.com/8154646/34507204-d6ec051c-f06e-11e7-9ef7-2df4519e607f.png)
2. select and ctrl + enter
![image](https://user-images.githubusercontent.com/8154646/34507200-ce27feae-f06e-11e7-8893-37d86702051c.png)

Run Wrong selection
![image](https://user-images.githubusercontent.com/8154646/34507226-054181b2-f06f-11e7-924b-1dbc158c084e.png)
And then append a ')' and enter
The terminal process terminated with exit code: 3221226356
![image](https://user-images.githubusercontent.com/8154646/34507238-2d26ad10-f06f-11e7-98c7-870f56f58e10.png)

**Comment by Ladvien** [comment]
@Victsz thanks for the detailed notes.  I’ll fix it ASAP.

**Comment by adamaltmejd** [comment]
I'm experiencing something similar on Mac. When I run a selection it actually tries to run all code on that line up until (and including) the selection, rather than only the selected text.

**Comment by Ladvien** [comment]
Apologies, I've found the problem, but wife had a baby and got distracted.  I'll try to fix this weekend.

**Comment by andycraig** [comment]
As a temporary workaround, I got the desired behaviour by adding this entry to my `keybindings.json` file:

    {"key": "ctrl+enter", "command": "workbench.action.terminal.runSelectedText"}

**Comment by Ladvien** [comment]
Ok! Finally starting on this fix.
