### ISSUE TITLE
Change name of `browser` function in init.R?

### ISSUE THREAD

**Issue by MilesMcBain** [Ikuyadeu/vscode-R#424]
Somewhat surprisingly having a function called `browser` on the search path interferes with R's command line debugging tools.

`base:: browser()` can be used, but recover mode using `options(error = recover)` does not work - I find this one really handy for jumping to the source of errors in dense code like init.R.

I'd suggest renaming the internal `browser` for future debugging convenience. Thoughts?

**Comment by renkun-ken** [comment]
Yes, it should be renamed. I'll do a PR for this.
