### ISSUE TITLE
add syntax highlight for R code in Rcpp's comment

### ISSUE THREAD

**Issue by dongzhuoer** [Ikuyadeu/vscode-R#43]
Rcpp allows to write R code in cpp block comment, like the following.

Now RStudio already support this kind of R code. I hope vscode-R can support it too.

```cpp
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
double meanC(NumericVector x) {
  int n = x.size();
  double total = 0;

  for(int i = 0; i < n; ++i) {
    total += x[i];
  }
  return total / n;
}

/*** R
library(microbenchmark)
x <- runif(1e5)
microbenchmark(
  mean(x),
  meanC(x)
)
*/
```

**Comment by Ikuyadeu** [comment]
I think it'll be supported by VS Code team.
After, I'll try to submit issue or PR to there.

**Comment by dongzhuoer** [comment]
Actually, the whole file should be a c++ source file. Maybe we should fire a issue [there](https://github.com/Microsoft/vscode-cpptools)
