### ISSUE TITLE
Request new feature: r.runFromLineToEnd

### ISSUE THREAD

**Issue by Dave-cruzz** [Ikuyadeu/vscode-R#442]
**Is your feature request related to a problem? Please describe.**
Hello, I am new to vscodeR extension. It is very good. Coming from RSTUDIO, I miss a feature for running codes from the current line to the end.

**Describe the solution you'd like**
I found a `r.runFromBeginningToLine` for running code from beginning to the current line here https://github.com/Ikuyadeu/vscode-R/blob/15dba257bac1fa098a605df526f3bee7e554a21e/src/extension.ts#L170. I would like to request a new feature and shortcut key something called `r.runFromLineToEnd` similar to `r.runFromBeginningToLine`

**Describe alternatives you've considered**
Selecting the codes using mouse and run the code. It is not convenient.

**Additional context**
None

**Comment by andycraig** [comment]
Hi @Dave-cruzz, thank you for the suggestion. Would you be interested in implementing this? The code would be similar to the code for `r.runFromBeginningToLine`:

https://github.com/Ikuyadeu/vscode-R/blob/15dba257bac1fa098a605df526f3bee7e554a21e/src/extension.ts#L128-L135

**Comment by Dave-cruzz** [comment]
Hi @andycraig thank you for the pointer. Let me have a look this or next week. I have not done any typescript language but this looks like an easy task and a good opportunity for me to learn.
