### ISSUE TITLE
The Ctrl+Enter shortcut does not work properly when a non-comment line in a function definition contains the "#" character.

### ISSUE THREAD

**Issue by altairwei** [Ikuyadeu/vscode-R#443]
**Describe the bug**
The `Ctrl+Enter` shortcut does not work properly when a non-comment line in a function contains the "#" character.

**To Reproduce**

1. Enter the following code:

    ```R
    read_data <- function(basepath) {
      matrix_loc <- Sys.glob(file.path(base_path, "*_data.csv"))
      df <- readr::read_csv(matrix_loc, comment = "#", progress = TRUE)
    }
    ```

2. Move the cursor in front of the function definition and press `Ctrl+Enter`.

3. The function cannot be entered into the R console as a whole, with the cursor resting at the beginning of the first line of the function body.

**Do you want to fix by self? (I hope your help!)**

No

**Expected behavior**
The code of function definition should be entered into the R console as a whole.

**Environment (please complete the following information):**
 - OS: Linux
 - VSCode Version: 1.50.1
 - R Version: 3.6.1
 - vscode-R version: 1.5.2

**Comment by andycraig** [comment]
Hi @altairwei, thank you for reporting this. I have reproduced it.

**Comment by renkun-ken** [comment]
Could reproduce this too.

The `extendSelection` algorithm must have treated `#", progress = TRUE)` as a comment so that the closing `)` in this line is ignored.

**Comment by andycraig** [comment]
I believe this has been fixed so I'm closing. Thanks @markbaas!
