### ISSUE TITLE
Name completion in pipe chains

### ISSUE THREAD

**Issue by andycraig** [Ikuyadeu/vscode-R#446]
Currently the session watcher provides name completion for data frame names using `$`. It would be nice if this also worked for pipe chains:

```r
mtcars %>%
    select(
```

One way to do this might be to provide the names as completion options any time there is a pipe and an unmatched `(` between the start of the pipe chain and the cursor.

For now just having completions for the variable at the start of the pipe chain would be good. Functions like `mutate` can add new columns but I don't think we need to worry about having them as completion options initially.

**Comment by renkun-ken** [comment]
Would be nice to have this.

I implemented a document-wide token completion (https://github.com/REditorSupport/languageserver/pull/324) in languageserver in an attempt to provide some partial support based on static analysis. If the columns do not appear as symbols anywhere in the document, then it does not work.

**Comment by andycraig** [comment]
Thanks for the reference @renkun-ken. Reading it I discovered that there is already an open issue for this, so I will close in favour of https://github.com/Ikuyadeu/vscode-R/issues/323
