### ISSUE TITLE
Does it work with a 32-bit version of R ?

### ISSUE THREAD

**Issue by f-leborgne** [Ikuyadeu/vscode-R#45]
Hello,

My question is in the title. I would like to know if your extension 'vs-code R' accepts a 32-bit version of R or if a 64-bit version of R is required as in RTVS.

Thanks
Florent

**Comment by Ladvien** [comment]
Underneath the hood of the extension is R itself, so long as you direct vscode-R to a 32-bit R, then the rest should work like a charm.  The R path is found in the vscode-R settings.

Just reopen if you have any issues.
