### ISSUE TITLE
Outdated README links?

### ISSUE THREAD

**Issue by pat-s** [Ikuyadeu/vscode-R#450]
The README states that this extension is based on 

- https://github.com/lee-dohm/language-r
- https://github.com/randy3k/R-Box

is this still true? Both are archived.

Maybe I just misunderstand the wording here :)

**Comment by Ikuyadeu** [comment]
@pat-s Thank you for your report.

Actually, our syntax file and interface are implemented from them.
However, currently these repositories are moved to REditor org.
I'll update the links.

**Comment by pat-s** [comment]
I think it might be wording related; I read it as "relies on/powered by" as if this ext would make use of these projects. But in fact this ext is a successor of these projects (?).

So maybe some wording wrapping this in more detail would already do it - your choice of course :)

**Comment by Ikuyadeu** [comment]
I agree with you. Our extension does not depend on these link packages.
I used "based on" as meaning "referring/respecting", but my English skill is not so good.
@pat-s  @andycraig I hope your opinion about what kind of words are better.

**Comment by renkun-ken** [comment]
Closing as the links are removed.
