### ISSUE TITLE
Add support to Python chunks in .Rmd notebooks

### ISSUE THREAD

**Issue by albersonmiranda** [Ikuyadeu/vscode-R#451]
What up guys?
Seems to me that Python chunks are currently ignored. Is that right?

![screen](https://user-images.githubusercontent.com/45690517/99864775-0127e000-2b84-11eb-93a0-9cb231078c3c.png)

**Comment by renkun-ken** [comment]
Yes, you are right. Code chunks that are not R language are ignored currently. Will it work for you if code highlighting is added to all code chunks that starts with ` ```{ ` but only R chunks have the run commands shown above the chunk?

**Comment by albersonmiranda** [comment]
Absolutely!

**Comment by albersonmiranda** [comment]
Awesome!

just one little question: how does publishing works? Since all actions finished running, should it be available in marketplace by now or you guys doing it manually? I'm kinda anxious to test it lol

**Comment by renkun-ken** [comment]
Auto release (#449) is not merged yet. To test the latest dev, you could go to <https://github.com/Ikuyadeu/vscode-R/actions> and find the latest build at <https://github.com/Ikuyadeu/vscode-R/actions/runs/378046002>, and download the artifact, and install it in vscode.
