### ISSUE TITLE
Place cursor on the end of the line or next line

### ISSUE THREAD

**Issue by stanleesocca** [Ikuyadeu/vscode-R#452]
Hi 

Thanks for the work so far. I was wondering if vscode R can always place the cursor prompt at the end of the line once it have been executed or better yet move to the next line of code (just like rstudio). For some reason, my vscode R editor, fails to do that (always placing the cursor at the beginning of the line after running code. Weird).  

Hope my raised issue clear enough. Thanks for the amazing work. 

Stanley

**Comment by andycraig** [comment]
Hi @stanleesocca, thank you for using vscode-R and thank you for the suggestion.

Moving the cursor prompt to the end of the line would have the disadvantage that pressing <kbd>Ctrl+Enter</kbd> twice would run the same code twice. I agree that moving to the next line of code would be good.

**Comment by renkun-ken** [comment]
Not sure if I'm understanding the request correctly. Isn't that we already have?

**Comment by andycraig** [comment]
@renkun-ken Here's my understanding of the request. 
```r
x <- 1 # Cursor on this line, Ctrl+Enter
# Current behaviour: cursor moves to start of this line

y <- 2 # Requested behaviour: cursor moves to start of this line
```

@stanleesocca Please correct me if I've misunderstood.

**Comment by stanleesocca** [comment]
Thanks for reply @renkun-ken  and @andycraig. Yes, @andycraig that exactly my issue. I would imagine it will be handy since one don't have to keep manually placing the cursor every time at the beginning of a new line. 

@andycraig Yes, I agree with your point that the risk of running the code twice exist, but that in many case such isn't much of a big deal. Great work you guy are doing.

Once again, apologies for my late response. I've been dealing grad school work.

**Comment by andycraig** [comment]
@stanleesocca When you use <kdb>Ctrl+Enter</kbd> it should run the next block of code, so if you just want to run code you shouldn't need to manually move the cursor.

Not sure if it helps for your use case but there's also a command `R: Run Selection/Line (Retain Cursor)` which runs the next block of code without moving the cursor.

**Comment by stanleesocca** [comment]
Thanks @andycraig Sure Ctrl+Enter work and place Alt+Enter can do with the retain cursor. Maybe I just asking to much with the option of placing cursor to the end.  One more thing, will vscode-r ever have a built-in dataframe viewer? 

In any case, I can't emphasize how great a work you guys are doing.

**Comment by kar9222** [comment]
>  will vscode-r ever have a built-in dataframe viewer?

@stanleesocca You can enable "session watcher" to e.g. `View(iris)`. See [Writing R in VSCode: Interacting with an R session](https://renkun.me/2019/12/26/writing-r-in-vscode-interacting-with-an-r-session/) for many more features that comes with "session watcher".

**Comment by stanleesocca** [comment]
Thanks @kar9222 . @renkun-ken @andycraig The session watcher feature is awesome. Any idea if the feature will keep being "experimental"? I think it is a solid feature that is hidden (at least for me).

**Comment by renkun-ken** [comment]
Closing as resolved.
