### ISSUE TITLE
Help View: Blank Window

### ISSUE THREAD

**Issue by pat-s** [Ikuyadeu/vscode-R#454]
Hi guys,

very enthusiastic about the new help view.
However, currently I only get a blank window when opening any help page.
I have set `r.helpPanel.rpath` to vanilla R but this does not change anything.
I did not find anything in the dev tools pane.

Also I think `r.helpPanel.rpath` needs to be documented top-level or set to a reasonable default? 
Many peope have set the R interpreter to `radian` and will not know that they need to set the vanilla R path again explicitly here (I only saw this browsing the PR).

Would it make sense to set it to the default `$R_HOME/bin/R` for each OS?

**Comment by renkun-ken** [comment]
No need to set `r.helpPanel.rpath` if you type `?something` to show help viewer. It works on top of session watcher that works with the current session you are running by default. Only the `R: Show help` command will spawn a standalone R process to provide help. Which way do you use and you get a blank page?

If you are using `R: Show help`, then there might be something wrong there. Please try using `?something` in an attached R session.

If you are using `?something`, then something is wrong resolving the help file paths. You might revert to the old behavior via `options(vsc.helpPanel = FALSE)`.

@ManuelHentschel any idea on this?

**Comment by renkun-ken** [comment]
Are you setting `r.rterm.*` to radian?

@ManuelHentschel I think `r.helpPanel.rpath` should not default to `r.rterm.*` as many users are using radian as we recommend, the help panel won't work then. It should default to `getRpath()` instead if not specified.

**Comment by renkun-ken** [comment]
#455 might be the same problem.

**Comment by ManuelHentschel** [comment]
Looks like there was a typo when accessing the config entry `r.helpPanel.rpath`

**Comment by ManuelHentschel** [comment]
> @ManuelHentschel I think `r.helpPanel.rpath` should not default to `r.rterm.*` as many users are using radian as we recommend, the help panel won't work then. It should default to `getRpath()` instead if not specified.

It does default to `getRpath()` [already](https://github.com/Ikuyadeu/vscode-R/blob/master/src/extension.ts#L53), but maybe we should change that function so that the help panel never uses the `r.rterm.*` setting

**Comment by renkun-ken** [comment]
@pat-s Would you like to install the latest build at https://github.com/Ikuyadeu/vscode-R/actions/runs/377371651 and see if it works for you?

**Comment by pat-s** [comment]
Works!
