### ISSUE TITLE
As of vscode-R 1.6.0 I cannot see help files

### ISSUE THREAD

**Issue by nathaneastwood** [Ikuyadeu/vscode-R#455]
I have the latest versions of vscode-R (v1.6.0) and {languageserver} (v0.3.7) on the latest VSCode (v1.51.1) on MacOS 19.6.0. If I type into the console `?rnorm`, as an example, I just see a black tab with nothing displayed there.

These are my current settings:

```json
  "r.rterm.mac": "/usr/local/bin/radian",
  "r.rterm.option": [""],
  "r.bracketedPaste": true,
  "r.sessionWatcher": true,
  "r.lsp.debug": true,
  "r.lsp.diagnostics": true,
  "r.alwaysUseActiveTerminal": true,
```

<img width="585" alt="Screenshot 2020-11-22 at 09 38 45" src="https://user-images.githubusercontent.com/9799530/99899056-91f6dc80-2ca6-11eb-8340-5efb192e7958.png">

**Comment by renkun-ken** [comment]
You might use `options(vsc.helpPanel = FALSE)` to disable the help panel at the moment.

@ManuelHentschel any idea on this?

**Comment by renkun-ken** [comment]
Looks like setting `r.helpPanel.rpath` does not have any effect.

If I set

```json
"r.rterm.mac": "/usr/local/bin/radian",
"r.helpPanel.rpath": "/usr/local/bin/R"
```

it won't work either. and

```json
"r.rterm.mac": "",
"r.helpPanel.rpath": "/something/not/exists"
```

works.

Looks like `r.helpPanel.rpath` is ignored/not used at all. It will always default to `r.rterm.mac`.

**Comment by nathaneastwood** [comment]
Interestingly, if I `devtools::load_all()` and then look at the help file, it will load the development help file in my internet browser.

**Comment by ManuelHentschel** [comment]
`load_all` attaches an environment `devtools_shims` which contains a modified version of `help` that is not affected by the overwrites from `init.R`:
```
> devtools::load_all()
Loading RTestPackage
> search()
 [1] ".GlobalEnv"           "devtools_shims"       "package:RTestPackage"
...
```

**Comment by renkun-ken** [comment]
@nathaneastwood Would you like to install the latest build at https://github.com/Ikuyadeu/vscode-R/actions/runs/377371651 and see if it works for you?

**Comment by nathaneastwood** [comment]
I installed the extension from the vsix and can confirm it works! Thanks very much to all for your quick response to this issue.
