### ISSUE TITLE
r session watcher does not open the "View-Objects" inside of VSC anymore with V 1.6.0

### ISSUE THREAD

**Issue by Pindar777** [Ikuyadeu/vscode-R#458]
As the r.sessionwatcher feature is experimental I'd like to point out that with V 1.6.0 (all of a sudden) the session watcher changed it's behavior and opens separate "R windows" instead of showing the content next to the script inside VSC.

I'm using ikuyadeu.r in 1.6.0 and VSC in Version: 1.51.1 (user setup) on Windows_NT x64 10.0.19042

**Comment by renkun-ken** [comment]
Might be related to #455 where session watcher script is not sourced due to error on extension activation.

Would you like to install the latest build at https://github.com/Ikuyadeu/vscode-R/actions/runs/377371651 and see if the issue still persists?

**Comment by renkun-ken** [comment]
Closing as fixed by #456 that stops extension activation if no workspace folder is open.

**Comment by Pindar777** [comment]
@renkun-ken Thanks for your fast response and the fix. 1.6.1 works like a charm.
