### ISSUE TITLE
Suggestion: Change R terminal to distinguishable name

### ISSUE THREAD

**Issue by MilesMcBain** [Ikuyadeu/vscode-R#46]
Love this extension :)

I have found myself using multiple R terminals in VSCode. The most common case is when I want to use one to lookup documentation while I work out how to use a particular R function.

I would like to suggest that the main R terminal used by this extension be given a special name so it is easy to distinguish from other R terminals the user might have opened. Something like "R Session" or "R Workspace" maybe?

Should be a small change to here: https://github.com/Ikuyadeu/vscode-R/blob/master/src/rTerminal.ts#L9

**Comment by Ikuyadeu** [comment]
@MilesMcBain Thank you for your love and suggestion.
In 65af6a8, I changed R term name to "R Interactive", it is same of RTVS.
