### ISSUE TITLE
All variables by environment viewer

### ISSUE THREAD

**Issue by Ikuyadeu** [Ikuyadeu/vscode-R#47]
From #23 

Is there an environment variable viewer in your extension in which we could see all the variables created in R and their values like in R studio?
![image](https://user-images.githubusercontent.com/32433180/35393579-a5c7a6d4-01e5-11e8-8b65-e91fa18f4fef.png)
----------------------------------------------

I think it is not so difficult.
If other users want to this function, I'll implement.

**Comment by jacob-long** [comment]
I think this would be great and would be an important step for a lot of RStudio converts.

**Comment by hfberg** [comment]
Hi! Any news on a variable viewer? Is there a way to view the variables? This is a huge issue for me, I have intricate objects and I need to be able to view them. So far I haven't run across a command/ option to open this variable viewer in the R extension for VS code. If this is not fixed i will have to change back into RStudio. :(:(:(

**Comment by wleoncio** [comment]
A primitive implementation of this would be to have a panel that calls `ls.str()` when a change in the environment is detected. Perhaps even a keyboard shortcut for that function will do at first.

**Comment by andycraig** [comment]
Hi @wleoncio, thank you for your suggestions. Their is a command `R: Preview Environment` that can be called to display a simple summary of the environment (although it seems to have some problems at the moment: #92).

Detecting a change in the environment is tricky as vscode-R has to send text to the console to communicate with the R session.

**Comment by wleoncio** [comment]
Oh, so _that's_ what "Preview Environment" does! I've tried that command in the past, but for whatever reason I couldn't figure out what I was looking at (don't ask). Anyway, TIL, thanks!

**Comment by andycraig** [comment]
Hi @Ikuyadeu, I’m closing this issue because I think the `R: Preview Environment` command provides this functionality. Please reopen if there are still features that need to be added. Thank you!

**Comment by Ikuyadeu** [comment]
@andycraig Ok, Thank you for your managing!
