### ISSUE TITLE
better language highlight for Rmd

### ISSUE THREAD

**Issue by dongzhuoer** [Ikuyadeu/vscode-R#48]
The current support for R markdown language highlight is awesome. While I think the following aspects are overweighted by VScode's native markdown support.

highlight for Rmd
![image](https://user-images.githubusercontent.com/15871952/35514921-b8536210-0542-11e8-85d8-0c844fe8b750.png)

highlight for md
![image](https://user-images.githubusercontent.com/15871952/35514958-d20f239c-0542-11e8-9593-0842f4cb6fff.png)

```md
1. item

- item

+ item

* item

> Blockquotes

`inline code`
```

**Comment by dongzhuoer** [comment]
Other feature I desired is to support [Block content in list items](https://pandoc.org/MANUAL.html#block-content-in-list-items). I think this feature is reasonable since Rmd heavily relies on Pandoc.

Current the block content rendered as text code, so the markdown highlight is lost.

One problem is that after pandoc 2.0, **four space rule** is replaced by **CommonMark variable nesting rules**. (https://github.com/jgm/pandoc/issues/3511  and search `#3511` in https://pandoc.org/releases.html#pandoc-2.0.1-31-october-2017). Maybe you can add an option.

**Comment by Ikuyadeu** [comment]
Looks Good! I added as my TODO.
However if you will contribute this, I'll be happy.

**Comment by dongzhuoer** [comment]
Thanks, but I'm afraid I don't have the ability. I'm not familiar with VSCode extension, moreever, I have problems build VSCode form source.

Anyway, I'd like to provide some suggestions. Since VSCode's built in support for Markdown highlight is quite nice, what about adding some new rules (inline code `` `r code` `` and block code) rather than implement a whole language highlight from scratch.
