### ISSUE TITLE
Have to press ctrl+enter two times to "Run Command in Terminal" when set to radian

### ISSUE THREAD

**Issue by jooyoungseo** [Ikuyadeu/vscode-R#483]
- VSCode Version: 
  Version: 1.52.0-insider (system setup)
  Commit: ac165d7f974d70212be80cb15eaecfc1fd20b21a
  Date: 2020-11-30T17:36:25.607Z
  Electron: 11.0.2
  Chrome: 87.0.4280.63
  Node.js: 12.18.3
  V8: 8.7.220.24-electron.0
  OS: Windows_NT x64 10.0.19042

- VSCode-R Version: 1.6.1
- OS Version: Windows 10

Steps to Reproduce:

1. Set `radian` as your default Rterm.
1. Press `CTRL+Enter` on any selected R command to `Run Command in Terminal`.

Unlike `R.exe`, for radian we need to press `CTRL+Enter` two times (first one just opens radian in terminal; second one sends command to the console).

Do you want to fix by self? (I hope your help!)

No

My `settings.json` is like below:

``` json
{
    "r.sessionWatcher": true,
    "r.rterm.windows": "C:/ProgramData/Miniconda3/Scripts/radian.exe",
    "r.bracketedPaste": true,
    "r.rterm.option": [
        "--no-save",
        "--no-restore",
        "-q"
    ],
    "r.source.focus": "terminal",
    "r.lsp.path": "C:/program files/R/R-4.0.3/bin/x64/R.exe",
    "r.lsp.debug": true
}
```

**Comment by nwillems94** [comment]
I have the same issue when no terminal is active, and it seems to be new. 

Quickly hitting `ctrl+enter` twice will send only part of the selected code
