### ISSUE TITLE
Addin picker sorting

### ISSUE THREAD

**Issue by ElianHugh** [Ikuyadeu/vscode-R#489]
**Is your feature request related to a problem? Please describe.**
I'm not sure if this is a bug or a feature request but... Sometimes I'm interested in using an addin, but I don't know what the commands it use are. Searching for the addin _does_ highlight the addin, but doesn't put the result at the top of the picker.

E.g.
![image](https://user-images.githubusercontent.com/60372411/101719752-dbfc0280-3a9b-11eb-9e43-71617717b361.png)

**Describe the solution you'd like**
Ideally, we would put the addin results at the top of the picker. 

If people are interested, I could look into fixing this.

**Comment by renkun-ken** [comment]
I could reproduce this. It looks like the only a match with pick item label will sort the list and the matched items are put on top while a match on other parts (decription `{package}`, detail) is merely highlighted and will not trigger re-sorting.
