### ISSUE TITLE
Save before Run Source

### ISSUE THREAD

**Issue by michaelHL** [Ikuyadeu/vscode-R#5]
- Great extension! It's annoying that I can't see any changes after sourcing the `R` code and only find I just don't save my edited file. 
- And it would be better if you provide an option whether keeping focus on the editor or the terminal area (Just like RStudio)~

**Comment by Ikuyadeu** [comment]
@michaelHL Thank you for your good issues.
I'll fix them in next week.

**Comment by michaelHL** [comment]
@Ikuyadeu Yep! That's also me.:smile:

**Comment by Ikuyadeu** [comment]
@michaelHL  Now I fixed two problems new version!

**Comment by michaelHL** [comment]
@Ikuyadeu Glad to see that! I like it even more😉
