### ISSUE TITLE
ctrl+c

### ISSUE THREAD

**Issue by edult** [Ikuyadeu/vscode-R#50]
is there a way to stop ctrl+C from exiting the R terminal? In RStudio it just deletes the line which is more desirable than turning of the whole terminal

**Comment by Ikuyadeu** [comment]
@edult Thank you for an issue and sorry for late reply.
This problem looks difficult for fixing or stable.
I'll decide to fix or not by other users suggestion.

**Comment by andycraig** [comment]
This isn't a universal issue - for me, Ctrl-C just deletes the line as it does in RStudio.

**Comment by Ladvien** [comment]
@edult I'm curious what OS you're running?  I've tested on Mac and will test on Linux later today (but I'm guessing it will be the same as Mac).  Anyways, CTRL-C on in vscode-R on the Mac drops down to a new line without executing the current line in the R terminal.

However, I've a sneaky suspicion you are on Windows, where I'd guess the behavior is different.

**Comment by andycraig** [comment]
Hi @edult, I’m revisiting some old issues. Does this problem still occur for you? If so, does it also occur when you use a R in a normal terminal (not in VSCode)?

Thank you.

**Comment by andycraig** [comment]
It sounds like this is probably an R issue rather than a vscode-R issue: https://stackoverflow.com/questions/48748076/ctrlc-exits-r-in-windows

I am going to close it, but please post if you don't consider it resolved.
