### ISSUE TITLE
Unable to see WebView buttons when running Shiny app

### ISSUE THREAD

**Issue by rpodcast** [Ikuyadeu/vscode-R#501]
**Describe the bug**

I wanted to try the new browser WebView command buttons that were recently added via PR #494 in a remote container session, but I do not see the buttons appear in the VS-Code UI when running a shiny application

**To Reproduce**
1. Create a development environment container for VS-Code using a custom `.devcontainer/devcontainer.json` and `DockerFile` such as the configuration in [this GitHub repository](https://github.com/rpodcast/r_dev_projects/tree/master/.devcontainer)
2. If not present, install the `shiny` package and run the example application in an R terminal via `shiny::runExample("01_hello")`
3  View the tab of the application which only shows two buttons (default to split to side view and the "...")

**Do you want to fix by self? (I hope your help!)**

I would be glad to help troubleshoot further but I don't have enough expertise to fix myself

**Expected behavior**

Ability to refresh webview and open in external browser with new buttons

**Screenshots**

![2020-12-22_00-09](https://user-images.githubusercontent.com/1043111/102851750-a1269280-43ea-11eb-8b9d-1d0d1d8932e5.png)

**Environment (please complete the following information):**
 - OS:  Linux Ubuntu 20.04
 - VSCode Version: 1.52.1 (snap package)
 - R Version: 4.0.2 (running in development docker container)
 - vscode-R version: 1.6.2 (installed in remote session)

**Additional context**

It was not clear to me if I was supposed to set any new configuration options either in the extension or within the `languageserver` package itself.

**Comment by renkun-ken** [comment]
Could you confirm that you installed the latest development build in the remote session?

**Comment by rpodcast** [comment]
That indeed was the issue.  I had assumed incorrectly that this was part of the latest version in the extension marketplace.  I had to look up how to install a development `.vsix` version of an extension but found this [post](https://stackoverflow.com/questions/56055183/how-can-i-install-a-vsix-file-based-extension-in-a-remote-container-via-devconta) on how to pull it off.  After rebuiliding the container I can see the buttons without a problem.  We can close this.  Just for my understanding, how do we tell if the version available on the marketplace is behind the current GitHub version?

**Comment by ManuelHentschel** [comment]
>  Just for my understanding, how do we tell if the version available on the marketplace is behind the current GitHub version?

Ideally, the latest release in the [releases section](https://github.com/Ikuyadeu/vscode-R/releases) is identical to the marketplace release. There you can also view the [commits to master](https://github.com/Ikuyadeu/vscode-R/compare/v1.6.2...master) since the release and check if something relevant changed.

Currently the GitHub release action is not happening (completely) automatically, so the last release wasn't released on github in time.
I'll open a separate Issue/PR to address this and hopefully the next releases will be mirrored on GitHub automatically.
