### ISSUE TITLE
GitHub Releases

### ISSUE THREAD

**Issue by ManuelHentschel** [Ikuyadeu/vscode-R#503]
We currently have a GitHub [action](https://github.com/Ikuyadeu/vscode-R/blob/master/.github/workflows/release.yml) that prepares a release draft, when a tag matching `v*` is pushed.

Modifying the action to actually publish the release instead of drafting can easily be done, but this still requries the corresponding tag to be pushed.

@Ikuyadeu, would you be ok with tagging the releases you publish to the marketplace to make sure they are also released to GitHub? In principle, this can be done by any collaborator, but the safest way would be to do this at the same time as releasing to the marketplace.

Two alternatives would be:
1. We also automate the release to the marketplace, as done e.g. [here](https://github.com/ManuelHentschel/vscode-github-linker/blob/master/.github/workflows/release.yml#L49:L61). This would make it possible to simultaneously release to the marketplace and GitHub by pushing a single tag
2. After each push, we check if the version changed and automatically tag and release the commit containing the version change. This might be a bit cumbersome to implement, since we'd need to compare a number of different commits to tag the correct one, and lead to another workflow running on each push.

I'd prefer alternative 1 or sticking with the current action (with the modification that releases are published, not just drafted), what are your thoughts on this?

**Comment by Ikuyadeu** [comment]
@ManuelHentschel Thank you for your opinions. And sorry for my few participating.
I feel 1 is good, it can be safe if I got an accident.
This repo management discussion is still in progress. We should use the auto-publish at this time.
