### ISSUE TITLE
Show Call Hierarchy should work for R

### ISSUE THREAD

**Issue by jooyoungseo** [Ikuyadeu/vscode-R#509]
Currently, "Show Call Hierarchy" (Shift+Alt+H) does not work for R.

Do you have any plan to support this feature?

Many thanks!

**Comment by renkun-ken** [comment]
The [Call Hierarchy](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_prepareCallHierarchy) feature requires R code analysis. It is better implemented in [languageserver](https://github.com/REditorSupport/languageserver) which does the actual R code analysis.
