### ISSUE TITLE
R Workspace sidebar panel pane stays empty

### ISSUE THREAD

**Issue by gwd999** [Ikuyadeu/vscode-R#519]
**Describe the bug**
R Workspace stays empty 

**To Reproduce**
1. Install R VS Code extension 
2. Enable Session Watcher 
3. Restart VS Code 
4. after loading tidyverse - create a sample data.frame object 
5. create a sample ggplot object 
6. R workspace stays empty  

**Do you want to fix by self? (I hope your help!)**

No - b/c of lack of electron (and js/ts) experience  

**(If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)**

(If related)setting.json

```json

    "r.alwaysUseActiveTerminal": true,
    "r.linting.pascalCase": false,
    "r.linting.camelCase": false,
    "r.linting.enable": true,
    "r.linting.nameLength": true,
    "r.editor.bracesOnNewLine": true,
    "r.editor.tabSize": 4,
    "r.rpath.windows": "C:\\R\\R-4.0.3\\bin\\x64\\R.exe",
    "r.rterm.windows": "C:\\R\\R-4.0.3\\bin\\x64\\Rterm.exe",
    "r.rterm.option": [
        "--no-save",
        "--no-restore-data"
    ],
    "r.rterm.linux": "/usr/bin/R",
    "r.rpath.linux": "/usr/bin/R",
    "r.workspaceViewer.removeHiddenItems": true,
    "r.sessionWatcher": true

```

**Expected behavior**
Seeing R objects in the WORKSPACE sidebar panel window 

**Screenshots**

![image](https://user-images.githubusercontent.com/306826/103676602-8f63f400-4f81-11eb-8a2b-20660c2e34ab.png)

**Environment (please complete the following information):**
 - OS: Windows 10 
 - VSCode Version: 1.52.1 
 - R Version: 4.0.3 (as well as 3.6.3)
 - vscode-R version:  1.6.3 (the one from VS Code extension marketplace)

**Additional context**
Help Pages, Save and Load workspace and Clear env all work w/o any issues. 

I have added the globalenv.json as .txt as well - that also looks fine 
[globalenv.txt](https://github.com/Ikuyadeu/vscode-R/files/5771561/globalenv.txt)

**Comment by ElianHugh** [comment]
I haven't been able to replicate this on Windows 10 or WSL (Ubuntu) using vscode-R 1.6.3 and R 4.0. 

![image](https://user-images.githubusercontent.com/60372411/103735359-d1268600-4fe5-11eb-8b32-afa7ce2cb69a.png)

Your globalenv file looks okay, which is odd considering the bug. The workspace viewer should have the data passed to it during the [updateGlobalEnv] command, so there could be an issue there. A possibility is that the globalenv file path isn't being passed to your session properly. Does View(globalenv()) work?

**Comment by gwd666** [comment]
Not sure but am I missing some setup thing?  Just asking b/c the workspace neither works on my home nor on my job PC?

**Comment by gwd666** [comment]
Update ... I managed my WORK VSC R extension with "session watcher" feature to work as defined. 
Seems that the two Windows R and Rterm paths were not the same (I think I mixed up i386 and x64 paths) in there and that maybe caused issues. 
`View(globalenv())` still does not show anything but the other features are working now - a bit slow every now and then BUT they work! So GREAT!         
SO what I am left with now os the HOME PC Windows10 VSC R extension session watcher. 
Which brings me to the IMPORTANT question - I have a custom .libPath() pointing to my D drive -> CAN THIS CAUSE ISSUES with the extension?

**Comment by gwd999** [comment]
Not sure but am I missing some setup thing?  Just asking b/c the workspace neither works on my home nor on my job PC? 
I do have a custom .Rprofile I am using on both machines ... but when I deactivate that -> also the same result. 
      
BUT!!!! On WSL2 on my home machine it worked TEMPORARILY ... thanks for giving me that idea, since you mentioned it working on yr WSL. 
BUT View(globalenv()) only showed a white canvas; same happened when I looking at a data.frame object (ie when I click on the View icon next to a data.frame in the R Workspace), functions and vectors in the R-workspace will showed up "nice" AND in my "native" WINDOWS 10 VSC sessions ON MY HOME PC nothing happens when issuing the `View(globalenv())` command BUT on my WORK PC it tells me that you cannot coerce class  "environment" to a data.frame, so again differing behavior - difference being that at WORK I use R-3.6.3 at HOME I use R-4.0.3 on WIN10 (switching versions from 4.0.3 to 3.6.3 on HOME PC did not solve it either, I tried that as well) and R-3.6.3 on WSL2 (Ubuntu 20.04).   
     
Hope the cause is only some setting since the extension is really awesome! 
So is there is something in the Windows VSC settings regarding where commands are sent to for R extension that is not as it should be - any idea where I could maybe check?     
Like I said it worked only temporarily - after a couple of fresh restarts using projects on different folders - all is back to EMPTY workspaces again.

**Comment by gwd999** [comment]
UPDATE from my side - just to be clear the extension does work sometimes; and I think it is really cool and useful but it randomly quits on me ... and I have not been able to identify under which circumstances it will populate the workspace and when it will not

**Comment by korilium** [comment]
I have the same issue. Hopefully, this will be solved in the near future.

**Comment by ElianHugh** [comment]
Sorry, I lost track of this! Would you be able to run `ls.str(.vsc)` and post the output?

**Comment by korilium** [comment]
I have fixed the issue on my side by deleting the setting.json and reinstalling the extensions of R. 
here is the output for `ls.str(.vsc)`. 

`r$> ls.str(.vsc)
attach : function ()
capture_str : function (object)
check_null_dev : function ()
dataview_data_type : function (x)
dataview_table : function (data)
dir_extension :  chr "C:\\Users\\ignac/.vscode-R"
dir_plot_history :  chr "C:\\Users\\ignac\\AppData\\Local\\Temp\\RtmpCUiaMC/vscode-R/images"
dir_session :  chr "C:\\Users\\ignac\\AppData\\Local\\Temp\\RtmpCUiaMC/vscode-R"
get_timestamp : function ()
globalenv_file :  chr "C:\\Users\\ignac\\AppData\\Local\\Temp\\RtmpCUiaMC/vscode-R/globalenv.json"
globalenv_lock_file :  chr "C:\\Users\\ignac\\AppData\\Local\\Temp\\RtmpCUiaMC/vscode-R/globalenv.lock"
homedir :  chr "C:\\Users\\ignac"
inspect_env : function (env)
new_plot : function ()
null_dev_id :  Named int 2
null_dev_size :  num [1:2] 10.1 10.1
path_to_uri : function (path)
pid :  int 14528
plot_file :  chr "C:\\Users\\ignac\\AppData\\Local\\Temp\\RtmpCUiaMC/vscode-R/plot.png"
plot_history_file :  chr "C:\\Users\\ignac\\AppData\\Local\\Temp\\RtmpCUiaMC/vscode-R/images/20210311-083158.399280.png"
plot_lock_file :  chr "C:\\Users\\ignac\\AppData\\Local\\Temp\\RtmpCUiaMC/vscode-R/plot.lock"
plot_updated :  logi FALSE
print.help_files_with_topic : function (h, ...)
print.hsearch : function (x, ...)
rebind : function (sym, value, ns)
request : function (command, ...)
request_browser : function (url, title, ..., viewer)
request_file :  chr "C:\\Users\\ignac/.vscode-R/request.log"
request_lock_file :  chr "C:\\Users\\ignac/.vscode-R/request.lock"
rstudioapi_enabled : function ()
show_browser : function (url, title = url, ..., viewer = getOption("vsc.browser", "Active"))
show_dataview : function (x, title, viewer = getOption("vsc.view", "Two"))
show_globalenv :  logi TRUE
show_page_viewer : function (url, title = NULL, ..., viewer = getOption("vsc.page_viewer", "Active"))
show_plot :  logi TRUE
show_view :  logi TRUE
show_viewer : function (url, title = NULL, ..., viewer = getOption("vsc.viewer", "Two"))
show_webview : function (url, title, ..., viewer)  
tempdir :  chr "C:\\Users\\ignac\\AppData\\Local\\Temp\\RtmpCUiaMC"
unbox : function (x)
update_globalenv : function (...)
update_plot : function (...)
wd :  chr "C:/Users/ignac/Documents/Kuleuven/advance_analyticals_in_Business"`

**Comment by ElianHugh** [comment]
> I have fixed the issue on my side by deleting the setting.json and reinstalling the extensions of R. 

That's good to hear! If resetting the json worked, then it sounds like it may have been an issue with the rTerm or rPath setting

**Comment by gwd999** [comment]
@korilium - did i remove the whole settings.json file or did you just remove selectively some lines and @ElianHugh when you say "may have been issues with the rTerm or rPath" could you maybe elaborate if a certain procedure of removing some lines in the settings.json and uninstalling and reinstalling the extension could verify that; I guess this could be interesting to verify to adopt the extension installation or update process accordingly; will give it a couple of days to hear from you before I do a brute force on it like korilium

**Comment by korilium** [comment]
sorry totally forgot about it and yes I did remove the whole setting.json file
