### ISSUE TITLE
Display promise / active-binding objects in the OUTLINE

### ISSUE THREAD

**Issue by shrektan** [Ikuyadeu/vscode-R#522]
**Is your feature request related to a problem? Please describe.**

Promise and Active binding objects are not displayed in the OUTLINE

**Describe the solution you'd like**

Would be great to have them in the OUTLINE.

Considering the following test file: 

**test.R**

```r
x <- 1
y <- "a"
z <- function() {
  'hello'
}
delayedAssign("d", 1)
delayedAssign("err", stop("err"))
makeActiveBinding("a1", function() 1, environment())
```

Currently, only `x`, `y` and `z` are displayed in the OUTLINE but `d`, `err` and `a1` don't. I hope we can have them in the OUTLINE, too.

![image](https://user-images.githubusercontent.com/8368933/103998998-69379180-51d7-11eb-9aab-e435454fe10c.png)

**Comment by renkun-ken** [comment]
Document outline is provided by languageserver using parsed data. You might want to raise issue [there](https://github.com/REditorSupport/languageserver/issues).

**Comment by shrektan** [comment]
Opened at REditorSupport/languageserver#362
