### ISSUE TITLE
Ctrl + Enter inspects function instead of running on radian

### ISSUE THREAD

**Issue by danielbasso** [Ikuyadeu/vscode-R#523]
I can be missing something very obvious, or I simply don't know how the extension works. Whenever I hit ctrl + enter, instead of running the line on radian, vscode opens a new pane with the function code, kind like an "inspect function" command. If I hit f1, then ctrl + enter, it works normal. Is this the intended way or there is something to configure? . I just have this and R Lsp client extension installed.

Image 1: ctrl+ enter opens "inspect function" tab

![image](https://user-images.githubusercontent.com/20959177/104528168-40ebd080-55e5-11eb-9c2f-0029ea4fcc89.png)

Image 2 and 3: f1, then ctrl + enter works like I expected

![image](https://user-images.githubusercontent.com/20959177/104528214-64af1680-55e5-11eb-9d0f-56794d34eddc.png)

![image](https://user-images.githubusercontent.com/20959177/104528248-7ee8f480-55e5-11eb-8c09-f1871db5504d.png)
 

Settings file:

`"r.bracketedPaste": true,
"r.rterm.linux": "/usr/local/bin/radian",
"r.lsp.debug": true,
"r.lsp.diagnostics": true,
"r.rpath.linux": "/usr/bin/R",
"r.sessionWatcher": true,
"files.associations": {
   "*.rmd": "markdown"
}`

**Comment by renkun-ken** [comment]
Looks like you set Ctrl + Enter to "Go To Definition" in the key bindings. You could go to Keyboard shortcuts and search "ctrl+enter" and see if it is set up to other commands in editor.

Mine is 

<img width="1726" alt="image" src="https://user-images.githubusercontent.com/4662568/104531461-2ba88d80-5649-11eb-9d76-72151be230b4.png">

**Comment by danielbasso** [comment]
Hey @renkun-ken, thanks for your reply. Like you said, I suspected that another "ctrl + enter" was taking precedence above "Run Selection/Line". The curious thing is that this only happens when R extension is installed. If it isn't installed, then "ctrl + enter" execute "Insert Line Below", so at least the R extension is changing the default behavior, which is odd. 

Take a look at my keyboard shortcuts, by order of precedence:

![image](https://user-images.githubusercontent.com/20959177/104589848-3bc06d00-5649-11eb-8b84-dc4205a46a78.png)

Maybe the command that is being executed is "openReferenceToSide", since "referenceSearchVisible" may return true after the R extension is installed. This could be the source of confusion, because it explains why this behavior happens only after the extension is present. 

I tried to change this order, with no success. There is a `keybindings.json` file under /home/user/.config/Code/User folder. Mine is empty, so I can't use it to change the order of precedence.

**Comment by danielbasso** [comment]
Ok, so I couldn't find any way to tell vscode to change the order of precedence of shortcuts. Ended up editing my `settings.json` file and adding these lines:

```
[
    {
        "key": "ctrl+enter",
        "command": "r.runSelection",
        "when": "editorTextFocus && editorLangId == 'rmd'"
    },

    {
        "key": "ctrl+enter",
        "command": "r.runSelection",
        "when": "editorTextFocus && editorLangId == 'r'"
    }
]
```

Vscode now has a duplicate entry from both commands, but it places user commands above everything else:

![image](https://user-images.githubusercontent.com/20959177/104677263-e4151680-56c7-11eb-9b3c-64132be5b514.png)


It's a strange solution, but I'm ok with that. Sorry for posting this as an issue with the extension, but I really needed help and couldn't find anywhere else.
