### ISSUE TITLE
Add Update Packages to help pages viewer

### ISSUE THREAD

**Issue by renkun-ken** [Ikuyadeu/vscode-R#529]
Now we have the following commands in the help viewer

<img width="243" alt="image" src="https://user-images.githubusercontent.com/4662568/105271728-fe248c80-5bd2-11eb-9d4a-a303b654c987.png">

Does it make sense to add "Update packages" command?

**Comment by Ikuyadeu** [comment]
At least adding the function will not be a problem, but it's better to create it under the package tree for the future.

**Comment by Ikuyadeu** [comment]
Fixed by #532
