### ISSUE TITLE
How to use this package in Windows?

### ISSUE THREAD

**Issue by ShixiangWang** [Ikuyadeu/vscode-R#53]
- VSCode Version: 1.20.1
- VSCode-R Version: 0.5.4
- OS Version: Windows 7

Hello,

This package's feature you show is awesome, but I cannot use it on my Windows 7. I use conda to manage my R packages, so I have to change the R location, but it fails.

I use cmd to confirm my R location is right.
 
![image](https://user-images.githubusercontent.com/25057508/36887764-9cafd8be-1e2d-11e8-8aa5-14c62c2135e7.png)

And I add the location to VS code in setting.

![image](https://user-images.githubusercontent.com/25057508/36887827-d816843e-1e2d-11e8-9167-a6d35d4e3031.png)

When I run R in VS code

![image](https://user-images.githubusercontent.com/25057508/36887858-f6df99fa-1e2d-11e8-89c4-e0621584e549.png)

![image](https://user-images.githubusercontent.com/25057508/36887897-209f2530-1e2e-11e8-9be0-1006f40b6467.png)

![image](https://user-images.githubusercontent.com/25057508/36887909-2cd4f4ec-1e2e-11e8-9522-e568d9414357.png)

BTW, I love your font show in 

![image](https://user-images.githubusercontent.com/25057508/36887935-51a2a954-1e2e-11e8-934e-b7e387ac2a77.png)

What's name of this font?

Thanks.

**Comment by Ikuyadeu** [comment]
@ShixiangWang Thank you for the issue and using!
First, you can use this extension on the folder, please open your folder that has `.r` file.

Font: 
If you say about logo it is published on https://www.r-project.org/logo/
If it is source code font, you can check default setting `editor.fontFamily`
