### ISSUE TITLE
"R path for macOS" Invalid

### ISSUE THREAD

**Issue by ttttttssssss** [Ikuyadeu/vscode-R#533]
**Describe the bug**
"R path for macOS" Invalid

**To Reproduce**

Premise: The ⬇️ is executed correctly. 
```shell
// mac shell

/Library/Frameworks/R.framework/Versions/4.0/Resources/bin/Rscript desktop/test/r/index.R

// print

[1] "hello world"
```
In vscode work(`desktop/test/r/`)

```
.
├── .vscode
│   └── settings.josn
└── index.R
```

```
// .vscode/settings.josn
{
    "r.rterm.mac": "/Library/Frameworks/R.framework/Versions/4.0/Resources/bin/Rscript"
}
```
use`command + enther`  => vscode error
```
"/Library/Frameworks/R.framework/Versions/4.0/Resources/bin/Rscript '--no-save', '--no-restore'" terminated with exit code: 1.
```

**Do you want to fix by self? (I hope your help!)**

Yes

**what kind of help do you want? **

solution

**Expected behavior**

```
[1] "hello world"
```

**Environment (please complete the following information):**
 - OS: macOS
 - VSCode Version: 1.52
 - R Version: R-4.0.3
 - vscode-R version: 1.6.3

**Additional context**
**index.R**
```
# index.R
print('hello world')
```

**Comment by gowerc** [comment]
Apologies if I am miss-understanding this but I think there maybe confusion over what the cmd+enter command is supposed to do.

By default cmd+enter submits code to be executed in an R terminal session (akin to how it works in Rstudio) for this to work `r.rterm.mac` needs to point to the R executable i.e:
```
/Library/Frameworks/R.framework/Versions/4.0/Resources/bin/R
```

Rscript is a wrapper around this primary used for executing whole files not interactive development.

**Comment by andycraig** [comment]
@gowerc's solution sounds right to me too.

I'm going to close this issue. @ttttttssssss If you are still having problems, please post and we will try to help.
