### ISSUE TITLE
Excle Viewer required while it has been installed

### ISSUE THREAD

**Issue by Whale-fall** [Ikuyadeu/vscode-R#534]
I want to use the function R: Preview dataframe  and R: Preview environment,however, I got this message: This function needs to install `GrapeCity.GC-excel viewer`, will you install? And I am sure I installed this extension

**To Reproduce**
1. create a new file named temp.R
2. Just input iris
3. press the F1 key and select R：Preview dataframe
4. got remained: This function needs to install `GrapeCity.GC-excel viewer`, will you install? And I am sure I installed this extension。

![Snipaste_2021-01-23_15-11-29](https://user-images.githubusercontent.com/22662209/105571725-57d0b680-5d8d-11eb-86a1-8fdd0d5dda58.png)
![Snipaste_2021-01-23_15-11-48](https://user-images.githubusercontent.com/22662209/105571727-5bfcd400-5d8d-11eb-95df-f0a9c76c23e5.png)

**Comment by Whale-fall** [comment]
sorry for my poor English.

**Comment by andycraig** [comment]
Hi @Whale-fall, thank you for reporting. I think this is the same as #399.

**Comment by Whale-fall** [comment]
closed for duplicate as #399
