### ISSUE TITLE
Query: Is it possible to open the help file for a highlighted function

### ISSUE THREAD

**Issue by gowerc** [Ikuyadeu/vscode-R#536]
This is a query rather than an issue.

Is it possible to open the help file for a highlighting function using a keybinding? This is achieved in Rstudio by pressing F1. Apologies if this is already documented somewhere and I missed it!  If it isn't possible is it possible to have this as a feature request.

**Comment by ManuelHentschel** [comment]
Coincidentally, we merged that functionality earlier today in #531 :)

To test the feature you need to install the latest [development build](https://github.com/Ikuyadeu/vscode-R/releases/tag/latest) from the included .vsix file. Then you can open a help file by right clicking on a function name and selecting `Open help for selection` (or use the command in the side-bar).

**Comment by MilesMcBain** [comment]
This has been possible in release for a while using the ability to run a command with word or selection at cursor. E.g. https://github.com/MilesMcBain/vsconfig/blob/master/settings.json#L154

Ignore the structure of the file since it depends on the whichkey extension.

**Comment by gowerc** [comment]
O awesome, thanks both !!
