### ISSUE TITLE
Interactive R terminal using system default R instead of R in a conda environment

### ISSUE THREAD

**Issue by pfren1998** [Ikuyadeu/vscode-R#537]
- VSCode Version: 1.52.1
- VSCode-R Version: 1.6.3
- OS Version: macOS catalina 10.15.6

Steps to Reproduce:

1. `R: Create R Terminal`
2.  The R interactive terminal uses a system default R(3.4.4), and I have created a conda environment and installed another R(4.0.3) before, how can I switch to the version 4.0.3 in vscode? Thanks!

Do you want to fix by self? (I hope your help!)

No

(If related)setting.json

```json
// R path for Linux
"r.rterm.linux": "/mnt/Storage/home/xx/miniconda3/envs/tools/bin/radian“,

// R command line options (i.e: --vanilla)
"r.rterm.option": [--no-save --no-restore],

// An optional encoding to pass to R when executing the file, i.e. 'source(FILE, encoding=ENCODING)'
"r.source.encoding": "UTF-8",

// Keeping focus when running
"r.source.focus": "editor",

// Use active terminal for all commands, rather than creating a new R terminal
"r.alwaysUseActiveTerminal": true,

// Use bracketed paste mode
"r.bracketedPaste": true,

// Enable R session watcher (experimental)
"r.sessionWatcher": true,

// Delay in milliseconds before sending each line to rterm (only applies if r.bracketedPaste is false)
"r.rtermSendDelay": 8,
```

**Comment by ManuelHentschel** [comment]
> OS Version: macOS catalina 10.15.6



> (If related)setting.json
> 
> ```json
> // R path for Linux
> "r.rterm.linux": "/mnt/Storage/home/xx/miniconda3/envs/tools/bin/radian“,
> ```

There is a setting `"r.rpath.mac"` where you can specify the R path for macOS.

**Comment by pfren1998** [comment]
The vscode is running on macOS, and the R is on a remote server(Ubuntu 16.04.2 LTS). Sorry for my misleading message.

**Comment by ManuelHentschel** [comment]
Are you connected to the remote server using the "official" remote extension (i.e. your entire vscode session is on the remote machine) or are you using a normal SSH connection etc. in the terminal?

What is the os displayed when you run the vscode command `R: Create R terminal` and enter `Sys.info()`?

**Comment by pfren1998** [comment]
I connect to the server using Remote-SSH extension in VScode, and below is the output of `Sys.info()`

`
                                      sysname                                       release 
                                      "Linux"                            "4.4.0-62-generic" 
                                      version                                      nodename 
"#83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017"                                  "BioServer1" 
                                      machine                                         login 
                                     "x86_64"                                  "renpengfei" 
                                         user                                effective_user 
                                 "renpengfei"                                  "renpengfei" 
`

**Comment by ManuelHentschel** [comment]
Does anything change if you set `"r.rterm.linux"` and/or `"r.rterm.mac"` to different or invalid paths?

**Comment by pfren1998** [comment]
I set the settings as you suggested, the `r.rterm.linux` was changed to a invalid path, the `r.rterm.linux`and `r.rterm.linux` are different. however, nothing strange happened, whenever I execute `R: Create R Terminal` and `R.home()`, the output is always `/usr/lib/R` which is the system default R.

**Comment by pfren1998** [comment]
Besides, before I execute `R: Create R Terminal`, the status bar in the bottom always shows `R:(not attached)`, I wonder if there is any problem with the settings.

**Comment by pfren1998** [comment]
There are several steps for me to run my code in R
```bash
open bash terminal
conda activate tools
R
command + enter (send code to the R terminal in remote server)
```
I wonder if there are some problems with my operation
Thanks!

**Comment by ManuelHentschel** [comment]
> ```json
> // Use active terminal for all commands, rather than creating a new R terminal
> "r.alwaysUseActiveTerminal": true,
> ```

This setting is used to send code (e.g. form pressing ctrl+enter) directly to the currently active terminal. If you open the R session yourself (as described in your most recent comment) the setting in `r.rterm.linux` shouldn't have any effect here.
To create an R terminal using the path specified in the extension setting, you can call `R: create R terminal` or set `r.alwaysUseActiveTerminal` to `false`.

To see what's going on could you please
* Open an R session as you usually do and type `sessionInfo()` to check the R version
* Open an R session using `R: create R terminal` and check the R version
* Open a bash console, paste the path from `r.rterm.linux`, and check the R version

**Comment by pfren1998** [comment]
Hi, I test as you suggested, below is the report
- Open an R session as you usually do and type sessionInfo() to check the R version
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS/LAPACK: /mnt/Storage/home/renpengfei/miniconda3/envs/tools/lib/libopenblasp-r0.3.12.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3
```

- Open an R session using R: create R terminal and check the R version
```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS/LAPACK: /mnt/Storage/home/renpengfei/miniconda3/envs/tools/lib/libopenblasp-r0.3.12.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.4 jsonlite_1.7.0
```

Open a bash console, paste the path from r.rterm.linux, and check the R version
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS/LAPACK: /mnt/Storage/home/renpengfei/miniconda3/envs/tools/lib/libopenblasp-r0.3.12.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3
```
I really appreciate you help!

**Comment by pfren1998** [comment]
Hi! The info box says ‘Platform is linux’

**Comment by ManuelHentschel** [comment]
That's strange... 
I just pushed some more changes that display more detailed info about the path used (three info boxes): https://github.com/ManuelHentschel/vscode-R/actions/runs/515821160

You could also try running the extension from code and setting a breakpoint roughly [here](https://github.com/ManuelHentschel/vscode-R/blob/592bc6989e1dff4aea71a6b08743019be4f4fbcb/src/util.ts#L101) to see what's going on.

**Comment by pfren1998** [comment]
I installed the version which you mentioned above, but there seems no info box that tells the path.

**Comment by pfren1998** [comment]
Below is the info

- termOptions are: { "name": "R Interactive", "shellPath": "/usr/local/bin/R", "shellArgs": [ "--no-save", "--no-restore" ] }

- Path after fallback: </usr/local/bin/R>

- Path from config (darwin): <>

**Comment by pfren1998** [comment]
Below is the information:
- termOptions are: { "name": "R Interactive", "shellPath": "/mnt/Storage/home/renpengfei/miniconda3/envs/tools/bin/radian", "shellArgs": [ "--no-save", "--no-restore" ] }
- Path after fallback: </mnt/Storage/home/renpengfei/miniconda3/envs/tools/bin/radian>
- Path from config (linux): </mnt/Storage/home/renpengfei/miniconda3/envs/tools/bin/radian>

**Comment by pfren1998** [comment]
It may have some relationship with radian, I will try to set the default R for radian

**Comment by afsdan** [comment]
did you solved the issue about the Interactive R terminal using system default R instead of R in a conda environment, i had the same issue
