### ISSUE TITLE
Error: invalid multibyte character in parser at line 1

### ISSUE THREAD

**Issue by PatricksonFang** [Ikuyadeu/vscode-R#54]
- VSCode Version:1.20.1
- VSCode-R Version:0.5.4
- OS Version: win10

Steps to Reproduce:

1. rm(list = ls())
setwd("D:\\temp")
house<-read.csv("北京链家二手房全部数据.csv")

1. 

(If related)setting.json

```json
// R.exe path for windows
"r.rterm.windows": "C:\\Program Files\\R\\R-3.3.3\\bin\\x64\\R.exe",

// R path for Mac OS X
"r.rterm.mac": "/usr/local/bin/R",

// R path for Linux
"r.rterm.linux": "/usr/bin/R",

// R command line options (i.e: --vanilla)
"r.rterm.option": [],

// An optional encoding to pass to R when executing the file, i.e. 'source(FILE, encoding=ENCODING)'
"r.source.encoding": "UTF-8",

// Keeping focus when running
"r.source.focus": "editor",

// Enable lintr
"r.lintr.enabled": true,

// list of linter functions
"r.lintr.linters": "default_linters",

// toggle caching of lint results
"r.lintr.cache": true,

// R executable path for lintr
"r.lintr.executable": "",

// If true, lintr exec lint_package() instead of lint()
"r.lintr.ispackage": false
```

**Comment by Ikuyadeu** [comment]
@PatricksonFang  Thank you for your issue.
I didn't understand completely.
But I think it is caused by the Chinese characters.
Your setting.json should be added

```json
"editor.renderControlCharacters": true
```

You can see the hidden multibyte characters.

**Comment by PatricksonFang** [comment]
@Ikuyadeu 
Chinese Cannot be displayed.
[Output results](https://github.com/PatricksonFang/The-Art-Of-Programming-By-July/blob/master/11.png?raw=true)
[Terminal Results](https://github.com/PatricksonFang/The-Art-Of-Programming-By-July/blob/master/12.png?raw=true)

**Comment by Ikuyadeu** [comment]
From https://stackoverflow.com/questions/36428141/error-invalid-multibyte-character-in-parser-at-line-1-and-stop

1. Use UTF-8
2. Rewrite R script without Chinese

**Comment by renkun-ken** [comment]
Feel free to open if you still encounter this problem.
