### ISSUE TITLE
Increase or make configurable level of utils::str used for session global env watcher?

### ISSUE THREAD

**Issue by MilesMcBain** [Ikuyadeu/vscode-R#540]
I like the fact that an object summary is shown on the hover but I find it a bit brief, particularly for data.frames. E.g.

```
tibble [100 x 4] (S3: tbl_df/tbl/data.frame)
```

Would it be possible to increase the level of description or make it configurable via an option?

From my reading of the code it would be a matter of changing the `max.level` in the call to utils::str here: https://github.com/Ikuyadeu/vscode-R/blob/master/R/init.R#L63

For example, if this is set to 2, it gives a useful summary of data frame columns:

```
tibble [100 x 4] (S3: tbl_df/tbl/data.frame)
 $ h3_index          : chr [1:100] "889d4a0643fffff" "889c236007fffff" "88be8d10a9fffff" "889c236001fffff" ...
 $ n_incidents       : int [1:100] 128 155 465 112 610 1675 537 43 31 77 ...
 $ mean_residual_mins: num [1:100] 18.96 10.88 2.81 9 1.59 ...
 $ score             : num [1:100] 2427 1686 1305 1008 967 ...
```

I realise with big data frames this may make for a large amount of hover information. It's not so much of an issue for me because I use another extension which shows the hover in a view at the side. Probably an argument for making an option.

Any interest in a PR?

**Comment by renkun-ken** [comment]
Sure, you could file an PR making it an option?
