### ISSUE TITLE
'Run Source' shortcut collides with 'Save As...' default binding

### ISSUE THREAD

**Issue by albertopessia** [Ikuyadeu/vscode-R#55]
- VSCode Version: 1.20.1
- VSCode-R Version: 0.5.4
- OS Version: Windows 10

Key combination `Ctrl + Shift + S` is a standard shortcut for 'Save As...' dialog and it is already taken by VS Code. I suggest to use a different combination for 'R: Run Source' because the user might get a different behavior than the one expected.

Thanks for the great extension!

**Comment by Ikuyadeu** [comment]
@albertopessia Thank you for using this extension and issue.
I agree your suggestion. However, R Studio users think `Ctrl + Shift + S` is Run Source.
Sorry, please change `setting.json`.
I put 
> TODO: Add Command `R: Change shortcut mode`

If other users want this function.

**Comment by andycraig** [comment]
I’m following up on some old issues. I think changing via `setting.json` is probably sufficient for users who want `Ctrl + Shift + S` to be set back to ‘Save As...’.

@Ikuyadeu I’m closing this but please reopen if you want!

**Comment by Ikuyadeu** [comment]
@andycraig Thank you for managing issues!
