### ISSUE TITLE
Expand search scope for "Go to Definition"

### ISSUE THREAD

**Issue by jhan1** [Ikuyadeu/vscode-R#557]
**Is your feature request related to a problem? Please describe.**
When a function exists in a different file (but still in the same project folder), pressing F12 ("Go to Definition") doesn't work as the error message "No definition found for <func_name>" pops up. 

**Describe the solution you'd like**
Like RStudio, I would like "Go to Definition" expand the search scope to the existing project folder. If multiple occurence, show it as dropdown list so user can select. 

![Screen Shot 2021-02-17 at 12 20 40 AM](https://user-images.githubusercontent.com/22291313/108159900-fbc03000-70b5-11eb-9202-384d5e9cfcef.png)

Thanks for you awesome extension!

**Comment by renkun-ken** [comment]
All language services are acutally provided by [languageserver](https://github.com/REditorSupport/languageserver).

This is a duplicate of https://github.com/REditorSupport/languageserver/issues/20.
