### ISSUE TITLE
Seems not working on M1 (Apple Silicon) Mac

### ISSUE THREAD

**Issue by hyga2c** [Ikuyadeu/vscode-R#561]
I am using Mac mini 2020 (M1 chip) with the following apps:

VScode: version 1.53.2
R: version 4.0.4 

After I installed "R support for Visual Studio Code", an error message says "darwin can't use R"

Is this extension compatible with M1 chip?

**Comment by psobolewskiPhD** [comment]
I've been using this extension with no issue on my M1 MBPro.
However, I'm using native VSCode (1.54) and native R (homebrew).
Can you provide more info regarding your R environment?
Have you set:
r.rterm.mac to point to your R install?

**Comment by hyga2c** [comment]
@psobolewskiPhD Thank you for your advice.
I am using intel VSCode and intel R. 
I have have downloaded R package from https://cran.ism.ac.jp/ (R-4.0.4.pkg) and installed to /Application/ folder.
I tried to set r.rterm.mac as `/Applications/R.app`
However, same message appears "darwin can't use R"

**Comment by hyga2c** [comment]
I pointed the wrong file, I finally understand.
r.term.mac should be 
`/Library/Frameworks/R.framework/Versions/4.0/Resources/bin/R`
It works fine.
Thanks.

**Comment by macumop** [comment]
Does not work on the MacBook Air M1.

**Comment by psobolewskiPhD** [comment]
Need some more info, as you can see from the above that it does *work* on M1 mini and M1 MBPro...
What error are you getting?
What combination of VS Code and R are you using?
Are you using radian? 
Do you have r.rterm.mac to point to your R/radian install?
