### ISSUE TITLE
Forward slashes in r.rpath.windows stop Help Viewer working on Windows

### ISSUE THREAD

**Issue by MilesMcBain** [Ikuyadeu/vscode-R#562]
**Describe the bug**
None of the help viewer functionality works for me as of this morning when I upgraded to R 4.0.4. Clicking on any of the options under `HELP PAGES` throws an error, some shown here:

![image](https://user-images.githubusercontent.com/9996346/108949716-a507b700-76b0-11eb-8775-0a3b22e6a661.png)

Also the `?` operator and `help()` function do not work. For example `help(group_by)` with `dplyr` loaded gives a VSCode error:

![image](https://user-images.githubusercontent.com/9996346/108950306-b8675200-76b1-11eb-9df6-6bffce7a1e8a.png)

It was working well prior to the upgrade, as far as I am aware, all I have done is install R 4.0.4 and change the extension setting `R > Rpath: Windows` to: `C:/R/R-4.0.4/bin/x64/R/R.exe`

I do not have my library in that location, but I don't think that should matter, in any case I have:

```
[ins] r$> .libPaths()
[1] "C:/Users/msmcbain/libs/R" "C:/R/R-4.0.4/library"    
```

If I turn off the help panel with `vsc.helpPanel = FALSE`, things work normally - `help()` and `?` are usable and open a new browser window with help.

**To Reproduce**
I am not sure if you'll be able to reproduce. I guess you could try on R 4.0.4 but that feels quite unlikely. Possibly it's something to do with the path setting on windows?

**Do you want to fix by self? (I hope your help!)**

I can't build extensions on this machine so hard to debug. I'll try to reproduce on my personal computer when I get a chance. 

**(If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)**

(If related)setting.json

```json
  "r.rterm.windows": "C:/Users/msmcbain/AppData/Local/Programs/Python/Python38/Scripts/radian.exe",
    "r.bracketedPaste": true,
    "r.rmarkdown.enableCodeLens": false,
    "r.rpath.windows": "C:/R/R-4.0.4/bin/x64/R/R.exe"
```

**Expected behavior**
The Help Panel to function without error.

**Environment (please complete the following information):**
 - OS: Windows
 - VSCode Version: 1.53.2
 - R Version: 4.0.4
 - vscode-R version: 1.6.4

**Additional context**

**Comment by ManuelHentschel** [comment]
On my machine (windows 10) it's working with versions 3.6.3, 4.0.3, and 4.0.4 so it doesn't seem to be a general problem with R 4.0.4.

Do the terminal related commands (e.g. `R: Create R terminal`) work if you replace the radian path with the path from `"r.rpath.windows"`?

**Comment by MilesMcBain** [comment]
Yeah terminal commands work, as in I can successfully attach the terminal, but help related things have the same way.

**Comment by MilesMcBain** [comment]
It's working again now!

I removed `"r.rpath.windows": "C:/R/R-4.0.4/bin/x64/R/R.exe"` and let it default from my $PATH which has `C:\R\R-4.0.4\bin\x64`, so maybe this is a slash direction issue? They are interchangeable in R but maybe not in the typescript?

**Comment by ManuelHentschel** [comment]
Sounds like a slash direction issue. As far as I'm aware they are not interchangeable in typescript (though some automatic conversion might take place in the background)

**Comment by MilesMcBain** [comment]
Yeah okay I think I'll just rename the issue as a breadcrumb for someone else, and close. Nothing to do I think, other than use your platform's path conventions.

Thanks for trying to reproduce.
