### ISSUE TITLE
Question about long input lines in R console

### ISSUE THREAD

**Issue by MNRK01** [Ikuyadeu/vscode-R#57]
- VSCode Version: 1.21.1
- VSCode-R Version: 0.5.4
- OS Version: Windows 10

I have some trouble with long input lines when using R console under Visual Studio Code with the vscode-R add-in.

In RStudio, I can do the following in an R console without any issues:
```R
> print("1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890")
[1] "1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890"

```

However, in VSCode-R, trying the same input gives me:

```R
> print("123456789012345678901234567890123456789012345678901234567890123456789$
[1] "1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890"
```

Notice the "$" symbol at the end of the input line from VSCode-R console. The visible portion of long input lines get truncated to 76 characters. The input is all there, it's the visible part that gets truncated. The help for [Base R readline command](https://stat.ethz.ch/R-manual/R-devel/library/base/html/readline.html), states that the limit is 256 characters so that can't be the source of this issue.

I am not sure what the issue is but it seems that the input line character limitation is specific to vscode-R.

Changing ```options(width=132)``` does not help and neither should it since it this option is for output lines.

I would appreciate it if someone could take a look into my report. Thank you for an excellent add-in!

Steps to Reproduce:

1. Open up VSCode, then Ctrl + Shift + P, then "R: Create R terminal"
2. Paste above input line, use Left and Right arrow keys to inspect/confirm that the entire line is present
3. Repeat the same in RStudio to demonstrate that truncation is an issue specific to vscode-R

setting.json

```json
  // toggle caching of lint results
  "r.lintr.cache": true,

  // Enable lintr
  "r.lintr.enabled": true,

  // R executable path for lintr
  "r.lintr.executable": "",

  // If true, lintr exec lint_package() instead of lint()
  "r.lintr.ispackage": false,

  // list of linter functions
  "r.lintr.linters": "default_linters",

  // R path for Linux
  "r.rterm.linux": "/usr/bin/R",

  // R path for Mac OS X
  "r.rterm.mac": "/usr/local/bin/R",

  // R command line options (i.e: --vanilla)
  "r.rterm.option": [
    "--no-save",
    "--no-restore",
    "--no-site-file"
  ],

  // R.exe path for windows
  "r.rterm.windows": "C:\\Program Files\\R\\R-3.3.3\\bin\\x64\\R.exe",

  // An optional encoding to pass to R when executing the file, i.e. 'source(FILE, encoding=ENCODING)'
  "r.source.encoding": "UTF-8",

  // Keeping focus when running
  "r.source.focus": "editor"
```

user modified setting.json:
```json
    // R settings
    "r.rterm.windows": "C:/Program Files/R/R-3.4.3/bin/x64/R.exe",
    "r.lintr.enabled": false,
```

**Comment by Ikuyadeu** [comment]
@MNRK01 Thank you for using and submitting the issue.
It is difficult to identify for VS Code issue or vscode-r issue.
However, it is not so important bug, if you know this.
As the future work, I can add this limitation on the document.

**Comment by Ladvien** [comment]
@MNRK01 
Hey, I think I implemented a change awhile back which should have resolved this issue.  Basically, what I found was RTerm wasn't processing text as quickly as VSCode was sending it.  This resulted in a lot of the text being lost or RTerm freezing up.  

I added a small async delay (please no judgement) between sending "chunks" of a command to RTerm.

Anyway, I'm not able to reproduce the behavior now, even with extremely long commands (see image).

![](https://ladvien.com/images/r-term-delay-fix.png)

**Comment by Ladvien** [comment]
I'm going to close issue, since it doesn't seem to still be impactful.
