### ISSUE TITLE
Send code to debug window

### ISSUE THREAD

**Issue by krlmlr** [Ikuyadeu/vscode-R#570]
**Is your feature request related to a problem? Please describe.**
In a debugging session with https://github.com/ManuelHentschel/VSCode-R-Debugger, Ctrl + Enter still sends code to the R session.

**Describe the solution you'd like**
Ctrl + Enter sends to the debug window if `inDebugMode`.

**Describe alternatives you've considered**
I have mapped `editor.debug.action.selectionToRepl` to Ctrl + Enter if `inDebugMode` is set. This works but I need to select the code I want to send. I'd like to take advantage of this extension's ability to detect the R code to send to the debug window.

**Additional context**
Thanks for the great extension!

**Comment by krlmlr** [comment]
@ManuelHentschel Does this require help from VSCode-R-Debugger? AFAICT the Python extension has a similar command: https://github.com/microsoft/vscode-python/issues/14494.

**Comment by krlmlr** [comment]
I changed the "when" for Ctrl+Enter to include `!inDebugMode`, now I can select code and press Ctrl + Enter to send code to the debug console. The default command "editor.debug.action.selectionToRepl" does that. It would be great if this extension enhanced this to send the current line and/or expression to the REPL. Do we need help from the R language server (or does this even belong there)?

CC @renkun-ken.

**Comment by ManuelHentschel** [comment]
> @ManuelHentschel Does this require help from VSCode-R-Debugger? AFAICT the Python extension has a similar command: [microsoft/vscode-python#14494](https://github.com/microsoft/vscode-python/issues/14494).

Ideally, this should be possible without any changes to VSCode-R-Debugger, using something similar to the command `editor.debug.action.selectionToRepl` or `debug.replPaste`. It's a bit annoying that there seems to be no command to send arbitrary text to the repl, just the selection/clipboard.

A workaround might be to determine which code to send, using the existing functions from this package, then quickly select that text, call `editor.debug.action.selectionToRepl` and revert the selection (or accordingly using the clipboard, though at first glance that command only seems to paste the code without running it).

**Comment by krlmlr** [comment]
Yeah, I forgot about "editor.debug.action.selectionToRepl". AFAICT this commands sends and executes, at least after I mark the line with Ctrl + L.

Can an extension send arbitrary text to the REPL?

**Comment by ManuelHentschel** [comment]
> Can an extension send arbitrary text to the REPL?

Not as far as I'm aware. An extension can send custom commands to a debug session, using [`vscode.DebugSession.customRequest`](https://github.com/microsoft/vscode/blob/1436b523d4aaa773ab246daa68daaa70cef48b1d/src/vs/vscode.d.ts#L11081-L11084) or access any of the normal commands, but there seems to be no command/function to send arbitrary text.



> A workaround might be to determine which code to send, using the existing functions from this package, then quickly select that text, call `editor.debug.action.selectionToRepl` and revert the selection (or accordingly using the clipboard, though at first glance that command only seems to paste the code without running it).

This could be implemented by the `vscode-R` extension instead, but feels a bit hacky.

**Comment by Sandy4321** [comment]
will it  work for python debugging ? 
Send code to debug window for current code line with cursor

**Comment by Sandy4321** [comment]
like
https://www.youtube.com/watch?v=VXJChVF28jw
How To Run Selected Lines In VS Code (Visual Studio Code)

how to find exact text to update key binding json file ?
