### ISSUE TITLE
Run certain commands as a task instead of sending to terminal

### ISSUE THREAD

**Issue by krlmlr** [Ikuyadeu/vscode-R#571]
**Is your feature request related to a problem? Please describe.**
I'm exploring VS Code as an alternative to RStudio for package development. In RStudio, most dev-related tasks run in a dedicated session without affecting the main REPL.

**Describe the solution you'd like**
I'd like to be able to press Ctrl+Shift+B (or a different shortcut) to run `R CMD INSTALL`, and e.g. `devtools::document()` should run in a separate session.

**Describe alternatives you've considered**
I can define tasks myself, do I need to replicate this for every project?

**Additional context**
Example `tasks.json`:

```json
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Install",
      "type": "shell",
      "command": "R CMD INSTALL .",
      "problemMatcher": [],
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

**Comment by ElianHugh** [comment]
Could be related to #440, as background sessions may be useful for this

**Comment by krlmlr** [comment]
Only for some tasks I guess; I think this is largely independent of background sessions?

**Comment by andycraig** [comment]
Here's another feature request related to tasks: #59

**Comment by krlmlr** [comment]
Closing as a duplicate.
