### ISSUE TITLE
Implement "Extract variable" and "Inline variable" refactorings

### ISSUE THREAD

**Issue by krlmlr** [Ikuyadeu/vscode-R#574]
**Is your feature request related to a problem? Please describe.**
I'd like to edit my code even faster.

**Describe the solution you'd like**
For "Extract variable", the transformation would be:

```
# Old
f(g(x))
```

Select `g(x)`, then "Extract variable", then:

```
# New
var <- g(x)
f(var)
```

The `var` should be selected with two cursors so that I can type in the name.

For "Inline variable", the other way round: I select `var`, then all instances of `var` are replaced by the right-hand side.

**Describe alternatives you've considered**
RStudio has "Extract variable".

**Additional context**
This seems to be a pretty common refactoring available for other languages.

**Comment by andycraig** [comment]
Hi @krlmlr, thank you for the suggestion. I reckon the place to implement refactoring is the language server. It maintains a parse tree, so it's easier to implement there, and implementing it there means that editors other than VS Code can use the feature too.

I opened an issue for extract variable/function this a while ago and it's on my list but it could be a while before I get to it. (Help would be very welcome of course!) I've added 'inline' to the title as that would be useful too and is closely related to extract variable. https://github.com/REditorSupport/languageserver/issues/94

I'll close this in favour of the language server issue.
