### ISSUE TITLE
Support sending to console without execution

### ISSUE THREAD

**Issue by krlmlr** [Ikuyadeu/vscode-R#575]
**Is your feature request related to a problem? Please describe.**
fledge calls `rstudioapi::sendToConsole(execute = FALSE)`, this is currently unsupported. Also, we could provide a command that sends to the console without execution, this can be useful when we want to edit the code before executing.

**Describe the solution you'd like**
I'd like the `execute = FALSE` variant supported, I think we need to call `term.sendText(code, false)` in this situation.

**Describe alternatives you've considered**
I have worked around in fledge for now, would be great to support this out of the box.

**Additional context**
Comment in original PR: https://github.com/Ikuyadeu/vscode-R/pull/535#issuecomment-792508390

VS Code API link: https://code.visualstudio.com/api/references/vscode-api#Terminal

**Comment by MilesMcBain** [comment]
As far as I can remember this is possible I just didn't do it because the terminal send call is wrapped in a couple of layers of stuff. 

Felt a bit weird making so many changes for something I wasn't sure sure would ever get used.

**Comment by krlmlr** [comment]
Would you review a pull request?

**Comment by andycraig** [comment]
@krlmlr PR very welcome!
