### ISSUE TITLE
Workspace viewer str() functionality

### ISSUE THREAD

**Issue by danielbasso** [Ikuyadeu/vscode-R#577]
Following up on the discussion that took place in #416, I would like to suggest two improvements upon the current workspace viewer (which is already nice) that would make my experience using this extension almost perfect:

1) The most important one: the environment pane from RStudio has this button near each object that when pressed, print the result of `str(object)` under it:

![image](https://user-images.githubusercontent.com/20959177/110412801-89ff5480-806b-11eb-86d9-c4d13861a98a.png)

 I use this feature *all the time* as I always dealing with large dataframes with lots of columns, and sometimes you have to double check the actual type of one column in particular (like if a column is a `Date` a `character`). Sometimes I can't remember the name of some variable (not even how it starts) and this helps me. 

A similar button could be implemented in vscode-R:

![image](https://user-images.githubusercontent.com/20959177/110413214-3e00df80-806c-11eb-9de9-793fb6a858a7.png)

2) Apart from that, I think that the workspace panel could be moved to the explorer tab, under the folder contents panel. This, alongside the first suggestion, would make really easy to explore objects. The whole R tab (workspace + help) could be moved there, so you could manage your files and R objects without the need to switch between them:

![image](https://user-images.githubusercontent.com/20959177/110413959-abf9d680-806d-11eb-97a6-b2f89bb05108.png)

This happens with extensions from other languages (eg. Spring Boot Dashboard, Sonar Lint); having to switch tabs to access the workspace panel kinda hinders its potential to me.

**Comment by ElianHugh** [comment]
> Following up on the discussion that took place in #416, I would like to suggest two improvements upon the current workspace viewer (which is already nice) that would make my experience using this extension almost perfect:
> 
> 1) The most important one: the environment pane from RStudio has this button near each object that when pressed, print the result of `str(object)` under it:
> 
> ![image](https://user-images.githubusercontent.com/20959177/110412801-89ff5480-806b-11eb-86d9-c4d13861a98a.png)
> 
>  I use this feature *all the time* as I always dealing with large dataframes with lots of columns, and sometimes you have to double check the actual type of one column in particular (like if a column is a `Date` a `character`). Sometimes I can't remember the name of some variable (not even how it starts) and this helps me. 
> 
> A similar button could be implemented in vscode-R:
> 
> ![image](https://user-images.githubusercontent.com/20959177/110413214-3e00df80-806c-11eb-9de9-793fb6a858a7.png)
> 

I agree that this functionality is super useful! When writing the workspace viewer, I originally intended to include this (but ran out of time), so definitely something I'd like to work on :)

With regard to the placement of the viewer, you should be able to dock it wherever you want by dragging it around.

**Comment by danielbasso** [comment]
`With regard to the placement of the viewer, you should be able to dock it wherever you want by dragging it around.`

Well, I knew, I absolutely knew that this was already possible! I tried googling it, tried the settings, I just didn't try the most obvious thing that would be dragging the panel. Seriously, I've spent a good 30 minutes looking for the settings to do this hahaha. I fell so dumb now...

**Comment by danielbasso** [comment]
Decided to fiddle with the project a bit just for fun, I wouldn't believe that I would go this far:

![image](https://user-images.githubusercontent.com/20959177/111567545-e6562880-877d-11eb-8713-23be16c7fa29.png)

Beginner's luck I guess haha
