### ISSUE TITLE
Using object.size() in init.R could be expensive

### ISSUE THREAD

**Issue by renkun-ken** [Ikuyadeu/vscode-R#580]
**Describe the bug**

87f9bb6f8b450d897fb191780b086de07805fd4e in #544  uses `object.size(obj)` in `inspect_env` in `init.R` to support showing object size in the workspace viewer. However, the performance of this function could be extremely poor if the object contains character vectors in it.

```r
library(data.table)
dt <- data.table(id = 1:5000000)
for (i in 1:20) {
  dt[, paste0("x", i) := rep("hello", .N)]
}
system.time(object.size(dt))
```

```
   user  system elapsed
  1.068   0.687   1.741
```

This means, with session watcher enabled, whenever this data table is present in the global environment, then user has to wait for 1.7s after evaluating each top-level expression.

Therefore, I don't think we should call `object.size()` so eagerly in this way.

**Comment by renkun-ken** [comment]
@ ElianHugh Do you think we should remove this call or at least be more conservative using this?

**Comment by renkun-ken** [comment]
@Ikuyadeu This issue is quite blocking for users who work with large data with a few character vectors as the R session will become too laggy to use. I suggest that we make a quick release when #581 is merged.

**Comment by ElianHugh** [comment]
Apologies, that's definitely not intended! I agree, we should remove the call.

**Comment by ElianHugh** [comment]
I'm not sure of a way around this in base-R given this [stackoverflow post](https://stackoverflow.com/questions/19548938/faster-alternative-to-object-size).

Comparing alternatives in RStudio:

`system.time(object.size(dt))`
   user  system elapsed 
   2.06    0.75    3.14

`system.time(lobstr::obj_size(dt))`
   user  system elapsed 
   6.89    0.02    7.69

Or we could estimate it by getting the size of a subset of a given object?

**Comment by renkun-ken** [comment]
>Or we could estimate it by getting the size of a subset of a given object?

It might add too much complexity if we take into account nested list, environment, object attributes, etc. where character vector could appear anywhere.

**Comment by ElianHugh** [comment]
Agreed. I was looking through RStudio and it looks like they use object.size for their environment pane. I suppose using object.size would require a more substantial rewrite than is worth at the moment

**Comment by tdeenes** [comment]
Maybe one can record the timings on first invocation, and turn off the auto-object.size-calculation if the timing result is above a given threshold. Most people do not work with huge character vectors in interactive sessions.

**Comment by renkun-ken** [comment]
I implement a method in the middle ground, i.e. we only call `object.size()` when the either a symbol is not present in the cache or its memory address has changed. This will work with most cases but ignores those with in-place updates on an object.

**Comment by ElianHugh** [comment]
> I implement a method in the middle ground, i.e. we only call `object.size()` when either a symbol is not present in the cache or its memory address has changed. This will work with most cases but ignores those with in-place updates on an object.

This is awesome and a great middle ground, thank you!

**Comment by renkun-ken** [comment]
With #581 merged, wow the `object.size()` is called less frequently: it is called only when a new symbol appears or its memory address or length has changed.

And we have an option `vsc.show_object_size` to opt-in. It is disabled by default to minimize possible delay.
