### ISSUE TITLE
Feature request: citation auto-completion in *.Rmd

### ISSUE THREAD

**Issue by jooyoungseo** [Ikuyadeu/vscode-R#588]
It would be wonderful if citation key auto-completion could be supported within *.Rmd file just like [Pandoc Citer](https://marketplace.visualstudio.com/items?itemName=notZaki.pandocciter).

**Comment by renkun-ken** [comment]
@andycraig  Is it possible to make rmd also work with markdown extensions?

**Comment by andycraig** [comment]
@renkun-ken At #289 I was thinking about changing the language identifier for .Rmd files from `rmd` to `md`. We would then add R Markdown features to `md`. I think Markdown extensions would work in that case. We use `rmd` to set R Markdown-specific keybindings so we might need to define something new for use in keybinding `when` clauses.

That said, I haven't tried Pandoc Citer but it looks like it's specifically designed to work with `rmd` files:

https://github.com/notZaki/PandocCiter/blob/54cffeab336da535f0c3a1e906a49e76444c7120/src/extension.ts#L38

So if it's not working it might be a bug in vscode-R and/or Pandoc Citer. We both provide completion when the user types '@' so maybe there's a conflict there?

**Comment by andycraig** [comment]
@jooyoungseo Is Pandoc Citer working for you in .md files but not .rmd files?

**Comment by jooyoungseo** [comment]
@andycraig, thanks for the heads-up! Now it works. I had the following problematic configuration in my `settings.json` file; removing that resolved the issue.

``` json
    "files.associations": {
        "*.rmd": "markdown"
    },
```

**Comment by andycraig** [comment]
@jooyoungseo Great! Thank you.
