### ISSUE TITLE
extra blank lines added after cursor in radian powered terminal

### ISSUE THREAD

**Issue by romunov** [Ikuyadeu/vscode-R#592]
When running the radian as terminal, some empty lines keep getting added under the cursor, obfuscating the content above.

![Screenshot from 2021-03-22 12-51-26](https://user-images.githubusercontent.com/544571/111987227-3b43c700-8b0f-11eb-85c0-509b2b28d639.png)

No matter how much the terminal is expanded, several empty lines are added.

If I turn radian off, the terminal behaves as expected.

![Screenshot from 2021-03-22 12-55-51](https://user-images.githubusercontent.com/544571/111987335-64645780-8b0f-11eb-9f47-fb2eb7a5da44.png)

**Environment:**
 - OS: Fedora
 - VSCode Version: 1.54.3
 - R Version: 4.0.4
 - vscode-R version: 1.6.5

These are the settings:
```json
{
    "r.bracketedPaste": true,
    "r.lsp.debug": true,
    //"r.rterm.linux": "/home/user/.local/bin/radian",  // radian temporarily turned off
    "r.lsp.diagnostics": true,
    "r.rterm.option": [
        "--no-save",
        "--no-restore"
    ],
    "r.rpath.linux": "/usr/bin/R",
    "files.associations": {
        "*.rmd": "markdown"
    },
    "r.sessionWatcher": true
}
```

**Comment by renkun-ken** [comment]
This is a known radian issue (https://github.com/randy3k/radian/issues/135).
