### ISSUE TITLE
VSCode reports "Darwin can't use R" on MacBook Pro 2019 with MacOS 11.2.3

### ISSUE THREAD

**Issue by JarneUzL** [Ikuyadeu/vscode-R#595]
**Describe the bug**
After trying to install and run R markdown in VSCode it reports "Darwin can't use R". 
Previously we installed R, R Language Server and Client, MiKTeX, Python and Radian. 

**Expected behavior**
I expected it to not happen.

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/81361624/112684169-ea1b3680-8e72-11eb-8abd-6c7e32614f91.png">

**Environment :**
 - OS: [MacOS 11.2.3]
 - VSCode Version: [1.54.3]
 - R Version: [4.0.4]
 - vscode-R version: [1.6.5]

**Comment by andycraig** [comment]
Hi @JarneUzL, can you try adding a setting `"r.rpath.mac": path/of/your/executable/for/r`? Make sure it points to R, not radian.

We need to make this error message clearer: #568.

**Comment by andycraig** [comment]
While fixing the error messages to make them clearer, I realised we have the same message for two different errors. So you may also need to set  `"r.rterm.mac": "path/of/your/executable/for/radian"` .

The error messages should be clearer in the next version of this extension.

**Comment by JarneUzL** [comment]
Hello Andy,
Thank you for your fast reply. 
Indeed the error message is clearer now, but still a little bit weird. It now says: 
"Cannot find R client. Please check R path in preferences"
This seems to be quite easy to fix, but I checked and my path for R is the valid and there shouldn't be any more problems.
I will attach another screen capture with the new added options and maybe you are able to spot a mistake. 

with kind regards,
Jarne 
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/81361624/112844555-27b2d600-90a4-11eb-9653-ee97aacfe10d.png">

**Comment by JarneUzL** [comment]
I have also tried two way:
1. Describing the path to R/radian
2. Describing the path to the folder where R/radian are found.

Both didn't work and led to the error message.

**Comment by andycraig** [comment]
The path should be to R/radian (that is, it should end in 'R' or 'radian'), but you have tried that and it didn't work either.

Can you do this for me?
1. Change the path to end in R/radian
2. Copy-paste that path into the VS Code terminal. It should start R/radian in the terminal
3. Try to launch radian via VS Code. It will probably produce the error message again
4. Take a screenshot of that (like the one before, showing both your settings and the terminal)

I can use the screenshot to help figure out whether there is a bug. Thank you!

**Comment by Johnnypark99** [comment]
Hello, I have the 2020 MacBook Air with Apple Silicon and  I have received an identical problem.

The VS Code is initially reporting `Darwin can't use R`. After adding the path in `r.rterm.mac`, I have received a different error:
```
Command failed: undefined --silent --no-save --no-restore --slave -f "/Users/myusername/.vscode/extensions/ikuyadeu.r-
1.6.5/R/getAliases.R" > "/var/folders/cg/4pxvnpm96cz7hbh94wl12rtm0000gn/T/vscode-R-aliases-Dvigjm/aliases.json" 
/bin/sh: undefined: command not found
```

I also receive the error: 
```
Failed to get list of R functions. Make sure that `jsonlite` is installed 
and r.helpPanel.rpath points to a valid R executable.
```
I have installed jsonlite, and adding the R path for `r.helpPanel.rpath` did not fix it. 
![Screen Shot 2021-04-03 at 3 11 57 AM](https://user-images.githubusercontent.com/45082451/113471518-dcdde900-942a-11eb-8292-f26cc3b7b6c2.png)
![Screen Shot 2021-04-03 at 3 16 10 AM](https://user-images.githubusercontent.com/45082451/113471540-13b3ff00-942b-11eb-873b-ceaf8236527b.png)

There hasn't been any issues other than the error message popping up constantly. I do not use radian, as there has been another issue installing radian.

**Comment by andycraig** [comment]
Hi @Johnnypark99, since you're experiencing different errors I've created a new issue for those: #604

**Comment by JarneUzL** [comment]
Hey Andy,
Sorry for the late reply. 
We made a really dumb mistake in describing the path to radian. :)

Now everything works, seems that your extension is working just fine.

Jarne

**Comment by andycraig** [comment]
Hi @JarneUzL, thank you for the update. Good to hear that the problem was solved and everything is okay.
