### ISSUE TITLE
No command found

### ISSUE THREAD

**Issue by wilfriedgh** [Ikuyadeu/vscode-R#6]
Good afternoon,

Problem
------------------------
I can't run any R command from VSC with the R extension installed.

Additional explanations:
------------------------
I installed the extension but am not able to run any command. For installing, I just downloaded from VSC marketplace and checked R path in the settings. When seeing that it was working, I uninstalled and reinstalled the extension, R, and lintr in R. I'm usually using RStudio without problem.

R, VSC and macOS are updated to the last version available.

Enclosed files:
---------------
[Screen captures.zip](https://github.com/Ikuyadeu/vscode-R/files/1045007/Screen.captures.zip)
[settings.json.zip](https://github.com/Ikuyadeu/vscode-R/files/1045008/settings.json.zip)

------------------------

Additional information:
------------------------

## Visual Code Studio:
Mac, Version 1.12.2 (1.12.2)

## R:
platform: x86_64-apple-darwin15.6.0   
arch: x86_64 // os: darwin15.6.0 //system: x86_64, darwin15.6.0                       
svn rev: 72570             
version.string R version 3.4.0 (2017-04-21)

## MacOS:
System Version:	macOS 10.12.5 (16F73)
Kernel Version:	Darwin 16.6.0

**Comment by Ikuyadeu** [comment]
@wilfriedgh  Thanks for the detailed information, this was really helpful!:smile:
This enviroment is not so different than mine.
This problem maybe like https://github.com/Microsoft/vscode/issues/15837.
How did you install this extension?

**Comment by wilfriedgh** [comment]
It might.
I installed the extension through the VSCode marketplace, no special operations (I ran through your README twice but didn't find anything specific to do..)

**Comment by Ikuyadeu** [comment]
Similar problem and solve in https://github.com/Microsoft/vscode/issues/25026
This problem will probably fix by reinstall extension or VSCode or install VSCode insider version.
I'll update this extension tomorrow or 2 days ago.

**Comment by wilfriedgh** [comment]
Hi Ikuyadeu,
I uninstalled and reinstalled 1- VSC and 2- your extension without success today (meaning: it installed, but didn't work, while the CPP extension commands are found and work).
I also installed VSCinsider, and got the same issue.
I'll just do with RStudio for I'm running out of time at the moment (project deadline coming soon), but thank you really much for your support, and sad that I can't use your extension, but your work seems amazing. Good luck with the future developments:)

**Comment by Ikuyadeu** [comment]
@wilfriedgh @wilfriedgh I'm sorry I couldn't be much of a help. 😞
Please delete  `ikuyadeu.r-0.*` in your  `~/.vscode/extensions/` and re-install my extensions when you will have time.

**Comment by wilfriedgh** [comment]
Don't worry Yuki, you've been answering as much as you could, I've actually been very satisfied with your support:)
For what you told me in your last message, I've tried it, and it didn't change anything. I also tried it on the insiders version, trying to prevent any extensions conflict by deleting all the extensions and reinstalling only yours afterwards, and still, I had this command not found problem.
Therefore it might be linked to my system, not to your extension..

**Comment by karolz-ms** [comment]
On Windows 10 here, VSCode 1.12.2. I get the same error message, command not found, for pretty much any command that R extension is supposed to contribute. Tried uninstalling and installing the extension multiple times, no luck. Other extensions (e.g. Python) work.

**Comment by Ikuyadeu** [comment]
@wilfriedgh @karolz-ms 
Thank you for your issue, I reproduced!
Now, this extension work only in directory. Please open directory that has your R source file.

And I'll fix this problem in future.

**Comment by karolz-ms** [comment]
@Ikuyadeu thanks! This workaround works well for me :-)

**Comment by wilfriedgh** [comment]
@Ikuyadeu Works fine as well, thank you!
I'll edit the Store review to redirect to this page as soon as I have a bit of time.

**Comment by guvenim** [comment]
I was getting the same error, then this snippet solved it

"Please open directory that has your R source file.
F1 and Run Source"

**Comment by ejazr83** [comment]
I am getting the same issue, but when I try F1 and Run Source I get

Error command 'r.runSouce' not found

I am assuming open directory means opening it in VS Code, correct?

**Comment by hfberg** [comment]
@ejazr83 did you ever manage to solve this? I'm running R 3.6 on ubuntu 18.04 and vs code 1.34.0. I have not specified any special path to R in the settings, when I had a look on the default path it looked good enough. Following the recipe here, I opened the folder in which the R script lives (/usr/bin/R for linux), pressed F1 and typed Run source. I get the error message:

Running the contributed command: 'r.runSource' failed.

strange enough, I have a different window running R without trouble. suggestions in this group? :)
