### ISSUE TITLE
Wiki tips for handling ${file} in keybindings.json?

### ISSUE THREAD

**Issue by jooyoungseo** [Ikuyadeu/vscode-R#606]
It would be appreciated if someone could walk me through how to create a shortcut key for `knitr::wrap_rmd(${file})`. And, it would also be great to include the tip in wiki page explaining how to handle vscode variables (e.g., `${file}`) in `keybindings.json`.

The following is my `keybindings.json`, which does not work:

``` json
[
    {
        "description": "Wrap long lines in Rmd files in knitr",
        "key": "alt+shift+w",
        "command": "r.runCommand",
        "when": "editorTextFocus",
        "args": "knitr::wrap_rmd(${file})"
    },
]
```

**Comment by MilesMcBain** [comment]
I've not used vsocde variables before, but it seems that they're not generally supported in keybindings and settings if I understand this page correctly: https://code.visualstudio.com/docs/editor/variables-reference

Placeholders work a little differently in the R extension, see this section of the wiki:

https://github.com/Ikuyadeu/vscode-R/wiki/Keyboard-shortcuts#creating-keybindings-for-r-commands

Your example would be:

```
[
    {
        "description": "Wrap long lines in Rmd files in knitr",
        "key": "alt+shift+w",
        "command": "r.runCommandWithEditorPath",
        "when": "editorTextFocus",
        "args": "knitr::wrap_rmd(\"$$\")"
    },
]
```
