### ISSUE TITLE
Make R code auto-completion work within in-line R chunk

### ISSUE THREAD

**Issue by jooyoungseo** [Ikuyadeu/vscode-R#609]
While code completion does work in block chunk, it does not work inside in-line R chunk.

Examples are as follows:

````
``` r
# Hit ctrl+spacebar to invoke auto-suggestion after typing the following line:
ggp
```
````

````
# The following does not work:
`r ggp`
````

**Comment by renkun-ken** [comment]
The completion is provided by languageserver. Please raise an issue at <https://github.com/REditorSupport/languageserver/issues>.
