### ISSUE TITLE
Commented lines are not ignored when determining code blocks

### ISSUE THREAD

**Issue by andycraig** [Ikuyadeu/vscode-R#61]
It appears that the content of commented lines is taken into account when determining where a code block ends (i.e., when determining whether or not to keep sending lines to the console when using Ctrl-Enter).

- VSCode Version: 1.22.2
- VSCode-R Version: 0.5.6
- OS Version: Ubuntu 16.04.3
- R Version: 3.4.3

Steps to Reproduce:

1. Copy into editor:
```
for (i in 1:2) {
    print(i)
    # }
}
```

2. Position cursor on 'for' line and hit Ctrl-Enter.

Console output is:
```
> for (i in 1:2) {
+    print(i)
+
```

Desired console output is:
```
> for (i in 1:2) {
+        print(i)
+ }
[1] 1
[1] 2
>
```

This is a great extension by the way, thank you Ikuyadeu and contributors! :)

**Comment by Ladvien** [comment]
@andycraig Thanks for the detailed notes!  Working on this now.
