### ISSUE TITLE
Code chunks not highlighted and CodeLens commands not showing in Rmd files

### ISSUE THREAD

**Issue by nsandau** [Ikuyadeu/vscode-R#617]
**Describe the bug**
When editing Rmarkdown files the code chunks are not highlighted and CodeLens commands not showing.

**To Reproduce**
Create new Rmd file and create code chunk.

**Do you want to fix by self? (I hope your help!)**
Don't know how. 

**(If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)**

(If related)setting.json

```json
  "r.bracketedPaste": true,
  "r.sessionWatcher": true,
  "r.rterm.linux": "/home/nicolai/miniconda3/bin/radian",
  "r.rmarkdown.enableCodeLens": true,
  "r.rmarkdown.codeLensCommands": [
        "r.runCurrentChunk",
        "r.runAboveChunks",
        "r.runNextChunk"
    ],
  "r.rpath.linux": "/usr/lib/R/bin/R",
  "r.rmarkdown.chunkBackgroundColor": "rgba(128, 128, 128, 0.3)"
```

**Expected behavior**
Code chunks highlighted and CodeLens commands shown above the chunk. 

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/12936029/114185803-68350e00-9946-11eb-8fa7-eba0efe345e0.png)

**Environment (please complete the following information):**
 - OS: Pop_OS 20.10
 - VSCode Version: 1.55.1
 - R Version: 4.0.2
 - vscode-R version: 1.6.5

**Comment by renkun-ken** [comment]
Could you confirm that your `Rmd` document is using `R Markdown` language?

You could also associate `*.rmd` files with `rmd` language via the following setting:

```json
"files.associations": {
        "*.rmd": "rmd"
}
```

**Comment by nsandau** [comment]
Thank you so much! I have been trying to make it work for hours. 

It was somehow set to "markdown". Changing it to "rmd" solved it. 

Thanks again! and tanks for making this great extension.

**Comment by colinbrislawn** [comment]
I was missing your first part:
(I've included both parts here)

```json
  "r.rmarkdown.enableCodeLens": true,
  "r.rmarkdown.codeLensCommands": [
        "r.runCurrentChunk",
        "r.runAboveChunks",
        "r.runNextChunk"
    ],

    "files.associations": {
      "*.rmd": "rmd",
      "*.Rmd": "rmd"
    },

```
