### ISSUE TITLE
Session watcher won't update plots. 

### ISSUE THREAD

**Issue by FrederikFilip** [Ikuyadeu/vscode-R#624]
Thank you for a great extension!

I am using VS code to work on R on a server using Remote - SSH.
This has been working seamlessly for the last year.
I'm using the R session watcher to show my plots while working on them.
Now, the sessionwatcher is watching and showing my plots, but it won't **add** to the plot.

The most simple example would be the following R-code:
1. `plot(1,1)` --> the plot shows in sessionwathcer
2. `points(1,1.2)` --> the new point is **not** added to the plot

This is the case for all functionality adding to an already created plot, such as lines(), legend(), text(), etc.

I have tried reinstalling both VS code itself and the vscode-R extension.

## Do you want to fix by self? (We hope your help!)
No

**Environment (please complete the following information):**

- OS: Linux (remote)
- VSCode Version: 1.55.2
- R Version: 3.4.4
- vscode-R version: 1.6.6

**Comment by renkun-ken** [comment]
I could reproduce this. It is probably a regression introduced by #602. I'll take a closer look.

Before it is resolved, I suggest that you use [httpgd](https://github.com/nx10/httpgd) instead.

**Comment by renkun-ken** [comment]
@FrederikFilip you may download the [latest build](https://github.com/Ikuyadeu/vscode-R/releases/tag/latest) and it should work for you now.

**Comment by FrederikFilip** [comment]
> @FrederikFilip you may download the [latest build](https://github.com/Ikuyadeu/vscode-R/releases/tag/latest) and it should work for you now.

Awsome, thanks!
