### ISSUE TITLE
R language support doesn't work 

### ISSUE THREAD

**Issue by Whale-fall** [Ikuyadeu/vscode-R#627]
R-Languageserver seems to no more updated anymore.

**Describe the bug**
I installed this extension in vscode remote, the host environment is managed by anaconda.I install R via anaconda with multiple environments. Then I found this extension can not work partly.it seems that there is no syntax highlighting and autocompletion, R language server sends "R Language Server (undefined) started" and no more information.

```JSON
    "r.rpath.linux": "/home/yiliang/software/miniconda3/envs/biostar/bin/R",
    "r.rterm.linux": "/home/yiliang/software/miniconda3/envs/biostar/bin/R",
    "r.bracketedPaste": true,
    "r.lsp.debug": true,
    "r.sessionWatcher": true,
```
**Screenshots**
![image](https://user-images.githubusercontent.com/22662209/115362687-6136b700-a1f4-11eb-9945-7d8c22b4a9fc.png)

![image](https://user-images.githubusercontent.com/22662209/115360488-3f3c3500-a1f2-11eb-9ae7-f39325cc76b9.png)

![image](https://user-images.githubusercontent.com/22662209/115360680-6dba1000-a1f2-11eb-9df1-cc7cc4258a3d.png)

![image](https://user-images.githubusercontent.com/22662209/115362808-7f041c00-a1f4-11eb-8367-25d749e7d6e8.png)

> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /home/yiliang/software/miniconda3/envs/biostar/lib/libopenblasp-r0.3.12.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3 jsonlite_1.7.2 rlang_0.4.10 

**Environment (please complete the following information):**
- OS: 3.10.0-327.el7.x86_64
- VSCode Version:1.55.2
- R Version: 4.0.3
- vscode-R version: 1.66

**Comment by Whale-fall** [comment]
Please let me know if you need more information!

**Comment by MilesMcBain** [comment]
That is the path for the R terminal in vscode, the LSP uses the 'Rpath:Linux' path. They're separate because you can use Radian as your R terminal, but not with the `languageserver`. With your R set up you will need to add both. Or you can make sure R is added to the system PATH because I think we default to that now.

**Comment by MilesMcBain** [comment]
Oh sorry I see you did add 'Rpath' in your json.

**Comment by MilesMcBain** [comment]
and added it to PATH.

**Comment by MilesMcBain** [comment]
have you installed the `languageserver` R package? is it installed into the library associated with the R that is on the the PATH?

**Comment by renkun-ken** [comment]
`R Language Server (undefined) started` in the output looks a bit odd, suggesting it cannot start a process and get a pid?

**Comment by MilesMcBain** [comment]
I was wondering if it was some kind of issue due to languageserver version baked into conda.

**Comment by Whale-fall** [comment]
Yes, I installed the `languageserver` R package in different versions of R in different conda environments respectively. And both of `languageserver` is the latest version. I set `r.path` to `/home/yiliang/software/miniconda3/envs/biostar/bin/R`.

![image](https://user-images.githubusercontent.com/22662209/116642593-d6974a00-a9a1-11eb-9db5-90eeb5149e7b.png)
![image](https://user-images.githubusercontent.com/22662209/116642613-e31ba280-a9a1-11eb-85b4-cc2789eb4117.png)
Do you need other infomation?Thanks.

**Comment by renkun-ken** [comment]
Would you like to use "Toggle developer tools" and put a screenshot of the log and let me see if there's vscode-r-lsp error.

**Comment by Whale-fall** [comment]
![image](https://user-images.githubusercontent.com/22662209/116643823-75bd4100-a9a4-11eb-9b81-9d6f8b9096fa.png)
![image](https://user-images.githubusercontent.com/22662209/116643852-85d52080-a9a4-11eb-8361-7cee4372347a.png)

This is all the message that "Toggle developer tools" give

**Comment by renkun-ken** [comment]
Would you like to try manually running 

```
/home/yiliang/software/miniconda3/envs/biostar/bin/R --vanilla --quiet --slave -e 'languageserver::run(debug=TRUE)'
```

and see if it could start and wait for requests?

**Comment by renkun-ken** [comment]
This should be an issue in vscode-r-lsp where we cannot spawn an R process to run languageserver. So I'll close this one in favor of https://github.com/REditorSupport/vscode-r-lsp/issues/71.
