### ISSUE TITLE
Document symbol display in Rmd is not reliable

### ISSUE THREAD

**Issue by jooyoungseo** [Ikuyadeu/vscode-R#629]
I am not sure whether I had to file this issue on `languageserver` repo.

In R Markdown files, sometimes document symbols are not displayed in breadcrumbs view.

However, I have no idea what causes this issue. Please see the reprex below.

### Case 1: Document Symbol Appears Correctly

1. Download [this Rmd file](https://github.com/hadley/r4ds/blob/master/data-import.Rmd)
2. Open the file in VSCode.
3. Press `Ctrl+Shift+. (period)`.

### Case 2: Document Symbol Does Not Appear

1. Download [another Rmd file](https://github.com/hadley/r4ds/blob/master/data-visualize.Rmd)
2. Open the file in VSCode.
3. Press `Ctrl+Shift+. (period)`.

## System Info

Version: 1.55.2 (system setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by renkun-ken** [comment]
Document symbols are generated in languageserver. Please report issue there. Thanks!
