### ISSUE TITLE
'.vsc' not found

### ISSUE THREAD

**Issue by phisanti** [Ikuyadeu/vscode-R#631]
# Bug description

Running vscode in an EC2 remote machine. I am trying to see some plots but nothing happens. I checked the closed issues for similar cases and it seems I don't have the function `.vsc`. In addition, the workspace remains empty all the time.

# Reproduce error

1. Install r-base:
```
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          0.5                         
year           2021                        
month          03                          
day            31                          
svn rev        80133                       
language       R                           
version.string R version 4.0.5 (2021-03-31)
nickname       Shake and Throw    

```
2. Install R vscode extension (1.6.5)
3. Install R LSP client (0.1.5
4. Config settings

```
{
    "r.bracketedPaste": true,
    "r.alwaysUseActiveTerminal": true,
    "r.rpath.linux": "/usr/bin/R",
    "r.rterm.linux": "radian: /home/coder/miniconda3/bin/radian",
    "r.sessionWatcher": true,
    "r.lsp.path": "/usr/bin/R",
    "r.lsp.use_stdio": true,
    "r.lsp.debug": true
}
```

5. Run code
```R
r$> d <- data.frame(x = rnorm(100), 
    y = rnorm(100)) 
     
    View(d) 
    plot(d$x, d$y)                                                                                                                                                                                                  
Error in .External2(C_dataviewer, x, title) : unable to start data viewer
In addition: Warning message:
In View(d) : unable to open display
r$> ls.str(.vsc)                                                                                                                                                                                                    
Error in ls.str(.vsc) : object '.vsc' not found
```
# Environment

- OS: 
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

```
- VSCode Version: v1.54.2
- R Version: 4.0.5
- vscode-R version: 1.6.5

Thanks for the help. Feel free to close if not related.

**Comment by renkun-ken** [comment]
Looks like your R session does not source the init script. Are you using vscode remote ssh to connect to the server? How do you create the R terminal?

**Comment by renkun-ken** [comment]
Have you installed all the dependencies? The following is required:

```r
install.packages(c("jsonlite", "rlang"))
```

To use vscode-r-lsp properly:

```r
install.packages("languageserver")
```

**Comment by phisanti** [comment]
Hi,

I had already installed `languageserver`, but not the other two. I have just installed the others but the problem persists (no `.vsc `object). Is there a way to trigger a "debbuger" mode so that I can get detailed reports on what's going on in the background?

Regarding how I am running the R session, I am running a docker image of vscode in the EC2 and then pass the graphic interface to the `8888 `port. Once there, I run the command "radian" to start the R session. Finally I am not very sure what do you mean by "init scrip", if you could describe it, I could answer whether I run it or not.

**Comment by renkun-ken** [comment]
Well, this scenario is a bit tricky. We have immediate support of running vscode locally or with remote ssh/wsl/container extension. But in your case, I'm not sure if I know what you mean by "running a docker image of vscode"? You are running a vscode UI on remote server, and from the perspective of that server, the vscode is running locally?

If I understand this scenario correctly, would you like to try using vscode command "R: Create R terminal" and see if it works?

**Comment by phisanti** [comment]
That is an accurate description of what I am doing.

I tried to run the R terminal as you described but interestingly, I got the following error:

`Cannot find R client. Please check R path in preferences and reload.`

**Comment by renkun-ken** [comment]
In your settinggs

```
"r.rterm.linux": "radian: /home/coder/miniconda3/bin/radian"
```

This should be a valid path to radian, did you mean

```
"r.rterm.linux": "/home/coder/miniconda3/bin/radian"
```

**Comment by phisanti** [comment]
Solved! It was a silly mistake, in the path for radian says:
`"radian: /home/coder/miniconda3/bin/radian"`

Where I forgot to remove the `radian:` when I used the `whereis `command.

**Comment by renkun-ken** [comment]
If you prefer starting your own R session (maybe in a tmux window), you need to take a look at https://github.com/Ikuyadeu/vscode-R/wiki/R-Session-watcher#advanced-usage-for-self-managed-r-sessions.
