### ISSUE TITLE
`R: Go to Previous Chunk` does not work at the end of file

### ISSUE THREAD

**Issue by jooyoungseo** [Ikuyadeu/vscode-R#633]
`R: Go to Previous Chunk` does not work at the end of file whereas `R: Go to Next Chunk` works at the beginning.

1. Make a testing Rmd file.
2. Put your cursor in `para 1.` and execute `R: Go to Next Chunk` (this works: it will move your cursor inside chunk `a`).
3. This time, put your cursor in `Para 3.` and execute `R: Go to Previous Chunk` (this does NOT work: I was hoping to be moved to `b` chunk).

> Warning: Running the contributed command: 'r.goToPreviousChunk' failed. 

# `test.Rmd`

````
Para 1.

```{r a}
print("foo")
```

Para 2.

```{r b}
print("bar")
```

Para 3.
````

**Comment by renkun-ken** [comment]
Closed by #663
