### ISSUE TITLE
Run Source icon not showing in VSCode 1.56.0

### ISSUE THREAD

**Issue by renkun-ken** [Ikuyadeu/vscode-R#635]
In the editor toolbar, the "Run Source" button does not correctly show its icon in VSCode 1.56.0.

<img width="253" alt="image" src="https://user-images.githubusercontent.com/4662568/117227066-95db7d00-ae48-11eb-849e-7f3a4614558f.png">

**Comment by eitsupi** [comment]
(Maybe this should be a separate issue.) How about changing the icon design to VSCode built-in icons?
https://code.visualstudio.com/api/references/icons-in-labels

I think run or run-all are consistent with this usage.
![image](https://user-images.githubusercontent.com/50911393/117462966-21105c00-af8a-11eb-9db6-774e08412527.png)

The current icons seems to be using the images from VS 2015. (#21)

**Comment by hongooi73** [comment]
This appears to be fixed in VSCode 1.56.2.

**Comment by renkun-ken** [comment]
Yes, just noticed that. So closing this thread.

I also like the suggestion of @eitsupi to use the built-in icons. Would you like to file a separate issue for this?
