### ISSUE TITLE
Change the Run Source icon to VSCode built-in icons

### ISSUE THREAD

**Issue by eitsupi** [Ikuyadeu/vscode-R#639]
How about changing the icon design to VSCode built-in icons?
https://code.visualstudio.com/api/references/icons-in-labels

I think run or run-all are consistent with this usage.
![image](https://user-images.githubusercontent.com/50911393/117462966-21105c00-af8a-11eb-9db6-774e08412527.png)

The current icons seems to be using the images from VS 2015. (#21)

_Originally posted by @eitsupi in https://github.com/Ikuyadeu/vscode-R/issues/635#issuecomment-834448395_

**Comment by eitsupi** [comment]
At the moment, the `Run Source` icon that is displayed in R files and the `Knit Rmd` icon that is displayed in RMarkdown files are the same.
There was a suggestion to use other icons when adding the `Knit Rmd` command, but the choice was made to use the same icon. (#122)

![image](https://user-images.githubusercontent.com/50911393/118262804-6388ea00-b4f0-11eb-9591-f07ec55b7072.png)
![image](https://user-images.githubusercontent.com/50911393/118263912-e2caed80-b4f1-11eb-83c2-55cd3eb109c2.png)

If you set the build-in icon like run-all for `Run Source`, it may be more obvious to set a different icon for `Knit Rmd`.

**Comment by ElianHugh** [comment]
What if we use `run` for .R files and `run below` for .Rmd files?

**Comment by eitsupi** [comment]
Closed by #663
