### ISSUE TITLE
Session Watcher: Plot window don't update 

### ISSUE THREAD

**Issue by maillot-jaune** [Ikuyadeu/vscode-R#640]
The attached plot window do not update when commands are added after plot()

    plot(1)
    title(main="Test")

The title "Test" do not appear on the plot. If I disable the Session Watcher, the plot window is detached and everything works as expected. If I "source" the file (Ctrl+Shift+S) it works. And if I save the plot using `png()`, the saved file looks as expected:

    png(filename="/path/to/plot.png")
    plot(1)
    title(main="Test")
    dev.off()

**Environment**

- OS: Linux darkstar 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- VSCode Version: 1.56.2
- R Version: 3.6.3
- vscode-R version: 1.6.6

```
sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 20

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=sv_SE.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=sv_SE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=sv_SE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3
```

**Comment by renkun-ken** [comment]
It is already fixed by #625. Please use the [latest development build](https://github.com/Ikuyadeu/vscode-R/releases/tag/latest).

**Comment by maillot-jaune** [comment]
Sorry. Missed that one... works perfectly!

**Comment by renkun-ken** [comment]
You might be interested in using [httpgd](https://github.com/nx10/httpgd) which works quite well in vscode. See <https://renkun.me/2020/06/16/using-httpgd-in-vscode-a-web-based-svg-graphics-device/>.
