### ISSUE TITLE
Allow different program for R console

### ISSUE THREAD

**Issue by randy3k** [Ikuyadeu/vscode-R#65]
Right now, it is assumed that the default R console is used in the terminal. It has been [brought up](https://github.com/REditorSupport/languageserver/issues/11) by 
@joshualeond that an alternative is `rtichoke`. We should make it possible to specify a different program to use in the terminal. 

That means we need to change [getRpath()](https://github.com/Ikuyadeu/vscode-R/blob/master/src/rTerminal.ts#L10) to another function eg `getRconsole()` which reads settings `r.console.mac`, `r.console.windows` and `r.console.linux`. If they are not specified, we could use `r.term.xxx` as fallbacks.

**Comment by Ikuyadeu** [comment]
@randy3k Thank you for information!
I added `r.rpath.lsp` to use R.exe for language server.
