### ISSUE TITLE
Don't run `eval = FALSE` R Markdown chunks with code lens commands

### ISSUE THREAD

**Issue by jolars** [Ikuyadeu/vscode-R#651]
**Is your feature request related to a problem? Please describe.**

I sometimes put non-working/incomplete/only-for-demonstration code in R Markdown chunks and use `eval = FALSE` to have them not run when the document is knitted. When using the code lens commands in the extension, such as "Run Above", these chunks are still evaluated, which often causes errors.

**Describe the solution you'd like**

In R Studio, using "Run All" or "Run All Chunks Above" will skip running chunks with `eval = FALSE`, which I think is the correct behavior. I am hoping that this extension will adopt the same behavior.

Since vscode-R is already discovering R markdown chunks with what I suppose is some kind of regular expression, my naive guess is that it should be straightforward to also look for `eval = FALSE` in the code chunk header. I will probably be a little more work to get the extension to respect global `knitr::opts_chunk` settings in combination with code chunk header options, but that would of course be optimal.

**Describe alternatives you've considered**

I haven't considered any alternatives here.

**Comment by renkun-ken** [comment]
Looks like the pattern to extract chunk options requires a comma

https://github.com/Ikuyadeu/vscode-R/blob/6b9bf53e7a97028a9808f7532ad1eb655bd1c06f/src/rmarkdown.ts#L27-L29

But the comma is not necessary though. Are you interested in making a quick fix for this?

**Comment by jolars** [comment]
I actually considered that, and it doesn't seem like the comma matters (at least not on my end):

![evalfalsefail2](https://user-images.githubusercontent.com/13087841/119956441-64feeb80-bfa1-11eb-9a34-b213d5c5345a.gif)

I can take a stab at this during the weekend, but I know basically nothing about Java/TypeScript or VS code extension development so I can't guarantee that I'll be successful =)
