### ISSUE TITLE
Respect .DollarNames S3 method in autocompletion

### ISSUE THREAD

**Issue by hongyuanjia** [Ikuyadeu/vscode-R#654]
**Is your feature request related to a problem? Please describe.**

When doing autocompletion, `.DollarNames` S3 method is not respected. It would be great if it can work in a similar way as RStudio. Please see the example below:

**Describe the solution you'd like**

``` r
myClass <- R6::R6Class(
  classname = "myClass",
  public = list(
    initialize = function(x) {
      private$val <- x
    },
    get_val = function() return(private$val)
  ),
  private = list(
    val = NULL
  )
)

`$.myClass` <- function(x, i) {
  if (i == "A") return(x$get_val())
  NextMethod()
}

.DollarNames.myClass <- function(x, pattern = "") {
  grep(
    pattern,
    c("A", names(x)),
    value = TRUE,
    fixed = TRUE
  )
}

obj <- myClass$new(1)
```

<sup>Created on 2021-05-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**In RStudio**:

![rstudio](https://user-images.githubusercontent.com/20545387/120088823-1aa77700-c127-11eb-965f-905f3564c566.png)

**In VS Code**
![vscode](https://user-images.githubusercontent.com/20545387/120088856-5d694f00-c127-11eb-83f8-c37b91245658.png)

**Comment by ElianHugh** [comment]
Changing vsc.R from using `names()` to `.DollarNames()` appears to fix this. I haven't had much experience with .DollarNames() before, so I'm unsure if this would have any unintended consequences.

![image](https://user-images.githubusercontent.com/60372411/120763860-291ad780-c507-11eb-9042-8708fd145ac0.png)

**Comment by renkun-ken** [comment]
I don't find a problem using `.DollarNames()` except it might reduce performance when the object has a very long vector of `names` as it uses several `grep()` internally to do fuzzy finding.

```r
> ns <- baseenv()                                                                                                                                            

> microbenchmark::microbenchmark(names(ns), .DollarNames(ns))                                                                                                
Unit: microseconds
             expr      min       lq      mean   median        uq      max neval
        names(ns)  362.329  370.501  407.6089  374.288  387.7685 1023.431   100
 .DollarNames(ns) 2504.053 2521.983 2690.0429 2533.417 2610.4015 4432.138   100
```

**Comment by renkun-ken** [comment]
Looks like we could adopt the following:

```r
if (is.object(obj)) {
  info$names <- .DollarNames(obj)
} else if (is.recurve(obj)) {
  info$names <- names(obj)
}
```

Then even atomic vector that has a class with an implementation of `$.class` could work.

```r
x <- structure(c(a=1, b=2, c=3), class = "p")

`$.p` <- function(x, i) {
  x[[i]]
}

.DollarNames.p <- function(x, pattern = "") {
  grep(
    pattern,
    names(x),
    value = TRUE,
    fixed = TRUE
  )
}
```
