### ISSUE TITLE
Japanese characters corruption

### ISSUE THREAD

**Issue by ShortArrow** [Ikuyadeu/vscode-R#66]
- VSCode Version:1.2.2
- VSCode-R Version:
- OS Version: Windows 10 Pro 1709 16299.371

Steps to Reproduce:

1. In terminal(R interactive) run print method

```r
print("こんにちは")
```
2. result

```
[1] "ｱﾉｿﾍ"
```

(If related)setting.json

```json
// R.exe path for windows
"r.rterm.windows": "C:\\Program Files\\R\\R-3.4.4\\bin\\x64\\R.exe",

// R command line options (i.e: --vanilla)
"r.rterm.option": [],

// An optional encoding to pass to R when executing the file, i.e. 'source(FILE, encoding=ENCODING)'
"r.source.encoding": "UTF-8",

// Keeping focus when running
"r.source.focus": "editor",
```

**Comment by Ikuyadeu** [comment]
In my environment (Mac OS ) is work well.
I have a some cause of it.

1. .r file is not saved.
2. `run`(ctrl + enter) is not work, but `source`(ctrl + shift + s) is work

So, could you try `print("こんにちは")` on .r source file and save it.

**Comment by andycraig** [comment]
I believe this is https://github.com/Microsoft/vscode/issues/19837, an issue with the VSCode integrated terminal in Windows, and is not specific to R or Japanese characters. I have this problem too and haven't found a solution yet, but I will update if I do.

**Comment by Ikuyadeu** [comment]
One Japanese write the guide to fix it, please check it
https://qiita.com/surei/items/e5e22c70dd79c5603678

**Comment by ShortArrow** [comment]
Thank you very much. It worked well. However, I hope that permanent measures will be found.
