### ISSUE TITLE
Simplify README and update wiki

### ISSUE THREAD

**Issue by renkun-ken** [Ikuyadeu/vscode-R#668]
The README seems too long to be an effective introduction to the repo, and plenty of information presented in it is out-dated. I believe that in README, only the most important and up-to-date information should be presented.

I'd like to restructure (mostly simplify) the README to make everything brief and put links to wiki as the detailed documentation, i.e. the following points:

* Quick start
* Features
* Questions, bug reports, feature requests, and contribution

The original content should be mostly moved to wiki and I'll put links in "Features". Also, extensions we recommend users to install with vscode-R such as vscode-r-lsp and VSCode-R-Debugger should be introduced in README, so that user could get full R development experience including language service and debugging capabilities immediately.

**Comment by ElianHugh** [comment]
I think this would go a long way to making vscode-R more palatable for newcomers (see also some comments at #496 ).

There are a few repos that also have some nice formatting for reference:
- [julia-vscode](https://github.com/julia-vscode/julia-vscode)
- [vscode-python](https://github.com/Microsoft/vscode-python)

**Comment by renkun-ken** [comment]
Yes, those repos are exactly some good examples I'm looking at.

**Comment by Ikuyadeu** [comment]
Good, so we can put only three things like these extensions.

* `Install` or `Quick Start`
* Listing the functions and these detail links
* Adding QA link and document link
* ~~Data and telemetry~~ (We do not collect)

**Comment by renkun-ken** [comment]
Also, I suggest we turn on `r.sessionWatcher` by default and make it no longer labled as experimental.
