### ISSUE TITLE
WebView created by browser shows httpgd viewer toolbar buttons

### ISSUE THREAD

**Issue by renkun-ken** [Ikuyadeu/vscode-R#674]
With the latest vscode-insider (1.58.0-insider), the toolbar of the WebView created by `.vsc.browser()` contains httpgd plot viewer toolbar buttons in addition to the original buttons.

![image](https://user-images.githubusercontent.com/4662568/122516817-d16d8780-d041-11eb-9112-91d5d74d07cc.png)

```r
.vsc.browser("https://127.0.0.1/test") 
```

**Comment by ManuelHentschel** [comment]
I cannot reproduce this with the latest insider build. Is there any specific sequence of opening/focussing webviews that causes the buttons to appear?

```
Version: 1.58.0-insider (user setup)
Commit: 7dea6d7402b55671410a129661cad24b55aed9f4
Date: 2021-06-18T13:58:43.903Z
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by renkun-ken** [comment]
The problem is gone with the latest insider build. Closing now.
