### ISSUE TITLE
Extra characters added to submitted R commands

### ISSUE THREAD

**Issue by mvanio** [Ikuyadeu/vscode-R#675]
When submitting r code by pressing cmd + enter extra characters (unicode?) are added to the beginning and end of the line. Code will then not run. Submitting the code via the command palette and choosing `Run selected text in active terminal` works fine.

1. Add R code
2. Press cmd + enter to run.
3. Error seen in terminal, code not run
4. Run code with `Run selected text in active terminal`
5. No error. Code runs.

I have tried many things but cannot remedy. What is the issue here and how do I resolve it?

settings.json
```json
{
    "python.dataScience.askForKernelRestart": false,
    "terminal.integrated.inheritEnv": false,
    "security.workspace.trust.untrustedFiles": "open",
    "r.bracketedPaste": true,    
    "r.lsp.debug": true,
    "r.lsp.diagnostics": true,
    "r.rterm.mac": "/usr/local/bin/R",
    "r.path.mac": "/usr/local/bin/R",
    "r.rterm.option": [""],
    "launch": {
        "configurations": [
        ]
    },
  }
```
1.`print("vscode-R")`
2. cmd + enter
3. 
```
 00~print("vscode-R")01~
Error: unexpected numeric constant in "00~print("vscode-R")01"
```
4. Run selected text in active terminal
``` 
print("vscode-R")
[1] "vscode-R"
```

- OS: macOS
- VSCode Version: latest
- R Version: 4.0.2
- vscode-R version: latest

**Comment by renkun-ken** [comment]
You are using official R ("r.rterm.mac": "/usr/local/bin/R") as your R terminal, then `r.bracketedPaste` should be switched off as it is only intended to work with `radian` as the R terminal.

**Comment by mvanio** [comment]
@renkun-ken Thanks. That does solve the issue. I put `r.bracketedPaste` as true because I *was* getting errors trying to use  `radian`. Is there a recommended settings.json for vscode-R with radian?

**Comment by renkun-ken** [comment]
Only `"r.bracketedPaste": true` is required if you are using `radian`. Other settings have mostly nothing to do with it.
