### ISSUE TITLE
Typo in GitHub repository description

### ISSUE THREAD

**Issue by gvelasq** [Ikuyadeu/vscode-R#680]
**Describe the bug**
Thank you for recent updates simplifying language in the README and wiki (#668, #669).

This is a minor suggestion but the word 'documentation' is misspelled in the GitHub repository description (see below). I would suggest fixing the typo or simplifying the description to just read: 'R Extension for Visual Studio Code'.

**To Reproduce**

1. Go to https://github.com/Ikuyadeu/vscode-R
2. See repository description (screenshot attached below)

![Screen Shot 2021-06-20 at 6 58 15 PM](https://user-images.githubusercontent.com/20712598/122690947-61960300-d1e1-11eb-8469-552eb17ef8e3.png)

AFAIK, this can only be fixed by the repository owner @Ikuyadeu.

**Comment by Ikuyadeu** [comment]
@gvelasq Thank you for the information. Now it is updated.

**Comment by renkun-ken** [comment]
I guess "lint" could be removed as it is done by R language server?

**Comment by Ikuyadeu** [comment]
@renkun-ken I agree with you.
