### ISSUE TITLE
Running lintr does nothing

### ISSUE THREAD

**Issue by cddesja** [Ikuyadeu/vscode-R#69]
- VSCode Version: 1.23.0 (1.23.0)
- VSCode-R Version: 0.5.9
- OS Version: macOS 10.13.4

Steps to Reproduce:

1.  Open R script
2.  Try to run lintr 
3. Nothing happens

I have lintr installed and tried loading lintr, too.

**Comment by andycraig** [comment]
I think this should be resolved now that linting is fully provided by the language server, so I’m going to close this. But if anyone is still having problems along these lines, please reply and we’ll have another look.
