### ISSUE TITLE
Doesn't work once kills the R terminal

### ISSUE THREAD

**Issue by michaelHL** [Ikuyadeu/vscode-R#7]
I found this bug before going to bed...
Everything is okay until I kill the R terminal, by `q()` in R, or kill the terminal simply by clicking the trash can button🗑:

![run selected](http://i.imgur.com/M5xUUp2.gif) | ![run source](http://i.imgur.com/mYwaKDi.gif) | ![force kill](http://i.imgur.com/GFqK3cv.gif)
------------ | ------------- | -------

It gives no response at all.

---

Tested on

- Windows 10 1607 x64
- VSC 1.12.2
- R version 3.4.0 (2017-04-21)

Good Night! 🌙

**Comment by Ikuyadeu** [comment]
Good morning @michaelHL, Thank you for submit issue!
Ok, I'll fix but solving this problem need little time.
Please use `create R term` command for now.

**Comment by michaelHL** [comment]
That Works! 😆

**Comment by Ikuyadeu** [comment]
@michaelHL OK, I fixed! Please wait next publish.
