### ISSUE TITLE
[Feature request] Support highlighting for yaml front matter of Rmarkdown document

### ISSUE THREAD

**Issue by psychelzh** [Ikuyadeu/vscode-R#71]
`.Rmd` is now well highlighted in the main document, but there is no support for highlighting for `yaml` front matter. Will it be supported in the future?

**Comment by Ikuyadeu** [comment]
@psychelzh Thank you for using and issue.
Looks little difficult, but actually it should be supported by this extension.
I put this as `want help`

**Comment by psychelzh** [comment]
Thanks. And I also filed an issue in vscode Microsoft/vscode#49604

**Comment by Ikuyadeu** [comment]
Yes, I think so.

**Comment by andycraig** [comment]
It might be possible to handle this as an Embedded Language: https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages

**Comment by psychelzh** [comment]
But I do believe this is supported in newer versions of vscode. See the following screenshots.

![image](https://user-images.githubusercontent.com/13306020/70105373-93855a00-167b-11ea-8c22-fb5b4c725409.png)

**Comment by andycraig** [comment]
@psychelzh Thank you for pointing this out! I hadn't realised this was supported at all. I checked just now and found that on Linux it is indeed highlighted, but on Windows there is no highlighting even with VSCode 1.40.

**Comment by andycraig** [comment]
Check of the highlighting info on Windows:

```
---
title: "highlighting test"
author: "me"
---

**Text!**

# Hello
```

![yaml-windows](https://user-images.githubusercontent.com/23294156/70145524-9ddb3e80-16e3-11ea-97bb-caaf04a7c98e.jpg)

**Comment by andycraig** [comment]
Linux:

![yaml-linux](https://user-images.githubusercontent.com/23294156/70146581-d54aea80-16e5-11ea-98ba-472200a57f16.png)

Windows and Linux are showing the front matter as different languages. Not sure why this would be.

**Comment by psychelzh** [comment]
@andycraig Interestingly, I am using Windows 10 now, which is normal.😱

**Comment by andycraig** [comment]
@psychelzh Oh! In that case it is almost certainly something specific to my system. I’ll try reinstalling VSCode etc. Thank you for letting me know!

**Comment by andycraig** [comment]
It's confirmed working on both Linux and Windows, and whatever problem I'm having on Windows is probably related to VSCode rather than vscode-R, so let's close this.
