### ISSUE TITLE
commands not running

### ISSUE THREAD

**Issue by iainmstott** [Ikuyadeu/vscode-R#72]
- VSCode Version: 1.23.1
- VSCode-R Version: v0.5.9
- OS Version: Win10 x64 Enterprise build 15063

Basic problem: none of the commands are working. e.g. CTRL+ENTER from an R file gives 
"command r.runSelection not found"

The same thing happens with other commands (e.g. r.lintr, r.previewEnvironment), and there's no option to create an integrated R terminal (although is of course accessible by entering 'R' into bash).

I searched around for an answer and came across this: Microsoft/vscode#44148
Maybe Excel Viewer is creating some problem? I can't disable or uninstall as vscode-R depends on it...

**Comment by Ikuyadeu** [comment]
@iainmstott  Thank you for using this extension!
Please open directory that has R source files.
I put about it on https://github.com/Ikuyadeu/vscode-R#faq .

**Comment by iainmstott** [comment]
Oops, I'm sorry. I thought I had read everything but somehow I didn't notice that. Thanks for replying so quickly

**Comment by zhongjiaxin1993** [comment]
Could you tell me that which file is R source file?  I also meet the error "r.runselection not fund", and I changed different R location, it doesn't work

**Comment by ohmlovesampere** [comment]
I don't understand. What's your meaning of "open directory that has R source files", open the file where I downloaded the R Gui?
I also meet this problem, thanks for your help.

**Comment by NicholasLangevin** [comment]
I think what he mean is don't just open `file1.R` in vscode, but open the folder `work` in vscode and then edit `file1.R`.
```
work/
    data/
    file1.R
    file2.R
```

**Comment by wwyi1828** [comment]
> 
> 
> I think what he mean is don't just open `file1.R` in vscode, but open the folder `work` in vscode and then edit `file1.R`.
> 
> ```
> work/
>     data/
>     file1.R
>     file2.R
> ```

Thank you so much! It does help me!

**Comment by wwyi1828** [comment]
> 
> 
> @iainmstott Thank you for using this extension!
> Please open directory that has R source files.
> I put about it on https://github.com/Ikuyadeu/vscode-R#faq .

Thank you!

**Comment by WT215** [comment]
> I think what he mean is don't just open `file1.R` in vscode, but open the folder `work` in vscode and then edit `file1.R`.
> 
> ```
> work/
>     data/
>     file1.R
>     file2.R
> ```

Thank you! This is crystal clear!

**Comment by michaeldorman** [comment]
Due to a recent update (I guess of VScode, on Ubuntu), I now get the "command r.runSelection not found" error when opening a file on double-click and trying to send R code to the terminal, which previously worked fine. Opening the folder (File -> Open Folder...) like @Ikuyadeu kindly suggested does solve the problem. However, I wonder if there is a way to get the previous behavior, where runSelection worked without having to set up a folder... Thanks!

![Screenshot from 2020-11-22 10-32-41](https://user-images.githubusercontent.com/9386655/99898983-84ddeb80-2cae-11eb-8e50-4857d0d0abfe.png)

**Comment by renkun-ken** [comment]
Looks like the extension activation is broken when workspace folder is undefined. Let me take a closer look on this.

**Comment by michaeldorman** [comment]
Thank you very much! It would be really great to get back the old behavior

**Comment by renkun-ken** [comment]
@michaeldorman Should be fixed via #456.

**Comment by michaeldorman** [comment]
@renkun-ken Thank you very much! I don't know if there is a way to install the development version of the extension to test this, will be happy to do so if you can please let me know how. Otherwise will wait for the automatic (?) update of the extension.

**Comment by renkun-ken** [comment]
@michaeldorman You could download the vsix built from that PR at https://github.com/Ikuyadeu/vscode-R/actions/runs/377123811 and install it in vscode.

**Comment by michaeldorman** [comment]
I downloaded & installed using:

```sh
code --install-extension vscode-R.vsix
``` 

confirming that this solves the problem. There is no "command r.runSelection not found" error message anymore, commands can be sent to console without setting up a folder. 

Thank you very much for the quick response and help!

**Comment by renkun-ken** [comment]
@michaeldorman Good to know that it works for you. We should have checked more thoroughly somehow with the tests.

**Comment by malcook** [comment]
FWIW - having a similar problem as a newbie to vscode-R, I learned that I can get the same issue of R not being discovered if my settings.json is saved with a syntax error (as I inadvertently created when saving settings for r.rterm.windows lacking double back-slashes).
