### ISSUE TITLE
No lintr Support for Rmd files?

### ISSUE THREAD

**Issue by ldsands** [Ikuyadeu/vscode-R#73]
- VSCode Version: 1.23.1
- VSCode-R Version: 0.5.9
- OS Version: Windows 10

As far as I can tell lintr works fine in normal r scripts but I do not see any lintr suggestions in rmd files. Am I missing something?

**Comment by Ikuyadeu** [comment]
@ldsands Thank you for using this extension.
Sorry, I did not support lintr for `rmd`.
However, request for rmd is increasing. Please wait next update.

**Comment by ldsands** [comment]
Sounds good, I look forward to the update!

**Comment by andycraig** [comment]
Linting is now provided by the language server. It lints Rmd files for me on Windows so I think this is probably resolved. Closing, but please post if you’re still experiencing this issue.
