### ISSUE TITLE
Error on formatting empty source file

### ISSUE THREAD

**Issue by renkun-ken** [Ikuyadeu/vscode-R#77]
- VSCode Version: 1.24.1
- VSCode-R Version: 0.6.0
- OS Version: macOS 10.13.5

Steps to Reproduce:

1. Create an empty R script and save to a folder
1. Format document

Then the output shows that an error occurs:

```
[Error - 7:32:24 PM] Request textDocument/formatting failed.
  Message: attempt to select less than one element in integerOneIndexdocument[[ndoc]]

  Code: -32603 
```

**Comment by Ikuyadeu** [comment]
@renkun-ken Thank you for your issue!
Could you tell me how did you format R script?

**Comment by renkun-ken** [comment]
The formatting is done by R LSP I think through `languageserver` package.

**Comment by Ikuyadeu** [comment]
OK, It looks vscode-lsp problem, I moved this to https://github.com/REditorSupport/vscode-r-lsp/issues/10.
