### ISSUE TITLE
Command XXX not found

### ISSUE THREAD

**Issue by swraithel** [Ikuyadeu/vscode-R#78]
- VSCode Version: 1.2.2
- VSCode-R Version: R 3.4.4
- OS Version: Windows 10

Steps to Reproduce:

1. Install extension via Marketplace
2. Open folder with  source r script per: https://github.com/Ikuyadeu/vscode-R#faq
3. F1 key and r.runSource
4. recieve "command 'command 'r.runSource' not found'

Attempts:
modify settings.json (the r.rterm.windows was set to R version 3.5 by defualt)

I've tried all the steps recommended in the FAQ and https://github.com/Ikuyadeu/vscode-R/issues/6

![image](https://user-images.githubusercontent.com/28785238/41785823-593c395e-7609-11e8-8445-df5b781b7403.png)

**Comment by swraithel** [comment]
@Ikuyadeu Any suggestions for debugging?

**Comment by swraithel** [comment]
For those who are having trouble installing the following worked for me:

1.  In R terminal run `install.packages("languageserver")`
2.  From VS Code install the 'R LSP Client'
3. Reload VS Code

Note: First time hitting Cntrl+Enter will load up R terminal only, anything after that will run selected line in terminal

![image](https://user-images.githubusercontent.com/28785238/43601180-4d7a1816-9652-11e8-9501-64442774cff1.png)

**Comment by Ikuyadeu** [comment]
@swraithel Sorry for my reply is late.

> Note: First time hitting Cntrl+Enter will load up R terminal only, anything after that will run selected line in terminal

is other problem and it is not fixed, thank you for your notification.

**Comment by SCTX** [comment]
I was also having trouble getting "R Extension Pack" to work and getting the same errors that the original poster mentioned. Here's what finally worked for me:
- Set r.rterm.windows in VS Code Settings to my executable,"C:\Program Files\R\R-3.5.1\bin\Rterm.exe"
- Set r.lsp.path in VS Code Settings to my executable, "C:\Program Files\R\R-3.5.1\bin\Rterm.exe"

After this, I was still receiving error messages. In VS Code Settings, I checked "r.lsp.debug" and in the output, I could see that an R library "processx" was outdated. I opened R and did an install.packages("processx").

Finally, I had to follow the advice [here](https://github.com/Ikuyadeu/vscode-R#faq) and File... Open Folder... to the directory with my R script in it. Finally, it worked.

**Comment by jooyoungseo** [comment]
@Ikuyadeu, has the issues been fixed?: First-time Ctrl+Enter still only launches R session.

> @swraithel Sorry for my reply is late.
> 
> > Note: First time hitting Cntrl+Enter will load up R terminal only, anything after that will run selected line in terminal
> 
> is other problem and it is not fixed, thank you for your notification.
