### ISSUE TITLE
'Run Source' doesn't work fine occasionally

### ISSUE THREAD

**Issue by michaelHL** [Ikuyadeu/vscode-R#8]
I find that occasionally when I execute the commands `R: Run Source` (or by keyboard shortcut) and the integrated terminal open an `R` session (not source my code actually) so I have to source it again.

Does it mean the code has been sent to the terminal before starting an `R` session so I cannot see any command in the terminal? It really bothers me in spite of it's a small problem... 😅 

And also the `R: Run Selection/Line` has the same problem.:grimacing:

---

- Windows 10 1607 Build 14393
- VSC 1.12.2
- vscode-R 0.2.9

**Comment by michaelHL** [comment]
And also the `R: Run Selection/Line` has the same problem.:grimacing:

**Comment by Ikuyadeu** [comment]
@michaelHL Oh, I known that problem in old version and I fixed, so I forgot.
 OK, I'll fix. Thank you for your issue!

**Comment by Ikuyadeu** [comment]
@michaelHL I updated this function many time.
Is this bug fine yet?

**Comment by michaelHL** [comment]
@Ikuyadeu Sorry for taking time to get back to you, and it works well for me now! 😄
Thank you!!!

**Comment by Ikuyadeu** [comment]
@michaelHL It's good.
Thank you for your information.

**Comment by chuanwen** [comment]
I got this same issue today with latest version.
