### ISSUE TITLE
Only support sending code to local R Interactive

### ISSUE THREAD

**Issue by renkun-ken** [Ikuyadeu/vscode-R#80]
- VSCode Version: 1.24.1
- VSCode-R Version: 0.6.0
- OS Version: macOS 10.13.5

Currently, `Send Code` ignores the existing vscode terminal. An R Interactive is always open.

My case is that I ssh logined a server in the vscode terminal and start an R session there. Therefore, whenever I send code, it is desired that the code be sent to the existing terminal rather than always open a new local R session.

**Comment by Atrebas** [comment]
For sending the code to the terminal, I use `ctrl + F8`.
I think I created this shortcut. It runs `workbench.action.terminal.runSelectedText` ([link](https://code.visualstudio.com/docs/editor/integrated-terminal#_key-bindings)).

**Comment by diazdc** [comment]
I also use R via ssh and have the same question. Executing code until the command ends with the default `cmd + enter` (i.e. the way vscode-R and Rstudio do) is very useful. Mapping `workbench.action.terminal.runSelectedText` to a shortcut works, but it's not as seamless as having the cursor skip to the next to the command with one shortcut. Hopefully there is a simple solution to this.

**Comment by andycraig** [comment]
I don't know of a simple solution to this, unfortunately. I'm thinking about trying to add a new command `Use existing R terminal` that would associate the editor with the current terminal and allow `Run Selection/Line` to work as normal. If this is possible (if!) I think it would solve this issue, although if anyone has any suggestions about a better alternative approach I'd be keen to hear them.

This might also help with #102 if changes between terminals aren't too frequent.

**Comment by andycraig** [comment]
I've decided to take a slightly different approach. I am working on a new command that will allow code to be sent to the currently active terminal, which should provide a solution to this problem.
