### ISSUE TITLE
Support for outlines in vscode?

### ISSUE THREAD

**Issue by ipstone** [Ikuyadeu/vscode-R#84]
Hello,

Thank you for this extension!
This is more of a feature question: somehow vscodes doesn't support symbols/outlines for R, is there a way to add such functionalities to VS Code (for R)?

https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline

in vim, such functionality are supported through plugins such as ctags/taglist/tagbar, etc.

Best,
Isaac

**Comment by Ikuyadeu** [comment]
@ipstone Thank you for information. It looks good function!
However, I didn't understand yet, how to implement.
So, I put it as todo.

**Comment by ipstone** [comment]
hi @Ikuyadeu - perhaps this link is helpful for providing outline view function for vscode R: https://github.com/Microsoft/vscode-go/blob/master/src/goOutline.ts

I am relative new to vscode - will explore more to see how to add this feature.

**Comment by Ikuyadeu** [comment]
@ipstone Thank you for additional information!
I checked, it looks fit for language server protocol than here.
I will survey more.

**Comment by atanasj** [comment]
I would love this feature... Not sure where it is best handled, but please (someone... anyone!) bring this one. 👍

**Comment by andycraig** [comment]
I agree that this is a language server feature. The language server would need an implementation of `DocumentSymbolProvider`.

**Comment by andycraig** [comment]
Language server issue for this: https://github.com/REditorSupport/languageserver/issues/46

**Comment by andycraig** [comment]
This is now supported by the latest version of the language server. Until it’s updated on CRAN, it can be installed with:

    devtools::install_github("REditorSupport/languageserver")

**Comment by ipstone** [comment]
just a quick comment: install the language server (default): works fine for my setup: `install.packages("languageserver")`
