### ISSUE TITLE
Use rterm from docker image

### ISSUE THREAD

**Issue by paulklemm** [Ikuyadeu/vscode-R#87]
Is it possible to tell the extension to use the `rterm` located on a `docker` image?

A typical call for an interactive `R` session using the `r-base` image looks like 

```bash
docker run -ti --rm r-base R
```

**Comment by Ikuyadeu** [comment]
@paulklemm Thank you for using and issue.
I did not try to use docker, but could you try to edit `R > Rterm.windows` or `R > Rterm.Mac`  to
`docker run -ti --rm r-base R`

**Comment by paulklemm** [comment]
I did that and it seems that it doesn't work, I don't get any autocomplete suggestions or other indications that it finds `R` properly.

**Comment by Ikuyadeu** [comment]
Thank you early reply.
Sorry, it is limited for this extension.

**Comment by vnijs** [comment]
If you "attach" to a running container using VSCode (see link) below you would get the R terminal (or even better, use radian) from the container. You can do the same with VSCode through SSH to connect to R on a remote server.

https://code.visualstudio.com/docs/remote/containers#_attaching-to-running-containers

**Comment by renkun-ken** [comment]
Yes, Remote Development should be the right way, and it supports SSH, WSL, and Docker.

**Comment by paulklemm** [comment]
Unfortunately, this is not a feasible solution for me. I already am running VSCode via the SSH package to connect to a compute cluster. Here, I run R using a Singularity Container (Docker, but suitable for HPC). With vscode-r-lsp it works using a wrapper script https://github.com/REditorSupport/vscode-r-lsp/issues/23

**Comment by paulklemm** [comment]
Actually, with the session watcher feature this might be obsolete since I can simply attach vscode-r to any running R session. https://github.com/Ikuyadeu/vscode-R#r-session-watcher-experimental. https://renkun.me/2019/12/26/writing-r-in-vscode-interacting-with-an-r-session/ @renkun-ken Great write up, will check that out right away!

**Comment by renkun-ken** [comment]
@paulklemm The R session watcher requires that vscode-R and the R session both access the same filesystem in the working directory. It works for the following cases:

* Local workspace, local terminal
* Remote Development via SSH/WSL/Docker

while it does not work with

* Local workspace, ssh to a remote terminal (since vscode-R cannot directly access the remote filesystem)

**Comment by paulklemm** [comment]
Because of the caching, I see. Thanks for clarifying. Since I run Remote Development via SSH, the R session watcher works perfect for me.

**Comment by renkun-ken** [comment]
@paulklemm Glad to know it works for you :)
