### ISSUE TITLE
Run Selection/Line only executes the first line of file when nothing was selected

### ISSUE THREAD

**Issue by michaelHL** [Ikuyadeu/vscode-R#9]
(with extension [vim](https://github.com/VSCodeVim/Vim) installed)

<p align="center">
<img src="http://i.imgur.com/7EOmIs0.gif">
</p>

When nothing is selected, the default behavior of `R: Run Selection/Line` executes the first line of the current file. 

And, I suggest that after performing `R: Run Selection/Line`, the cursor should move to next line(when nothing is selected) or next code block, just like in RStudio:

<p align="center">
<img src="http://i.imgur.com/tan0MGm.gif">
</p>

**Comment by Ikuyadeu** [comment]
@michaelHL Thank you, Looks good!
OK, I'll study RStudio Code. But maybe It'll take much time.

**Comment by Ikuyadeu** [comment]
@michaelHL  I just fixed bugs in new version but
> And, I suggest that after performing R: Run Selection/Line, the cursor should move to next line(when nothing is selected) or next code block, just like in RStudio:
>
is yet.
I'll add this function.

**Comment by Ikuyadeu** [comment]
Fixed by @Ladvien's #13, so closing.

**Comment by michaelHL** [comment]
@Ikuyadeu Many thanks! An excellent feature! 😄
