### ISSUE TITLE
Please remove dependency on Excel Viewer

### ISSUE THREAD

**Issue by stegmueller** [Ikuyadeu/vscode-R#90]
Would it be possible to remove the dependency on Excel Viewer (or make it optional). It adds an incredible amount of latency to VSCode.

**Comment by stegmueller** [comment]
Here is an illustration of the time it uses at startup:
![image](https://user-images.githubusercontent.com/9674007/46685703-1a4bbd80-cbc4-11e8-840f-6948c31a3dfe.png)

**Comment by Ikuyadeu** [comment]
@stegmueller Thank you for useful information! 
I wondered why this extension is heavy. I'll update this weekend!

**Comment by Ikuyadeu** [comment]
sorry late, fixed
