### ISSUE TITLE
please help:  r and visual studio code

### ISSUE THREAD

**Issue by goldirana** [Ikuyadeu/vscode-R#91]
hi, 
i installed r tool and git which is integrated with visual studio code and i can't run my r code in visual studio code, command written in user setting in visual studio code is
{   
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "r.rterm.windows": "C:\\Program Files\\R\\R-3.5.0\\bin\\x64\\R.exe"
}

showing error: ( Please find r client, please check r prefrences and reload) as i already installed r extension in visual code
WHERE I AM doing wrong please help me
thanks in advance

**Comment by Ikuyadeu** [comment]
@goldirana Thank you for your issue!

I did not see ever this error. Could you tell me which command did you try? 
If you have screenshot, it will help us.

There are current cause option.
* R version is different. How to Solve: Check your folder `C:\Program Files\R\R-3.5.0\bin\x64\`
* This extension is not enabled yet. How to Solve: reload vscode.

**Comment by goldirana** [comment]
yeah u r right sir, i downgrade my version to 3.3.3 and it just start working, i can't even say thank you so much.
