### ISSUE TITLE
Save as: incorrect file extension for .R files

### ISSUE THREAD

**Issue by mstenemo** [Ikuyadeu/vscode-R#95]
This has been referenced here: https://github.com/Microsoft/vscode/issues/28425 and https://github.com/Microsoft/vscode/issues/62054#issuecomment-434149025

Steps to Reproduce:

Try to "save as" on a file with file extension ".r"

Do you want to fix by self? (I hope your help!)

Yes

(If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)
Should be easy according to https://github.com/Microsoft/vscode/issues/62054#issuecomment-434149025

**Comment by renkun-ken** [comment]
Feel free to reopen if you still encounter this problem.
