### ISSUE TITLE
Highlighting for .R files not working

### ISSUE THREAD

**Issue by wdomi** [Ikuyadeu/vscode-R#99]
Hi there,

I don't seem to manage to get the highlighting to work for my .R files. What am I missing? I have already tried to go through all the settings twice and looked for answers online, unfortunately without luck.

Comments are green, logicals (true/false) are bright blue and string shows as brown whereas the rest of the code is dark blue, but apart from this, I don't get the nice (and most of all useful) color highlighting I see in your snapshots. Just as a matter of information, I work on a mac.

How can I fix this?

Would be very grateful for any help or hint about what the problem could be.
Dominique

**Comment by Ikuyadeu** [comment]
@wdomi Thank you for using.
I could not understand how is your code.
Could you put your screenshot?
And, you can edit this file to fix highlight
https://github.com/Ikuyadeu/vscode-R/blob/master/syntax/r.json

**Comment by wdomi** [comment]
Hi,

Thank you for attaching again the json link. I am sorry to say that I don't understand how to edit it to fix the problem.

Here a screenshot

![screenshot 2019-02-20 08 50 57](https://user-images.githubusercontent.com/20965917/53078231-10cc4d80-34f4-11e9-8f36-acbc653374ba.png)

here a snapshot of another R file (using tidyverse syntax).

![image](https://user-images.githubusercontent.com/20965917/53078876-70772880-34f5-11e9-8dc4-656e0a6e3d22.png)

Many thanks for your help.

Dominique

**Comment by Hong-Revo** [comment]
This doesn't seem to be related to the R extension. You just need to change your theme to something that uses more colours. Note that most light themes aren't that flashy; if you want lots of colours, try a dark theme.

**Comment by wdomi** [comment]
Oh man, thanks so much! This was very helpful!
Sorry to bother you with such a naive issue!

Many thanks!
dominique
